/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beagle_BeagleNative4StateImpl */

#ifndef _Included_beagle_BeagleNative4StateImpl
#define _Included_beagle_BeagleNative4StateImpl
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     beagle_BeagleNative4StateImpl
 * Method:    calculateStatesStates
 * Signature: ([I[D[I[DII[D)V
 */
JNIEXPORT void JNICALL Java_beagle_BeagleNative4StateImpl_calculateStatesStates
  (JNIEnv *, jobject, jintArray, jdoubleArray, jintArray, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     beagle_BeagleNative4StateImpl
 * Method:    calculateStatesPartials
 * Signature: ([I[D[D[DII[D)V
 */
JNIEXPORT void JNICALL Java_beagle_BeagleNative4StateImpl_calculateStatesPartials
  (JNIEnv *, jobject, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     beagle_BeagleNative4StateImpl
 * Method:    calculatePartialsPartials
 * Signature: ([D[D[D[DII[D)V
 */
JNIEXPORT void JNICALL Java_beagle_BeagleNative4StateImpl_calculatePartialsPartials
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     beagle_BeagleNative4StateImpl
 * Method:    calculateLogLikelihoods
 * Signature: ([D[D[DII[D[D)V
 */
JNIEXPORT void JNICALL Java_beagle_BeagleNative4StateImpl_calculateLogLikelihoods
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
