/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beagle_basta_BastaJNIWrapper */

#ifndef _Included_beagle_basta_BastaJNIWrapper
#define _Included_beagle_basta_BastaJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    allocateCoalescentBuffers
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_allocateCoalescentBuffers
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    getBastaBuffer
 * Signature: (II[D)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_getBastaBuffer
  (JNIEnv *, jobject, jint, jint, jdoubleArray);

/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    updateBastaPartials
 * Signature: (I[II[IIII)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_updateBastaPartials
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jint, jint);

/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    accumulateBastaPartials
 * Signature: (I[II[III[D)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateBastaPartials
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jdoubleArray, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateBastaPartialsGrad
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jdoubleArray, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_updateBastaPartialsGrad
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jint, jint);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_updateTransitionMatricesGrad
  (JNIEnv *, jobject, jint, jintArray, jdoubleArray, jint);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_allocateCoalescentGradBuffers
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_updateBastaPartialsPopSizeGrad
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jint, jint);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateBastaPartialsPopSizeGrad
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint, jdoubleArray, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_getMatrixAdjoint
  (JNIEnv *, jobject, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_getPopulationSizeGradient
  (JNIEnv *, jobject, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_setExpmKernels
  (JNIEnv *, jobject, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateExpmGradient
  (JNIEnv *, jobject, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_transformMatrixAdjoints
  (JNIEnv *, jobject, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_backTransformEigenBasisGradient
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateEigenBasisGradient
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray);

JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_uploadBastaSlabMetadata
  (JNIEnv *, jobject, jint, jintArray, jint);


JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_getBastaSlabConstants
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
