/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beagle_basta_BastaJNIWrapper */

#ifndef _Included_beagle_basta_BastaJNIWrapper
#define _Included_beagle_basta_BastaJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    updateBastaPartials
 * Signature: (I[III)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_updateBastaPartials
  (JNIEnv *, jobject, jint, jintArray, jint, jint);

/*
 * Class:     beagle_basta_BastaJNIWrapper
 * Method:    accumulateBastaPartials
 * Signature: (I[II[II)I
 */
JNIEXPORT jint JNICALL Java_beagle_basta_BastaJNIWrapper_accumulateBastaPartials
  (JNIEnv *, jobject, jint, jintArray, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
