"""Plan step C1: the cubins the plugin embeds (kernels/BeagleTinyGPU_cubins.S and their table kernels/TinyGPUNVCubins.h, both
generated by make_tinygpu_cubins.sh), the C++ runtime's use of them (TinyGPUHybridNVCubins.h), and the daemon's runtime handoff.
- golden_cubins.cpp, linked with the generated .S as the plugin is, selects and loads every entry and checks the refusals (DP,
  a state count, an architecture, an entry holding another architecture's cubin);
- the table holds exactly the 9 SP modules x sm_86, sm_89, sm_120, and every embedded cubin is byte-identical to
  nv_compile_helper.compile_ptx of the PTX the plugin embeds (tgpaths.cubin: the daemon's compile_all, cached by the PTX's
  sha256), which also catches a cubin filed under the wrong state count and a changed ptxas;
- each cubin's kernel names equal nv_compile_helper's (compile_all's reply), and nvd_elf_sm reads the architecture in the file
  name of every cubin in the harness cache;
- the build's ptxas (TINYGPU_CUBINS_STAMP) is the one the daemon's compile_all runs (nv_compile_helper._ptxas_path), so the
  embedded cubins and the other modes' run-time cubins come from the same ptxas;
- the real Daemon.cmd_handoff for the C++ runtime right after boot (no compile_all, so no ELF): elf_size 0, then the blob and
  the four fds, and nothing else;
- the real Daemon.cmd_boot never selects tinygrad's renderer (on macOS that builds its compiler, which starts tinygrad's Docker
  compile server), and cmd_compile_all checks it, refusing NAK, before its first ptxas cubin."""
import os, re, sys, io, json, types, ctypes, struct, socket, subprocess, contextlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tgpaths
tgpaths.setup()
import nv_dispatch_daemon as d
import nv_compile_helper as nch
from tinygrad.runtime.autogen import nv
from tinygrad.runtime.support.memory import TLSFAllocator, MMIOInterface

ARCHS, MB = ("sm_86", "sm_89", "sm_120"), 1 << 20

def embedded():
    work = tgpaths.WORK / "golden_cubins"
    work.mkdir(parents=True, exist_ok=True)
    for f in work.glob("SP_*"): f.unlink()
    tgpaths.build_cpp(tgpaths.HERE / "golden_cubins.cpp", work / "golden_cubins", str(tgpaths.GPU_DIR / "kernels/BeagleTinyGPU_cubins.S"))
    cached = sorted((tgpaths.DATA / "cubins").glob("*.cubin"))   # <sha16>_<arch>.cubin
    r = subprocess.run([str(work / "golden_cubins"), str(work), *map(str, cached)], capture_output=True, text=True)
    print(r.stdout + r.stderr, end="")
    ok = r.returncode == 0
    tags, want = sorted(f.stem for f in work.glob("SP_*.cubin")), sorted(f"{v}_{a}" for v in tgpaths.VARIANTS for a in ARCHS)
    ok &= tags == want
    print(f"table: {len(tags)} cubins, " + ("the 9 SP modules x sm_86, sm_89, sm_120" if tags == want else f"expected {want}"))
    for v in tgpaths.VARIANTS:
        for a in ARCHS:
            if f"{v}_{a}" not in tags: continue
            elf = (work / f"{v}_{a}.cubin").read_bytes()
            same = elf == tgpaths.cubin(v, a)
            names = sorted((work / f"{v}_{a}.names").read_text().split()) == sorted(nch.extract_all_metadata(elf)[1])
            ok &= same and names
            print(f"{v:<6} {a:<6} {len(elf):7d} bytes: {'==' if same else 'DIFFERS FROM'} compile_ptx of KERNELS_STRING_{v}; "
                  f"kernel names {'equal' if names else 'DIFFER FROM'} nv_compile_helper's")
    for line in r.stdout.splitlines():
        if not line.startswith("SM "): continue
        _, sm, path = line.split(" ", 2)
        good = f"sm_{sm}" == os.path.basename(path)[:-len(".cubin")].split("_", 1)[1]
        ok &= good
        print(f"{os.path.basename(path)}: nvd_elf_sm {sm}, {'matching' if good else 'NOT matching'} the file name")
    stamp = re.search(r'#define TINYGPU_CUBINS_STAMP "(.*) @ ', (tgpaths.GPU_DIR / "kernels/TinyGPUNVCubins.h").read_text()).group(1)
    runtime = subprocess.run([nch._ptxas_path(), "--version"], capture_output=True, text=True).stdout.strip().splitlines()[-1]
    ok &= stamp == runtime
    print(f"ptxas: the build's '{stamp}' {'is' if stamp == runtime else 'is NOT'} compile_all's ({nch._ptxas_path()}: '{runtime}')")
    return ok

def runtime_handoff():
    """The real cmd_handoff (programs false) right after boot (rig as test_p3.test_handoff_wpr_refusal, default pool)."""
    real_build = d.build_handoff
    try:
        pa = TLSFAllocator((8188 - 64 - 2 - 16) * MB, base=(2 + 16) * MB)
        views, fds = [], {}
        def alloc(size, spec=None):
            views.append((ctypes.c_uint8 * 64)()); view = MMIOInterface(ctypes.addressof(views[-1]), 64)
            fds[view.addr] = os.open(os.devnull, os.O_RDONLY)
            return types.SimpleNamespace(va_addr=pa.alloc(size, 0x1000), size=size, cpu_view=lambda: view)
        impl = types.SimpleNamespace(fmc_boot=False, vram_size=8188 * MB, mm=types.SimpleNamespace(pa_allocator=pa),
                                     gsp=types.SimpleNamespace(wpr_meta=bytes(nv.GspFwWprMeta(gspFwRsvdStart=0x1f3a00000))))
        dev = types.SimpleNamespace(allocator=types.SimpleNamespace(alloc=alloc), synchronize=lambda: None, error_state=None,
                                    iface=types.SimpleNamespace(dev_impl=impl, pci_dev=types.SimpleNamespace(sysmem_fds=fds), compute_class=0xc9c0),
                                    sass_version=0x89, shared_mem_window=0, local_mem_window=0, num_gpcs=3, num_tpc_per_gpc=4,
                                    num_sm_per_tpc=2, max_warps_per_sm=48)
        d.build_handoff = lambda dev, progs, bufs: ({"qmd_ver": 3}, b"blob")
        a, b = socket.socketpair()
        dm = d.Daemon(b, 7); dm.dev = dev   # booted; no compile_all, so no ELF
        with contextlib.redirect_stderr(io.StringIO()): dm.cmd_handoff({"cmd": "handoff", "programs": False})
        b.close()   # everything the handoff sent is buffered in a, then EOF
        data, got = b"", []
        while True:
            chunk, f, _, _ = socket.recv_fds(a, 1 << 16, 4)
            if not chunk: break
            data, got = data + chunk, got + f
        for f in got + list(fds.values()): os.close(f)
        n = struct.unpack_from("<I", data)[0]
        reply, tail = json.loads(data[4:4 + n]), data[4 + n:]
    finally: d.build_handoff = real_build
    ok = reply.get("ok") and reply.get("elf_size") == 0 and reply.get("blob_size") == 4 and tail == b"blobF" and len(got) == 4
    print(f"runtime handoff after boot only: elf_size {reply.get('elf_size')}, then {tail!r} and {len(got)} fds: {'ok' if ok else 'FAIL'}")
    return ok

def recv_reply(sock):
    n = struct.unpack("<I", sock.recv(4, socket.MSG_WAITALL))[0]
    return json.loads(sock.recv(n, socket.MSG_WAITALL))

def renderer_after_boot():
    """cmd_boot on a stub device whose renderer property records each selection; then cmd_compile_all (ptxas stubbed)."""
    from tinygrad import Device
    selected = []
    class Dev:
        arch = "sm_89"
        def __init__(self, renderer): self._renderer = renderer
        @property
        def renderer(self): selected.append(1); return self._renderer
    real = type(Device).__getitem__, nch.compile_ptx, nch.extract_all_metadata
    ok, compiles = True, []   # how many renderer selections had happened at each compile_ptx call
    try:
        nch.compile_ptx = lambda *a, **k: compiles.append(len(selected)) or b"elf"
        nch.extract_all_metadata = lambda elf, is_blackwell=False: (None, {"kernelA": None})
        for renderer, nak in ((object(), False), (d.ops_nv.NAKRenderer.__new__(d.ops_nv.NAKRenderer), True)):
            selected.clear(); compiles.clear()
            type(Device).__getitem__ = lambda self, name, r=renderer: Dev(r)
            a, b = socket.socketpair(); a.settimeout(5)
            dm = d.Daemon(b)
            with contextlib.redirect_stderr(io.StringIO()): dm.cmd_boot({})
            boot, at_boot = recv_reply(a), len(selected)
            with contextlib.redirect_stderr(io.StringIO()): dm.cmd_compile_all({"ptx_path": "unused"})
            comp = recv_reply(a)
            good = boot == {"ok": True, "arch": "sm_89"} and at_boot == 0 and len(selected) > 0 and \
                   (comp.get("ok") is False and "NAKRenderer" in comp.get("error", "") and compiles == [] if nak else
                    comp == {"ok": True, "kernels": ["kernelA"]} and len(compiles) == 1 and compiles[0] > 0)   # checked before ptxas
            ok &= good
            print(f"boot with a {'NAK' if nak else 'ptxas'} renderer: renderer selected {at_boot}x at boot, then at compile_all: "
                  f"{'refused' if not comp.get('ok') else 'compiled'}: {'ok' if good else 'FAIL'}")
    finally: type(Device).__getitem__, nch.compile_ptx, nch.extract_all_metadata = real
    return ok

if __name__ == "__main__":
    ok = embedded()
    ok &= runtime_handoff()
    ok &= renderer_after_boot()
    print("C1: all passed" if ok else "C1: FAILED")
    sys.exit(0 if ok else 1)
