"""Offline tests for plan step C4: the firmware manifest is what tinygrad's boot and nv_init_helper's teardown fetch
(regenerated byte for byte, every URL's md5 its cache name); TinyGPUFirmware.h returns, for every manifest entry, the bytes
tinygrad's own fetch_fw returns with the network off (from BEAGLE's cache, where check_firmware.py staged them), and fails
where fetch_fw would have to download when downloads are off; it searches $BEAGLE_TINYGPU_FW, share/beagle/firmware and
BEAGLE's cache in that order, never tinygrad's cache, rejects a 2,679-byte HTML page and a partial download, and says how to
fetch; it downloads a missing file into BEAGLE's cache (from a file:// mirror), checks it and keeps nothing bad; tinygpu_fetch_firmware.sh fetches (from a file:// copy), checks and refuses a bad file,
for NVIDIA's chips and the AMD cards' gfx1100 and gfx1201 (TODO.md plan step N13);
nvd_elf_load reads the ELF32 FMC image, the ELF64 GSP image and small ELF32 and ELF64 objects with relocations exactly as
tinygrad's elf_loader does. No GPU, no network.
    python test_c4_firmware.py"""
import os, sys, json, shutil, hashlib, pathlib, subprocess, urllib.request
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tgpaths
tgpaths.setup()
from tinygrad import helpers
from tinygrad.runtime.support.elf import elf_loader

GPU, W = tgpaths.GPU_DIR, tgpaths.WORK / "c4"
PROBE = W / "bin" / "c4_probe"   # share/beagle/firmware is then W/share/beagle/firmware
SHARE = W / "share" / "beagle" / "firmware"
BEAGLE_CACHE = pathlib.Path.home() / "Library" / "Caches" / "beagle" / "firmware"   # the probe runs without XDG_CACHE_HOME
HTML = (b"<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Sign in \xc2\xb7 GitLab</title></head>\n<body>"
        + b"<p>You need to sign in or sign up before continuing.</p>" * 60)[:2679 - 16] + b"</body></html>\n\n"
assert len(HTML) == 2679

def offline(*a, **k): raise RuntimeError("network access attempted")
urllib.request.urlopen = offline   # fetch() imports urllib.request at call time: no download can happen here

def sha(b): return hashlib.sha256(b).hexdigest()

def manifest():
    text = (GPU / "TinyGPUFirmwareManifest.h").read_text()
    base = text.split('kLinuxFirmware = "')[1].split('"')[0]
    rows = []
    for line in text.splitlines():
        if line.startswith('    {"'):
            f = line.split("}")[0].strip(" {").replace('"', "").split(", ")
            rows.append(dict(zip(("chip", "role", "subdir", "name", "sha256", "url_md5"), f)))
    return base, rows

def amd_rows():   # TinyGPUAMDBootTables.h's fw table: the AMD card's firmware, in the manifest's row format
    text = (GPU / "TinyGPUAMDBootTables.h").read_text().split("namespace fw {")[1].split("} // namespace fw")[0]
    return [dict(zip(("chip", "role", "subdir", "name", "sha256", "url_md5"), l.split("}")[0].strip(" {").replace('"', "").split(", ")))
            for l in text.splitlines() if l.startswith('    {"')]

def probe(*args, stderr=False, **env):   # downloads off unless the caller turns them on (BEAGLE_TINYGPU_NO_DOWNLOAD="0")
    e = {k: v for k, v in os.environ.items() if k not in ("BEAGLE_TINYGPU_FW", "XDG_CACHE_HOME", "BEAGLE_TINYGPU_FW_BASE_URL")}
    e["BEAGLE_TINYGPU_NO_DOWNLOAD"] = "1"
    e.update({k: str(v) for k, v in env.items()})
    r = subprocess.run([str(PROBE), *args], env=e, capture_output=True, text=True, timeout=300)
    assert r.returncode == 0, r.stderr
    rows = [json.loads(l) for l in r.stdout.splitlines()]
    return (rows, r.stderr) if stderr else rows

def located(out, chip, role): return next(x for x in out if x["chip"] == chip and x["role"] == role)

def test_manifest():
    gen = W / "gen"; gen.mkdir(parents=True, exist_ok=True)
    subprocess.run([sys.executable, str(GPU / "make_tinygpu_fw_manifest.py"), str(gen)], check=True, capture_output=True)
    assert (gen / "TinyGPUFirmwareManifest.h").read_bytes() == (GPU / "TinyGPUFirmwareManifest.h").read_bytes(), "stale manifest: rerun it"
    base, rows = manifest()
    assert base == "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de"
    for r in rows: assert hashlib.md5(f"{base}/{r['subdir']}/{r['name']}".encode()).hexdigest() == r["url_md5"], r
    assert {(r["chip"], r["role"]) for r in rows} == {(c, x) for c in ("ga102", "ad102") for x in ("booter_load", "gsp", "bootloader", "booter_unload")} \
        | {("gb202", x) for x in ("fmc", "gsp", "bootloader")}
    print(f"manifest: regenerated byte for byte from tinygrad's own fetch_fw calls, {len(rows)} entries, each md5(url) its cache name")

def test_locate_equals_fetch_fw():
    _, rows = manifest()
    out, found = probe("locate"), 0
    for r in rows:
        got = located(out, r["chip"], r["role"])
        try: b = helpers.fetch_fw(r["subdir"], r["name"], r["sha256"])
        except RuntimeError as e:
            assert "network access attempted" in str(e) and "error" in got, (r, got)   # fetch_fw would download it: so both fail
            assert "the download: not tried (BEAGLE_TINYGPU_NO_DOWNLOAD is set)" in got["error"], got
            continue
        assert "error" not in got, got
        assert (got["size"], got["sha256"]) == (len(b), sha(b)) == (len(b), r["sha256"]), (r, got)
        assert got["path"] == str(BEAGLE_CACHE / r["subdir"] / r["name"]), got   # where check_firmware.py staged it
        found += 1
    assert found >= 8, found   # all of ad102's and gb202's, and ga102's gsp and booter_unload, are staged here
    print(f"locate: the bytes fetch_fw returns (network off) for all {found} staged entries, from BEAGLE's cache; "
          f"an error naming the fetch for the {len(rows) - found} it would download")

def test_search_order():
    _, rows = manifest()
    r = next(x for x in rows if (x["chip"], x["role"]) == ("ad102", "booter_load"))
    real = helpers.fetch_fw(r["subdir"], r["name"], r["sha256"])
    rel = pathlib.Path(r["subdir"]) / r["name"]
    fw1, xdg = W / "fw1", W / "xdg"
    shutil.rmtree(fw1, ignore_errors=True); shutil.rmtree(xdg, ignore_errors=True); shutil.rmtree(W / "share", ignore_errors=True)
    def put(root, data):
        (root / rel).parent.mkdir(parents=True, exist_ok=True)
        (root / rel).write_bytes(data)
    cache = xdg / "beagle" / "firmware" / rel
    tg_cache = xdg / "tinygrad" / "downloads" / "fw" / r["url_md5"]
    put(fw1, HTML)                    # a GitLab sign-in page saved in place of the firmware
    put(SHARE, real[:20000])          # a partial download
    tg_cache.parent.mkdir(parents=True); tg_cache.write_bytes(real)   # a good file where tinygrad keeps it: not searched
    err = located(probe("locate", BEAGLE_TINYGPU_FW=fw1, XDG_CACHE_HOME=xdg), "ad102", "booter_load")["error"]
    for want in (f"$BEAGLE_TINYGPU_FW {fw1 / rel}: 2679 bytes with sha256 {sha(HTML)}, not this file",
                 f"/../share/beagle/firmware/{rel}: 20000 bytes with sha256 {sha(real[:20000])}, not this file",
                 f"BEAGLE's download cache {cache}: not found",
                 "the download: not tried (BEAGLE_TINYGPU_NO_DOWNLOAD is set)",
                 "To fetch it by hand into BEAGLE's cache:", f"curl -fL -o '{cache}' '",
                 f"https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de/{rel}",
                 f"shasum -a 256 '{cache}'", f"(shasum must print {r['sha256']})", "tinygpu_fetch_firmware.sh"):
        assert want in err, (want, err)
    assert "tinygrad's download cache" not in err and str(tg_cache) not in err, err
    put(xdg / "beagle" / "firmware", real)
    got = located(probe("locate", BEAGLE_TINYGPU_FW=fw1, XDG_CACHE_HOME=xdg), "ad102", "booter_load")
    assert got.get("path") == str(cache) and got["sha256"] == r["sha256"], got
    put(fw1, real)
    assert located(probe("locate", BEAGLE_TINYGPU_FW=fw1, XDG_CACHE_HOME=xdg), "ad102", "booter_load")["path"] == str(fw1 / rel)
    put(fw1, HTML); put(SHARE, real)   # the first good place wins: share/, before the cache
    got = located(probe("locate", BEAGLE_TINYGPU_FW=fw1, XDG_CACHE_HOME=xdg), "ad102", "booter_load")
    assert got["path"].endswith(f"/bin/../share/beagle/firmware/{rel}") and got["sha256"] == r["sha256"], got
    (SHARE / rel).unlink()
    err = located(probe("locate", XDG_CACHE_HOME=W / "empty"), "ad102", "booter_load")["error"]
    assert "$BEAGLE_TINYGPU_FW: not set" in err and err.count(": not found") == 2, err
    shutil.rmtree(W / "share")
    print("search order: $BEAGLE_TINYGPU_FW, share/beagle/firmware, BEAGLE's cache, and not tinygrad's cache; the first file "
          "with the manifest's sha256 wins; a 2,679-byte HTML page and a partial download are reported and skipped; the error "
          "gives the URL, curl and shasum into BEAGLE's cache")

def test_download():
    # the user's request (2026-10-01): a missing file is downloaded into BEAGLE's cache, from a file:// mirror here
    _, rows = manifest()
    have = [r for r in rows if r["chip"] in ("ad102", "gb202")]   # staged on this Mac (ga102's booter_load and bootloader are not)
    mirror, bad, xdg = W / "mirror", W / "mirror_bad", W / "xdg_dl"
    for d in (mirror, bad, xdg): shutil.rmtree(d, ignore_errors=True)
    for r in have:
        for root in (mirror, bad):
            p = root / r["subdir"] / r["name"]
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(HTML if root == bad and r["role"] == "bootloader" else helpers.fetch_fw(r["subdir"], r["name"], r["sha256"]))
    on = dict(BEAGLE_TINYGPU_NO_DOWNLOAD="0", BEAGLE_TINYGPU_FW_BASE_URL=f"file://{mirror}", XDG_CACHE_HOME=xdg)
    out, err = probe("locate", stderr=True, **on)
    cache = lambda r: xdg / "beagle" / "firmware" / r["subdir"] / r["name"]
    for r in have:
        got = located(out, r["chip"], r["role"])
        assert got.get("path") == str(cache(r)) and got["sha256"] == r["sha256"], got
    files = {(r["subdir"], r["name"]) for r in have}
    for sd, nm in files: assert err.count(f"TinyGPU: downloaded {sd}/{nm} into ") == 1, (sd, nm, err)   # each once, then cached
    ga = located(out, "ga102", "booter_load")["error"]   # not in the mirror: curl fails, nothing kept
    assert "the download: curl failed" in ga and not (xdg / "beagle/firmware/nvidia/ga102/gsp/booter_load-570.144.bin").exists(), ga
    out2, err2 = probe("locate", stderr=True, **on)   # now from the cache, with nothing downloaded
    assert all(located(out2, r["chip"], r["role"]).get("path") == str(cache(r)) for r in have) and "downloading NVIDIA firmware nvidia/ad102" not in err2, err2
    shutil.rmtree(xdg)
    out3 = probe("locate", **dict(on, BEAGLE_TINYGPU_FW_BASE_URL=f"file://{bad}"))   # a bootloader that is an HTML page: refused
    for r in have:
        if r["role"] != "bootloader": continue
        e3 = located(out3, r["chip"], "bootloader")["error"]
        assert f"is 2679 bytes with sha256 {sha(HTML)}, not this file" in e3 and not cache(r).exists(), e3
    assert not list(xdg.rglob("*.part.*")), list(xdg.rglob("*"))
    out4 = probe("locate", XDG_CACHE_HOME=W / "empty2")   # downloads off: the old error, nothing tried
    assert "the download: not tried (BEAGLE_TINYGPU_NO_DOWNLOAD is set)" in located(out4, "ad102", "gsp")["error"]
    print(f"download: {len(files)} missing files fetched from a file:// mirror into BEAGLE's cache, each sha256-checked, then "
          "found there with nothing fetched; a missing one and an HTML page in place of one refused with nothing kept; "
          "BEAGLE_TINYGPU_NO_DOWNLOAD=1 keeps the network off")

def test_fetch_script():
    _, rows = manifest()
    tree, dest, bad = W / "tree", W / "dest", W / "tree_bad"
    for d in (tree, dest, bad): shutil.rmtree(d, ignore_errors=True)
    ad = [r for r in rows if r["chip"] == "ad102"]
    for r in ad:
        for root in (tree, bad):
            p = root / r["subdir"] / r["name"]
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(HTML if root == bad and r["role"] == "booter_unload" else helpers.fetch_fw(r["subdir"], r["name"], r["sha256"]))
    script = str(GPU / "tinygpu_fetch_firmware.sh")
    def run(*args, base=tree):
        return subprocess.run([script, *map(str, args)], env=dict(os.environ, TINYGPU_FW_BASE_URL=f"file://{base}"), capture_output=True, text=True)
    r1 = run("--chip", "ad102", dest)
    assert r1.returncode == 0 and r1.stdout.count("fetched: ") == 4 and "export BEAGLE_TINYGPU_FW=" in r1.stdout, r1
    r2 = run("--chip", "ad102", dest)
    assert r2.returncode == 0 and r2.stdout.count("present: ") == 4, r2
    out = probe("locate", BEAGLE_TINYGPU_FW=dest)
    for r in ad: assert located(out, "ad102", r["role"])["path"] == str(dest / r["subdir"] / r["name"]), r
    shutil.rmtree(dest)
    r3 = run("--chip", "ad102", dest, base=bad)
    unload = dest / "nvidia/ad102/gsp/booter_unload-570.144.bin"
    assert r3.returncode == 1 and "FAILED: nvidia/ad102/gsp/booter_unload-570.144.bin" in r3.stderr and not unload.exists(), r3
    assert not list(dest.rglob("*.part.*")) and r3.stdout.count("fetched: ") == 3, r3
    r4 = run("--chip", "gb202", dest)   # fmc and bootloader are not in the copy: curl fails, nothing kept (gsp is there already)
    assert r4.returncode == 1 and r4.stderr.count("FAILED: ") == 2 and "present: " in r4.stdout and not list((dest / "nvidia/gb202").rglob("*.bin*")), r4
    r5 = run("--chip", "tu102", dest)
    assert r5.returncode == 2 and "lists no firmware for tu102" in r5.stderr, r5
    am = amd_rows()   # the AMD cards' blobs (six gfx1100, eight gfx1201), as fetch_fw returns them from tinygrad's cache
    counts = {c: sum(1 for r in am if r["chip"] == c) for c in {r["chip"] for r in am}}
    assert counts == {"gfx1100": 6, "gfx1201": 8}, counts
    for r in am:
        p = tree / r["subdir"] / r["name"]
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(helpers.fetch_fw(r["subdir"], r["name"], r["sha256"]))
    for chip, n in sorted(counts.items()):
        r6 = run("--chip", chip, dest)
        assert r6.returncode == 0 and r6.stdout.count("fetched: ") == n, r6
        assert all(sha((dest / r["subdir"] / r["name"]).read_bytes()) == r["sha256"] for r in am if r["chip"] == chip), r6
        r7 = run("--chip", chip, dest)
        assert r7.returncode == 0 and r7.stdout.count("present: ") == n, r7
    print("fetch script: fetches and checks every file of a chip (file:// copy), keeps a good file, refuses an HTML page in "
          "place of one and a missing one (nothing kept), refuses an unknown chip; the locator then finds them; the AMD cards' "
          "six gfx1100 and eight gfx1201 blobs the same way")

def elf_rows(path, align=1):
    img, secs, rel = elf_loader(pathlib.Path(path).read_bytes(), force_section_align=align)
    want = [dict(section=s.name, type=s.header.sh_type, addr=s.header.sh_addr, offset=s.header.sh_offset, size=s.header.sh_size,
                 addralign=s.header.sh_addralign, entsize=s.header.sh_entsize, link=s.header.sh_link) for s in secs]
    want.append(dict(image_size=len(img), image_sha256=sha(bytes(img))))
    return want + [dict(reloc=list(r)) for r in rel]

def test_elf():
    _, rows = manifest()
    cache = helpers._ensure_downloads_dir() / "fw"
    files = [(cache / next(r["url_md5"] for r in rows if r["role"] == "fmc"), 1), (cache / next(r["url_md5"] for r in rows if r["role"] == "gsp"), 1)]
    src = W / "reloc.c"
    src.write_text("static int x = 3; static int y[4] = {1, 2, 3, 4};\nint f(void) { return x + y[2]; }\nint *g(void) { return &x; }\n")
    for target in ("i386-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "arm-none-eabi"):
        obj = W / f"reloc_{target.split('-')[0]}.o"
        subprocess.run(["clang", "-target", target, "-fno-pic", "-c", str(src), "-o", str(obj)], check=True, capture_output=True)
        files += [(obj, 1), (obj, 0x80)]
    classes = set()
    for path, align in files:
        got, want = probe("elf", path, hex(align)), elf_rows(path, align)
        assert got == want, (path, align, [(g, w) for g, w in zip(got, want) if g != w][:3], len(got), len(want))
        classes.add((pathlib.Path(path).read_bytes()[4], sum("reloc" in x for x in want) > 0))
    assert classes >= {(1, False), (2, False), (1, True), (2, True)}, classes
    print(f"nvd_elf_load: sections, image and relocations identical to elf_loader for the ELF32 FMC image, the ELF64 GSP image "
          f"and ELF32 (i386, ARM) and ELF64 objects with REL and RELA relocations ({len(files)} loads)")

if __name__ == "__main__":
    PROBE.parent.mkdir(parents=True, exist_ok=True)
    tgpaths.build_cpp(tgpaths.HERE / "c4_probe.cpp", PROBE)
    test_manifest()
    test_locate_equals_fetch_fw()
    test_search_order()
    test_download()
    test_fetch_script()
    test_elf()
    print("C4 firmware manifest, locator, fetch script and ELF32: all passed")
