"""Paths shared by the TinyGPU offline harness (see README.md). Importing this touches no device.

Override with environment variables:
  TINYGRAD_PATH        the pinned tinygrad tree (default ~/Dropbox/Projects/tinygrad-hcq1, as nv_dispatch_daemon.py)
  BEAGLE_TINYGPU_DATA  cached cubins, firmware, captures, references, run logs (default ~/.beagle/tinygpu)
  TINYGPU_TEST_WORK    scratch outputs of a test run (default tinygpu_tests/.work, git-ignored)
"""
import os, sys, hashlib, pathlib, subprocess

HERE = pathlib.Path(__file__).resolve().parent
GPU_DIR = HERE.parent                                   # libhmsbeagle/GPU
REPO = GPU_DIR.parent.parent
TINYGRAD_PATH = os.environ.get("TINYGRAD_PATH", str(pathlib.Path.home() / "Dropbox/Projects/tinygrad-hcq1"))
DATA = pathlib.Path(os.environ.get("BEAGLE_TINYGPU_DATA", pathlib.Path.home() / ".beagle/tinygpu"))
WORK = pathlib.Path(os.environ.get("TINYGPU_TEST_WORK", HERE / ".work"))
KERNELS_H = GPU_DIR / "kernels/BeagleTinyGPU_kernels.h"   # generated by the TinyGPUKernels build target
VARIANTS = ("SP_4", "SP_32", "SP_64", "SP_128")

def setup():
    """Put the pinned tinygrad and libhmsbeagle/GPU (the daemons are the oracle) first on sys.path."""
    for p in (str(GPU_DIR), TINYGRAD_PATH):
        if p not in sys.path: sys.path.insert(0, p)
    WORK.mkdir(parents=True, exist_ok=True)

def cxx():
    return os.environ.get("CXX", "clang++")

def build_cpp(src, out, *extra):
    """Compile a harness C++ program against the in-tree headers."""
    subprocess.run([cxx(), "-std=c++17", "-O1", "-Wall", "-Wextra", f"-I{REPO}", *extra, "-o", str(out), str(src)], check=True)

def ptx(variant):
    """BEAGLE's PTX module for a kernel variant, exactly as the plugin embeds it (KERNELS_STRING_<variant>)."""
    WORK.mkdir(parents=True, exist_ok=True)
    out = WORK / f"beagle_{variant}.ptx"
    if not out.exists() or out.stat().st_mtime < KERNELS_H.stat().st_mtime:
        exe = WORK / f"ptx_extract_{variant}"
        build_cpp(HERE / "ptx_extract.cpp", exe, f"-DVARIANT=KERNELS_STRING_{variant}", "-w")
        out.write_bytes(subprocess.run([str(exe)], check=True, capture_output=True).stdout)
    return out.read_bytes()

def cubin_path(ptx_bytes, arch):
    """Cache key: the PTX's sha256 prefix, so a regenerated kernels header never reuses a stale cubin."""
    return DATA / "cubins" / f"{hashlib.sha256(ptx_bytes).hexdigest()[:16]}_{arch}.cubin"

def cubin(variant, arch):
    """The ptxas cubin for a variant, compiled once with nv_compile_helper.compile_ptx (the daemon's own compile)."""
    p = cubin_path(ptx(variant), arch)
    if not p.exists():
        setup()
        import nv_compile_helper as nch
        print(f"compiling {variant} for {arch} with ptxas (not cached at {p}) ...", flush=True)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(nch.compile_ptx(str(WORK / f"beagle_{variant}.ptx"), arch, kernel_name="_all"))
    return p.read_bytes()
