"""Paths shared by the TinyGPU offline harness (see README.md). Importing this touches no device.

Override with environment variables:
  TINYGRAD_PATH        the pinned tinygrad tree (default ~/Dropbox/Projects/tinygrad-hcq1, as nv_dispatch_daemon.py)
  BEAGLE_TINYGPU_DATA  cached cubins, firmware, captures, references, run logs (default ~/.beagle/tinygpu)
  TINYGPU_TEST_WORK    scratch outputs of a test run (default ~/Library/Caches/beagle-tinygpu-tests: per computer, since the
                       repo may be a synced folder shared between computers)
"""
import os, sys, hashlib, pathlib, subprocess

HERE = pathlib.Path(__file__).resolve().parent
GPU_DIR = HERE.parent                                   # libhmsbeagle/GPU
ORACLE = HERE / "oracle"                                # the NV and AMD daemons and their helpers, tinygrad plus BEAGLE's patches (C13b, A2l)
REPO = GPU_DIR.parent.parent
TINYGRAD_PATH = os.environ.get("TINYGRAD_PATH", str(pathlib.Path.home() / "Dropbox/Projects/tinygrad-hcq1"))
DATA = pathlib.Path(os.environ.get("BEAGLE_TINYGPU_DATA", pathlib.Path.home() / ".beagle/tinygpu"))
WORK = pathlib.Path(os.environ.get("TINYGPU_TEST_WORK", pathlib.Path.home() / "Library/Caches/beagle-tinygpu-tests"))
KERNELS_H = GPU_DIR / "kernels/BeagleTinyGPU_kernels.h"   # generated by the TinyGPUKernels build target
VARIANTS = tuple(f"SP_{n}" for n in (4, 16, 32, 48, 64, 80, 128, 192, 256))   # make_tinygpu_kernels.sh's SP modules

def setup():
    """Put the pinned tinygrad, the oracle (the NV and AMD daemons and their helpers) and libhmsbeagle/GPU (the table
    generators) first on sys.path, and make any real device access fail: harness code must only ever reach fakes."""
    for p in (str(GPU_DIR), str(ORACLE), TINYGRAD_PATH):
        if p not in sys.path: sys.path.insert(0, p)
    WORK.mkdir(parents=True, exist_ok=True)
    block_real_devices()
    block_network()

def block_network():
    """Harness code never downloads. tinygrad's fetch and fetch_fw download whatever their cache lacks: on 2026-10-01 a probe
    that went through fw.hashes fetched three AMD blobs the boot never uses. So every download raises (fetch() imports
    urllib.request at call time)."""
    import urllib.request
    def offline(*a, **k): raise RuntimeError("tinygpu_tests: network access attempted (the offline harness never downloads)")
    urllib.request.urlopen = offline

def block_real_devices():
    """tinygrad opens the real eGPU through APLRemotePCIDevice (which also starts TinyGPU.app) whenever something
    instantiates a device, e.g. its atexit hook finalizing Device._opened_devices. On 2026-09-24 a test left "NV"
    in that set and the hook booted the real RTX 4060 at exit (STATUS.md R16). Every constructor that could reach
    the real hardware now raises. Fakes that subclass APLRemotePCIDevice with their own __init__ (nv_dispatch_daemon's
    inherited-fd device, which the tests give a socketpair) are unaffected."""
    from tinygrad.runtime.support import system
    def refuse(*a, **k): raise RuntimeError("tinygpu_tests: real device access is blocked in the offline harness")
    system.APLRemotePCIDevice.__init__ = refuse
    system.APLRemotePCIDevice.ensure_app = classmethod(refuse)
    system.RemotePCIDevice.__init__ = refuse
    system.PCIDevice.__init__ = refuse
    import atexit
    from tinygrad import device
    atexit.register(lambda: device.Device._opened_devices.clear())   # runs before tinygrad's own hook (LIFO)

def cxx():
    return os.environ.get("CXX", "clang++")

def build_cpp(src, out, *extra):
    """Compile a harness C++ program against the in-tree headers."""
    subprocess.run([cxx(), "-std=c++17", "-O1", "-Wall", "-Wextra", f"-I{REPO}", *extra, "-o", str(out), str(src)], check=True)

def ptx(variant):
    """BEAGLE's PTX module for a kernel variant, exactly as the plugin embeds it (KERNELS_STRING_<variant>)."""
    WORK.mkdir(parents=True, exist_ok=True)
    out = WORK / f"beagle_{variant}.ptx"
    if not out.exists() or out.stat().st_mtime < KERNELS_H.stat().st_mtime:
        exe = WORK / f"ptx_extract_{variant}"
        build_cpp(HERE / "ptx_extract.cpp", exe, f"-DVARIANT=KERNELS_STRING_{variant}", "-w")
        out.write_bytes(subprocess.run([str(exe)], check=True, capture_output=True).stdout)
    return out.read_bytes()

def cubin_path(ptx_bytes, arch):
    """Cache key: the PTX's sha256 prefix, so a regenerated kernels header never reuses a stale cubin."""
    return DATA / "cubins" / f"{hashlib.sha256(ptx_bytes).hexdigest()[:16]}_{arch}.cubin"

def cubin(variant, arch):
    """The ptxas cubin for a variant, compiled once with nv_compile_helper.compile_ptx (the daemon's own compile)."""
    p = cubin_path(ptx(variant), arch)
    if not p.exists():
        setup()
        import nv_compile_helper as nch
        print(f"compiling {variant} for {arch} with ptxas (not cached at {p}) ...", flush=True)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(nch.compile_ptx(str(WORK / f"beagle_{variant}.ptx"), arch, kernel_name="_all"))
    return p.read_bytes()
