#!/usr/bin/env python3
"""
Generate TinyGPUAMDTables.h (TODO.md plan step A1a): every constant the C++ AMD runtime's PM4 and SDMA encoders, its
HSACO loader and its IH drain use, taken from tinygrad itself (the pinned hcq1 tree's autogen) rather than transcribed:
  - PM4 (am/pm4_nv.py) and SDMA (am/sdma_6_0_0.py) opcodes and field macros, and soc21's events (am/soc_11.py), as
    ops_amd.py's AMDComputeQueue and AMDCopyQueue use them on gfx11;
  - the gc 11.0.0 and nbio 4.3.0 registers those encoders name, at navi_offsets' constant bases, as AMDDevice builds
    self.gc and self.nbio (ops_amd.py:1026-1030): PM4 register offsets, not the discovered MMIO bases, which the
    daemon's handoff carries (AMDev._build_regs);
  - osssys 6.0.0's IH ring fields (AM_IH.drain), hsa's kernel code property bits and COMPUTE_TMPRING_SIZE_GFX11
    bitfields, and the llvm_amdhsa_kernel_descriptor_t layout (AMDProgram.__init__).
A field macro is emitted as (mask, shift) only after checking that it is exactly (x & mask) << shift. Rerun after
changing the tinygrad pin:

    python3 make_tinygpu_amd_tables.py > TinyGPUAMDTables.h
"""
import ctypes, importlib, os, pathlib, random, sys

sys.path.insert(0, os.environ.get("TINYGRAD_PATH", str(pathlib.Path.home() / "Dropbox/Projects/tinygrad-hcq1")))
from tinygrad.runtime.autogen import hsa, amdgpu_kd  # noqa: E402
from tinygrad.runtime.support.amd import AMDIP, import_module, import_soc  # noqa: E402
import tinygrad.runtime.ops_amd as ops_amd  # noqa: E402

GFX = (11, 0, 0)
pm4 = importlib.import_module("tinygrad.runtime.autogen.am.pm4_nv")
off = importlib.import_module("tinygrad.runtime.autogen.am.navi_offsets")
soc = import_soc(GFX)
sdma = import_module("sdma", (6, 0, 0))   # AMDDevice: min(SDMA0 6.0.0, (6, 0, 0))
gc = AMDIP("gc", GFX, bases={i: tuple(getattr(off, f"GC_BASE__INST{i}_SEG{s}", 0) for s in range(6)) for i in range(6)})
nbio = AMDIP("nbio", (4, 3, 0), bases={i: tuple(getattr(off, f"NBIO_BASE__INST{i}_SEG{s}", 0) for s in range(9)) for i in range(6)})
osssys = AMDIP("osssys", (6, 0, 0), bases={0: (0,) * 6})   # its fields only

rng = random.Random(1)
out = []
def emit(line=""): out.append(line)

def field(mod, name):
    """A macro tinygrad's autogen writes as a lambda; returns (mask, shift) once it is exactly (x & mask) << shift."""
    f = getattr(mod, name)
    one = f(1)
    assert one > 0 and one & (one - 1) == 0, f"{name}: f(1) = {one:#x} is not a single bit"
    shift = one.bit_length() - 1
    mask = f((1 << 64) - 1) >> shift
    unmasked = mask == (1 << 64) - 1
    for x in [0, 1, 2, 3, 0xff, 0xffff, 0x7fffffff, 0xffffffff] + [rng.getrandbits(32) for _ in range(64)]:
        assert f(x) == (x if unmasked else x & mask) << shift, f"{name} is not (x & mask) << shift at {x:#x}"
    return (0 if unmasked else mask), shift

def u(v): return f"0x{v:x}u" if v < (1 << 32) else f"0x{v:x}ull"

# PACKET3 is written below as C++; it must be the lambda's formula
for op in range(256):
    for n in (0, 1, 2, 7, 0x3fff, 0x4000, rng.getrandbits(16)):
        assert pm4.PACKET3(op, n) == (pm4.PACKET_TYPE3 << 30) | ((op & 0xFF) << 8) | ((n & 0x3FFF) << 16)
assert ops_amd.EVENT_INDEX_PARTIAL_FLUSH == 4 and ops_amd.WAIT_REG_MEM_FUNCTION_GEQ == 5 and ops_amd.WAIT_REG_MEM_FUNCTION_EQ == 3
assert nbio.version[:2] != (7, 11)   # memory_barrier's PF0 registers (ops_amd.py:136)

emit("""/*
 * TinyGPUAMDTables.h -- GENERATED by make_tinygpu_amd_tables.py from tinygrad (the pin's autogen: am/pm4_nv.py,
 * am/sdma_6_0_0.py, am/soc_11.py, am/navi_offsets.py with the gc 11.0.0, nbio 4.3.0 and osssys 6.0.0 register tables,
 * hsa.py and amdgpu_kd.py). Do not edit.
 *
 * The constants of ops_amd.py's AMDComputeQueue and AMDCopyQueue on gfx11 (TODO.md plan step A1a). Registers are at
 * navi_offsets' constant bases, as AMDDevice.gc and AMDDevice.nbio are (PM4 offsets); the discovered MMIO addresses
 * come from the daemon's handoff. A Field is a macro of the form (x & mask) << shift, mask 0 when it has none.
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H
#define LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H

#include <cstdint>

namespace tinygpu_device {
namespace amdt {

struct Field { uint64_t mask; uint32_t shift; };
constexpr uint64_t put(Field f, uint64_t x) { return (f.mask ? (x & f.mask) : x) << f.shift; }
struct Bits { uint32_t lo, hi; };   // AMDReg.fields: inclusive bit positions
constexpr uint64_t encode(Bits b, uint64_t x) { return x << b.lo; }   // AMDReg.encode does not mask
constexpr uint64_t getbits(uint64_t v, Bits b) { return (v >> b.lo) & ((1ull << (b.hi - b.lo + 1)) - 1); }
constexpr uint64_t mask(Bits b) { return ((1ull << (b.hi - b.lo + 1)) - 1) << b.lo; }
""")

emit("// ---- PM4 (pm4_nv.py) and soc21 (soc_11.py)")
emit(f"constexpr uint32_t PACKET_TYPE3 = {pm4.PACKET_TYPE3};")
emit("constexpr uint32_t PACKET3(uint32_t op, uint32_t n) { return (PACKET_TYPE3 << 30) | ((op & 0xFFu) << 8) | ((n & 0x3FFFu) << 16); }")
for n in ["PACKET3_SET_SH_REG", "PACKET3_SET_SH_REG_START", "PACKET3_SET_SH_REG_END", "PACKET3_SET_UCONFIG_REG",
          "PACKET3_SET_UCONFIG_REG_START", "PACKET3_WAIT_REG_MEM", "PACKET3_ACQUIRE_MEM", "PACKET3_RELEASE_MEM",
          "PACKET3_DISPATCH_DIRECT", "PACKET3_EVENT_WRITE", "CACHE_FLUSH_AND_INV_TS_EVENT",
          "event_index__mec_release_mem__end_of_pipe", "data_sel__mec_release_mem__send_32_bit_low",
          "int_sel__mec_release_mem__none", "PACKET3_RELEASE_MEM_GCR_GLV_INV", "PACKET3_RELEASE_MEM_GCR_GL1_INV",
          "PACKET3_RELEASE_MEM_GCR_GL2_INV", "PACKET3_RELEASE_MEM_GCR_GLM_WB", "PACKET3_RELEASE_MEM_GCR_GLM_INV",
          "PACKET3_RELEASE_MEM_GCR_GL2_WB", "PACKET3_RELEASE_MEM_GCR_SEQ"]:
    emit(f"constexpr uint32_t {n} = {u(getattr(pm4, n))};")
for n in ["WAIT_REG_MEM_MEM_SPACE", "WAIT_REG_MEM_OPERATION", "WAIT_REG_MEM_FUNCTION", "WAIT_REG_MEM_ENGINE",
          "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLI_INV", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLM_INV", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLM_WB",
          "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLK_INV", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLK_WB", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GLV_INV",
          "PACKET3_ACQUIRE_MEM_GCR_CNTL_GL1_INV", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GL2_INV", "PACKET3_ACQUIRE_MEM_GCR_CNTL_GL2_WB",
          "PACKET3_RELEASE_MEM_EVENT_TYPE", "PACKET3_RELEASE_MEM_EVENT_INDEX", "PACKET3_RELEASE_MEM_DATA_SEL",
          "PACKET3_RELEASE_MEM_INT_SEL", "PACKET3_RELEASE_MEM_DST_SEL", "EVENT_TYPE", "EVENT_INDEX"]:
    m, s = field(pm4, n)
    emit(f"constexpr Field {n} = {{{u(m)}, {s}}};")
emit(f"constexpr uint32_t CS_PARTIAL_FLUSH = {u(soc.CS_PARTIAL_FLUSH)};   // {soc.__name__.split('.')[-1]}")
emit(f"constexpr uint32_t EVENT_INDEX_PARTIAL_FLUSH = {ops_amd.EVENT_INDEX_PARTIAL_FLUSH};   // ops_amd.py")
emit(f"constexpr uint32_t WAIT_REG_MEM_FUNCTION_EQ = {ops_amd.WAIT_REG_MEM_FUNCTION_EQ}, WAIT_REG_MEM_FUNCTION_GEQ = {ops_amd.WAIT_REG_MEM_FUNCTION_GEQ};")
emit()

emit(f"// ---- SDMA ({sdma.__name__.split('.')[-1]}.py)")
for n in ["SDMA_OP_COPY", "SDMA_SUBOP_COPY_LINEAR", "SDMA_OP_FENCE", "SDMA_OP_POLL_REGMEM"]:
    emit(f"constexpr uint32_t {n} = {u(getattr(sdma, n))};")
for n in ["SDMA_PKT_COPY_LINEAR_HEADER_SUB_OP", "SDMA_PKT_COPY_LINEAR_COUNT_COUNT", "SDMA_PKT_FENCE_HEADER_MTYPE",
          "SDMA_PKT_POLL_REGMEM_HEADER_FUNC", "SDMA_PKT_POLL_REGMEM_HEADER_MEM_POLL", "SDMA_PKT_POLL_REGMEM_DW5_INTERVAL",
          "SDMA_PKT_POLL_REGMEM_DW5_RETRY_COUNT"]:
    m, s = field(sdma, n)
    emit(f"constexpr Field {n} = {{{u(m)}, {s}}};")
emit()

emit("// ---- gc 11.0.0 at navi_offsets' GC bases (AMDDevice.gc): PM4 register offsets, and the fields encode() names")
for r in ["regCOMPUTE_PGM_LO", "regCOMPUTE_PGM_RSRC1", "regCOMPUTE_PGM_RSRC3", "regCOMPUTE_TMPRING_SIZE",
          "regCOMPUTE_DISPATCH_SCRATCH_BASE_LO", "regCOMPUTE_RESTART_X", "regCOMPUTE_USER_DATA_0", "regCOMPUTE_RESOURCE_LIMITS",
          "regCOMPUTE_START_X", "regCOMPUTE_DISPATCH_INITIATOR"]:
    emit(f"constexpr uint32_t {r} = {u(getattr(gc, r).addr[0])};")
for r, fs in [("regCOMPUTE_DISPATCH_INITIATOR", ["compute_shader_en", "force_start_at_000", "cs_w32_en"]),
              ("regCOMPUTE_RESOURCE_LIMITS", ["waves_per_sh"]),
              ("regGCVM_L2_PROTECTION_FAULT_CNTL", ["clear_protection_fault_status_addr"])]:   # AM_IH.interrupt_handler's UTCL2 clear
    for f in fs:
        lo, hi = getattr(gc, r).fields[f]
        emit(f"constexpr Bits {r[3:]}__{f} = {{{lo}, {hi}}};")
emit("// nbio 4.3.0 at navi_offsets' NBIO bases (AMDDevice.nbio): memory_barrier's HDP flush request and done")
for r in ["regBIF_BX_PF0_GPU_HDP_FLUSH_REQ", "regBIF_BX_PF0_GPU_HDP_FLUSH_DONE"]:
    emit(f"constexpr uint32_t {r} = {u(getattr(nbio, r).addr[0])};")
emit("// osssys 6.0.0: the IH ring fields AM_IH.drain reads and updates (the registers' MMIO addresses are the handoff's)")
for r, fs in [("regIH_RB_WPTR", ["offset", "rb_overflow"]), ("regIH_RB_CNTL", ["wptr_overflow_clear"])]:
    for f in fs:
        lo, hi = getattr(osssys, r).fields[f]
        emit(f"constexpr Bits {r[3:]}__{f} = {{{lo}, {hi}}};")
emit()

emit("// ---- am.py: the IH ring entry (SOC15_*_FROM_IH_ENTRY), soc21's clients and gfx11's sources (AM_SOC.ih_srcs_names, AM_IH)")
from tinygrad.runtime.autogen.am import am  # noqa: E402
IH = [("CLIENT_ID", 0, 0, 0xff), ("SOURCE_ID", 0, 8, 0xff), ("RING_ID", 0, 16, 0xff), ("VMID", 0, 24, 0xf), ("VMID_TYPE", 0, 31, 0x1),
      ("PASID", 3, 0, 0xffff), ("NODEID", 3, 16, 0xff), ("CONTEXT_ID0", 4, 0, 0xffffffff), ("CONTEXT_ID1", 5, 0, 0xffffffff),
      ("CONTEXT_ID2", 6, 0, 0xffffffff), ("CONTEXT_ID3", 7, 0, 0xffffffff)]
for _ in range(256):   # each is exactly (entry[dw] >> shift) & mask
    e = [rng.getrandbits(32) for _ in range(8)]
    for name, dw, sh, m in IH: assert getattr(am, f"SOC15_{name}_FROM_IH_ENTRY")(e) == (e[dw] >> sh) & m, name
emit("struct IHField { uint32_t dword, shift, mask; };")
for name, dw, sh, m in IH: emit(f"constexpr IHField IH_{name} = {{{dw}, {sh}, {u(m)}}};")
emit("constexpr uint32_t ih_get(const uint32_t e[8], IHField f) { return (e[f.dword] >> f.shift) & f.mask; }")
emit(f"constexpr uint32_t SOC21_IH_CLIENTID_GRBM_CP = {am.SOC21_IH_CLIENTID_GRBM_CP}, SOC21_IH_CLIENTID_GFX = {am.SOC21_IH_CLIENTID_GFX};   // gfx_ih_clients")
emit("struct IHName { uint32_t id; const char* name; };")
gfx_srcs = sorted({getattr(am, k): k[k.find('__SRCID__') + 9:] for k in dir(am) if k.startswith(f'GFX_{GFX[0]}') and '__SRCID__' in k}.items())
emit(f"constexpr IHName IH_GFX{GFX[0]}_SRCS[] = {{" + ", ".join(f'{{{i}, "{n}"}}' for i, n in gfx_srcs) + "};")
emit("constexpr IHName IH_SOC21_CLIENTS[] = {" + ", ".join(f'{{{i}, "{n}"}}' for i, n in sorted(am.enum_soc21_ih_clientid.items())) + "};")
emit()

emit("// ---- hsa.py: kernel code properties and COMPUTE_TMPRING_SIZE_GFX11")
for n in sorted(n for n in dir(hsa) if n.startswith("AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR") and not n.endswith(("_SHIFT", "_WIDTH"))):
    emit(f"constexpr uint32_t {n} = {u(getattr(hsa, n))};")
emit("constexpr uint32_t KERNEL_CODE_PROPERTIES_WAVE32 = 0x400u;   // AMDProgram.__init__ tests this bit")
for name, _typ, byte, width, bit in hsa.union_COMPUTE_TMPRING_SIZE_GFX11_bitfields._real_fields_:
    emit(f"constexpr Bits TMPRING_GFX11_{name} = {{{byte * 8 + bit}, {byte * 8 + bit + width - 1}}};")
emit()

emit("// ---- amdgpu_kd.py: llvm_amdhsa_kernel_descriptor_t (byte offsets)")
kd = amdgpu_kd.llvm_amdhsa_kernel_descriptor_t
emit(f"constexpr uint32_t KD_SIZE = {kd.SIZE};")
for name, typ, byte, *rest in kd._real_fields_:
    if name.startswith("reserved"): continue
    emit(f"constexpr uint32_t KD_{name.upper()} = {byte};   // {ctypes.sizeof(typ)} bytes")
emit("""
}  // namespace amdt
}  // namespace tinygpu_device

#endif  // LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H""")
print("\n".join(out))
