#!/usr/bin/env python3
"""
Generate TinyGPUFirmwareManifest.h (TODO.md plan step C4): every NVIDIA firmware file tinygrad's NV boot fetches, for
each chip family it boots (ga102, ad102, gb202), plus the Booter Unload image nv_init_helper.py's teardown fetches (plan
step P2). The pinned hcq1 tree's own NV_FLCN.prep_booter, NV_FLCN_COT.init_fmc_image, NV_GSP.init_gsp_image and
NV_GSP.init_boot_binary_image (the calls NV_FLCN.init_sw, NV_FLCN_COT.init_sw and NV_GSP.init_wpr_meta make, ip.py:108,
300, 435-436), and nv_init_helper._booter_ucode, run with fetch_fw recording its arguments and helpers.fetch recording
the URL fetch_fw builds and stopping there, so each entry is what that call asks for: (subdir, name, sha256), the URL,
and the md5 of the URL, which names the file in tinygrad's download cache (helpers.fetch, :465-472). Nothing is read
and nothing is downloaded. Rerun after changing the tinygrad pin or nv_init_helper.py, with the harness Python
(BEAGLE_PYTHON in tinygpu_tests/env.sh):

    python make_tinygpu_fw_manifest.py [outdir]    # default: next to this script
"""
import hashlib, os, pathlib, subprocess, sys, types

HERE = pathlib.Path(__file__).resolve().parent
TINYGRAD = pathlib.Path(os.environ.get("TINYGRAD_PATH", pathlib.Path.home() / "Dropbox/Projects/tinygrad-hcq1"))
sys.path.insert(0, str(TINYGRAD))
from tinygrad import helpers  # noqa: E402
from tinygrad.runtime.support.nv import ip  # noqa: E402

# tinygrad's own functions, taken before nv_init_helper patches NV_FLCN.prep_booter (it calls the original first)
PREP = {"booter_load": ip.NV_FLCN.prep_booter, "fmc": ip.NV_FLCN_COT.init_fmc_image,
        "gsp": ip.NV_GSP.init_gsp_image, "bootloader": ip.NV_GSP.init_boot_binary_image}
sys.path.insert(0, str(HERE)); sys.path.insert(0, str(HERE / "tinygpu_tests/oracle"))   # nv_init_helper (plan step C13b)
import nv_init_helper  # noqa: E402

# what each chip family's boot fetches, in boot order (NVDev._early_ip_init picks NV_FLCN_COT for gb202, nvdev.py:115-118)
ROLES = {"ga102": ["booter_load", "gsp", "bootloader", "booter_unload"],
         "ad102": ["booter_load", "gsp", "bootloader", "booter_unload"],
         "gb202": ["fmc", "gsp", "bootloader"]}
WHERE = {"booter_load": "NV_FLCN.prep_booter, ip.py:170-174", "fmc": "NV_FLCN_COT.init_fmc_image, ip.py:302-304",
         "gsp": "NV_GSP.init_gsp_image, ip.py:401-402", "bootloader": "NV_GSP.init_boot_binary_image, ip.py:425-429",
         "booter_unload": "nv_init_helper._booter_ucode (plan step P2)"}

class _Fetched(Exception): pass

def record(chip, role):
    """The one fetch_fw call the role's function makes, as (subdir, name, sha256, url)."""
    asked, got = [], []
    real_fetch_fw = helpers.fetch_fw
    def fetch_fw(path, name, sha256):
        asked.append((path, name, sha256))
        return real_fetch_fw(path, name, sha256)
    def fetch(url, name=None, subdir=None, sha256=None, **kw):
        got.append((url, subdir, sha256))
        raise _Fetched
    saved = helpers.fetch_fw, ip.fetch_fw, helpers.fetch
    helpers.fetch_fw = ip.fetch_fw = fetch_fw   # _booter_ucode imports it from helpers at call time
    helpers.fetch = fetch                       # fetch_fw calls it through helpers' globals
    try:
        nvdev = types.SimpleNamespace(fw_name=chip)
        try:
            if role == "booter_unload":
                nv_init_helper._booter_ucode(chip, "booter_unload-570.144.bin", nv_init_helper._BOOTER_UNLOAD_SHA[chip])
            else:
                obj = object.__new__({"booter_load": ip.NV_FLCN, "fmc": ip.NV_FLCN_COT}.get(role, ip.NV_GSP))
                obj.nvdev = nvdev
                PREP[role](obj)
        except _Fetched: pass
    finally:
        helpers.fetch_fw, ip.fetch_fw, helpers.fetch = saved
    assert len(asked) == 1 and len(got) == 1, (chip, role, asked, got)
    (path, name, sha256), (url, subdir, fsha) = asked[0], got[0]
    assert subdir == "fw" and fsha == sha256 and url.endswith(f"/{path}/{name}"), (url, subdir)
    return path, name, sha256, url

def main():
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    rows = [(chip, role, *record(chip, role)) for chip in ROLES for role in ROLES[chip]]
    bases = {url[:-len(f"/{path}/{name}")] for _, _, path, name, _, url in rows}
    assert len(bases) == 1, bases
    pin = subprocess.run(["git", "-C", str(TINYGRAD), "rev-parse", "--short=9", "HEAD"], capture_output=True, text=True).stdout.strip() or "?"
    lines = [
        "/*",
        f" * TinyGPUFirmwareManifest.h -- GENERATED by make_tinygpu_fw_manifest.py from tinygrad {pin} and",
        " * libhmsbeagle/GPU/tinygpu_tests/oracle/nv_init_helper.py. Do not edit. TODO.md plan step C4.",
        " *",
        " * Every NVIDIA firmware file tinygrad's NV boot fetches (helpers.fetch_fw), per chip family, and the Booter Unload",
        " * image of BEAGLE's teardown: the arguments of each fetch_fw call, the URL it builds, and md5(URL), the file's name",
        " * in tinygrad's download cache (<cache>/tinygrad/downloads/fw/<md5>). TinyGPUFirmware.h finds and checks them.",
        " */",
        "",
        "#ifndef LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H",
        "#define LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H",
        "",
        "namespace tinygpu_device {",
        "namespace nvfw {",
        "",
        f'constexpr const char* kLinuxFirmware = "{bases.pop()}";   // helpers.fetch_fw\'s pin',
        "",
        "struct TGFirmware {",
        "    const char* chip;     // NVDev.fw_name",
        "    const char* role;     // booter_load, fmc, gsp, bootloader or booter_unload",
        "    const char* subdir;   // fetch_fw's path",
        "    const char* name;",
        "    const char* sha256;",
        "    const char* url_md5;  // its name in tinygrad's download cache",
        "};",
        "",
        "constexpr TGFirmware kFirmware[] = {",
    ]
    for chip, role, path, name, sha256, url in rows:
        lines.append(f'    {{"{chip}", "{role}", "{path}", "{name}", "{sha256}", "{hashlib.md5(url.encode()).hexdigest()}"}},  // {WHERE[role]}')
    lines += ["};", "", "} // namespace nvfw", "} // namespace tinygpu_device", "", "#endif // LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H", ""]
    (out / "TinyGPUFirmwareManifest.h").write_text("\n".join(lines))
    print(f"wrote {out / 'TinyGPUFirmwareManifest.h'}: {len(rows)} entries for {', '.join(ROLES)}")

if __name__ == "__main__":
    main()
