/*
 * TinyGPUNVRMTables.h -- GENERATED by make_tinygpu_nv_boot_tables.py from tinygrad a9830e2b4
 * (tinygrad/runtime/autogen/nv.py and tinygrad/runtime/autogen/nv_570.py, as tinygrad/runtime/support/nv/ip.py,
 * libhmsbeagle/GPU/nv_init_helper.py and ops_nv.py's PCIIface path use them). Do not edit. TODO.md plan step C2.
 *
 * nv: the RPC ids and results, and 21 RPC payload structs (139 fields). nv_gpu (tinygrad's nv_570): the RM classes,
 * controls and flags, and 32 RM structs (158 fields). Packed at tinygrad's offsets as in TinyGPUNVBootTables.h, which
 * has the registers and the boot's structs.
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUNVRMTABLES_H
#define LIBHMSBEAGLE_GPU_TINYGPUNVRMTABLES_H

#include <cstddef>
#include <cstdint>

#include "libhmsbeagle/GPU/TinyGPUNVBootTables.h"

namespace tinygpu_device {
namespace nv {

constexpr uint32_t NV_VGPU_MSG_EVENT_GSP_INIT_DONE = 0x1001;
constexpr uint32_t NV_VGPU_MSG_EVENT_GSP_RUN_CPU_SEQUENCER = 0x1002;
constexpr uint32_t NV_VGPU_MSG_EVENT_MMU_FAULT_QUEUED = 0x1005;
constexpr uint32_t NV_VGPU_MSG_EVENT_OS_ERROR_LOG = 0x1006;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_ALLOC_MEMORY = 0x4;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_CONTINUATION_RECORD = 0x47;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_GSP_RM_ALLOC = 0x67;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_GSP_RM_CONTROL = 0x4c;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_GSP_SET_SYSTEM_INFO = 0x48;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_SET_PAGE_DIRECTORY = 0x36;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_SET_REGISTRY = 0x49;
constexpr uint32_t NV_VGPU_MSG_FUNCTION_UNLOADING_GUEST_DRIVER = 0x2f;
constexpr uint32_t NV_VGPU_MSG_RESULT_RPC_PENDING = 0xffffffff;
constexpr uint32_t NV_VGPU_MSG_SIGNATURE_VALID = 0x43505256;
constexpr uint32_t NV_VGPU_PTEDESC_IDR_NONE = 0x0;
constexpr uint32_t REGISTRY_TABLE_ENTRY_TYPE_DWORD = 0x1;

#pragma pack(push, 1)

struct BUSINFO {  // nv.py:4278
    uint16_t deviceID;
    uint16_t vendorID;
    uint16_t subdeviceID;
    uint16_t subvendorID;
    uint8_t revisionID;
    uint8_t _pad0[1];
};
static_assert(sizeof(BUSINFO) == 10);
static_assert(offsetof(BUSINFO, deviceID) == 0);
static_assert(offsetof(BUSINFO, vendorID) == 2);
static_assert(offsetof(BUSINFO, subdeviceID) == 4);
static_assert(offsetof(BUSINFO, subvendorID) == 6);
static_assert(offsetof(BUSINFO, revisionID) == 8);

struct struct_DOD_METHOD_DATA {  // nv.py:4225
    uint32_t status;
    uint32_t acpiIdListLen;
    uint32_t acpiIdList[16];
};
static_assert(sizeof(struct_DOD_METHOD_DATA) == 72);
static_assert(offsetof(struct_DOD_METHOD_DATA, status) == 0);
static_assert(offsetof(struct_DOD_METHOD_DATA, acpiIdListLen) == 4);
static_assert(offsetof(struct_DOD_METHOD_DATA, acpiIdList) == 8);
using DOD_METHOD_DATA = struct_DOD_METHOD_DATA;

struct struct_JT_METHOD_DATA {  // nv.py:4234
    uint32_t status;
    uint32_t jtCaps;
    uint16_t jtRevId;
    uint8_t bSBIOSCaps;
    uint8_t _pad0[1];
};
static_assert(sizeof(struct_JT_METHOD_DATA) == 12);
static_assert(offsetof(struct_JT_METHOD_DATA, status) == 0);
static_assert(offsetof(struct_JT_METHOD_DATA, jtCaps) == 4);
static_assert(offsetof(struct_JT_METHOD_DATA, jtRevId) == 8);
static_assert(offsetof(struct_JT_METHOD_DATA, bSBIOSCaps) == 10);
using JT_METHOD_DATA = struct_JT_METHOD_DATA;

struct struct_MUX_METHOD_DATA_ELEMENT {  // nv.py:4243
    uint32_t acpiId;
    uint32_t mode;
    uint32_t status;
};
static_assert(sizeof(struct_MUX_METHOD_DATA_ELEMENT) == 12);
static_assert(offsetof(struct_MUX_METHOD_DATA_ELEMENT, acpiId) == 0);
static_assert(offsetof(struct_MUX_METHOD_DATA_ELEMENT, mode) == 4);
static_assert(offsetof(struct_MUX_METHOD_DATA_ELEMENT, status) == 8);
using MUX_METHOD_DATA_ELEMENT = struct_MUX_METHOD_DATA_ELEMENT;

struct struct_MUX_METHOD_DATA {  // nv.py:4251
    uint32_t tableLen;
    struct_MUX_METHOD_DATA_ELEMENT acpiIdMuxModeTable[16];
    struct_MUX_METHOD_DATA_ELEMENT acpiIdMuxPartTable[16];
    struct_MUX_METHOD_DATA_ELEMENT acpiIdMuxStateTable[16];
};
static_assert(sizeof(struct_MUX_METHOD_DATA) == 580);
static_assert(offsetof(struct_MUX_METHOD_DATA, tableLen) == 0);
static_assert(offsetof(struct_MUX_METHOD_DATA, acpiIdMuxModeTable) == 4);
static_assert(offsetof(struct_MUX_METHOD_DATA, acpiIdMuxPartTable) == 196);
static_assert(offsetof(struct_MUX_METHOD_DATA, acpiIdMuxStateTable) == 388);
using MUX_METHOD_DATA = struct_MUX_METHOD_DATA;

struct struct_CAPS_METHOD_DATA {  // nv.py:4260
    uint32_t status;
    uint32_t optimusCaps;
};
static_assert(sizeof(struct_CAPS_METHOD_DATA) == 8);
static_assert(offsetof(struct_CAPS_METHOD_DATA, status) == 0);
static_assert(offsetof(struct_CAPS_METHOD_DATA, optimusCaps) == 4);
using CAPS_METHOD_DATA = struct_CAPS_METHOD_DATA;

struct struct_ACPI_METHOD_DATA {  // nv.py:4267
    uint8_t bValid;
    uint8_t _pad0[3];
    struct_DOD_METHOD_DATA dodMethodData;
    struct_JT_METHOD_DATA jtMethodData;
    struct_MUX_METHOD_DATA muxMethodData;
    struct_CAPS_METHOD_DATA capsMethodData;
};
static_assert(sizeof(struct_ACPI_METHOD_DATA) == 676);
static_assert(offsetof(struct_ACPI_METHOD_DATA, bValid) == 0);
static_assert(offsetof(struct_ACPI_METHOD_DATA, dodMethodData) == 4);
static_assert(offsetof(struct_ACPI_METHOD_DATA, jtMethodData) == 76);
static_assert(offsetof(struct_ACPI_METHOD_DATA, muxMethodData) == 88);
static_assert(offsetof(struct_ACPI_METHOD_DATA, capsMethodData) == 668);
using ACPI_METHOD_DATA = struct_ACPI_METHOD_DATA;

struct struct_GSP_VF_INFO {  // nv.py:4287
    uint32_t totalVFs;
    uint32_t firstVFOffset;
    uint64_t FirstVFBar0Address;
    uint64_t FirstVFBar1Address;
    uint64_t FirstVFBar2Address;
    uint8_t b64bitBar0;
    uint8_t b64bitBar1;
    uint8_t b64bitBar2;
    uint8_t _pad0[5];
};
static_assert(sizeof(struct_GSP_VF_INFO) == 40);
static_assert(offsetof(struct_GSP_VF_INFO, totalVFs) == 0);
static_assert(offsetof(struct_GSP_VF_INFO, firstVFOffset) == 4);
static_assert(offsetof(struct_GSP_VF_INFO, FirstVFBar0Address) == 8);
static_assert(offsetof(struct_GSP_VF_INFO, FirstVFBar1Address) == 16);
static_assert(offsetof(struct_GSP_VF_INFO, FirstVFBar2Address) == 24);
static_assert(offsetof(struct_GSP_VF_INFO, b64bitBar0) == 32);
static_assert(offsetof(struct_GSP_VF_INFO, b64bitBar1) == 33);
static_assert(offsetof(struct_GSP_VF_INFO, b64bitBar2) == 34);
using GSP_VF_INFO = struct_GSP_VF_INFO;

struct GSP_PCIE_CONFIG_REG {  // nv.py:4300
    uint32_t linkCap;
};
static_assert(sizeof(GSP_PCIE_CONFIG_REG) == 4);
static_assert(offsetof(GSP_PCIE_CONFIG_REG, linkCap) == 0);

struct struct_GspSystemInfo {  // nv.py:4443
    uint64_t gpuPhysAddr;
    uint64_t gpuPhysFbAddr;
    uint64_t gpuPhysInstAddr;
    uint64_t gpuPhysIoAddr;
    uint64_t nvDomainBusDeviceFunc;
    uint64_t simAccessBufPhysAddr;
    uint64_t notifyOpSharedSurfacePhysAddr;
    uint64_t pcieAtomicsOpMask;
    uint64_t consoleMemSize;
    uint64_t maxUserVa;
    uint32_t pciConfigMirrorBase;
    uint32_t pciConfigMirrorSize;
    uint32_t PCIDeviceID;
    uint32_t PCISubDeviceID;
    uint32_t PCIRevisionID;
    uint32_t pcieAtomicsCplDeviceCapMask;
    uint8_t oorArch;
    uint8_t _pad0[7];
    uint64_t clPdbProperties;
    uint32_t Chipset;
    uint8_t bGpuBehindBridge;
    uint8_t bFlrSupported;
    uint8_t b64bBar0Supported;
    uint8_t bMnocAvailable;
    uint32_t chipsetL1ssEnable;
    uint8_t bUpstreamL0sUnsupported;
    uint8_t bUpstreamL1Unsupported;
    uint8_t bUpstreamL1PorSupported;
    uint8_t bUpstreamL1PorMobileOnly;
    uint8_t bSystemHasMux;
    uint8_t upstreamAddressValid;
    BUSINFO FHBBusInfo;
    BUSINFO chipsetIDInfo;
    uint8_t _pad1[2];
    struct_ACPI_METHOD_DATA acpiMethodData;
    uint32_t hypervisorType;
    uint8_t bIsPassthru;
    uint8_t _pad2[7];
    uint64_t sysTimerOffsetNs;
    struct_GSP_VF_INFO gspVFInfo;
    uint8_t bIsPrimary;
    uint8_t isGridBuild;
    uint8_t _pad3[2];
    GSP_PCIE_CONFIG_REG pcieConfigReg;
    uint32_t gridBuildCsp;
    uint8_t bPreserveVideoMemoryAllocations;
    uint8_t bTdrEventSupported;
    uint8_t bFeatureStretchVblankCapable;
    uint8_t bEnableDynamicGranularityPageArrays;
    uint8_t bClockBoostSupported;
    uint8_t bRouteDispIntrsToCPU;
    uint8_t _pad4[6];
    uint64_t hostPageSize;
};
static_assert(sizeof(struct_GspSystemInfo) == 928);
static_assert(offsetof(struct_GspSystemInfo, gpuPhysAddr) == 0);
static_assert(offsetof(struct_GspSystemInfo, gpuPhysFbAddr) == 8);
static_assert(offsetof(struct_GspSystemInfo, gpuPhysInstAddr) == 16);
static_assert(offsetof(struct_GspSystemInfo, gpuPhysIoAddr) == 24);
static_assert(offsetof(struct_GspSystemInfo, nvDomainBusDeviceFunc) == 32);
static_assert(offsetof(struct_GspSystemInfo, simAccessBufPhysAddr) == 40);
static_assert(offsetof(struct_GspSystemInfo, notifyOpSharedSurfacePhysAddr) == 48);
static_assert(offsetof(struct_GspSystemInfo, pcieAtomicsOpMask) == 56);
static_assert(offsetof(struct_GspSystemInfo, consoleMemSize) == 64);
static_assert(offsetof(struct_GspSystemInfo, maxUserVa) == 72);
static_assert(offsetof(struct_GspSystemInfo, pciConfigMirrorBase) == 80);
static_assert(offsetof(struct_GspSystemInfo, pciConfigMirrorSize) == 84);
static_assert(offsetof(struct_GspSystemInfo, PCIDeviceID) == 88);
static_assert(offsetof(struct_GspSystemInfo, PCISubDeviceID) == 92);
static_assert(offsetof(struct_GspSystemInfo, PCIRevisionID) == 96);
static_assert(offsetof(struct_GspSystemInfo, pcieAtomicsCplDeviceCapMask) == 100);
static_assert(offsetof(struct_GspSystemInfo, oorArch) == 104);
static_assert(offsetof(struct_GspSystemInfo, clPdbProperties) == 112);
static_assert(offsetof(struct_GspSystemInfo, Chipset) == 120);
static_assert(offsetof(struct_GspSystemInfo, bGpuBehindBridge) == 124);
static_assert(offsetof(struct_GspSystemInfo, bFlrSupported) == 125);
static_assert(offsetof(struct_GspSystemInfo, b64bBar0Supported) == 126);
static_assert(offsetof(struct_GspSystemInfo, bMnocAvailable) == 127);
static_assert(offsetof(struct_GspSystemInfo, chipsetL1ssEnable) == 128);
static_assert(offsetof(struct_GspSystemInfo, bUpstreamL0sUnsupported) == 132);
static_assert(offsetof(struct_GspSystemInfo, bUpstreamL1Unsupported) == 133);
static_assert(offsetof(struct_GspSystemInfo, bUpstreamL1PorSupported) == 134);
static_assert(offsetof(struct_GspSystemInfo, bUpstreamL1PorMobileOnly) == 135);
static_assert(offsetof(struct_GspSystemInfo, bSystemHasMux) == 136);
static_assert(offsetof(struct_GspSystemInfo, upstreamAddressValid) == 137);
static_assert(offsetof(struct_GspSystemInfo, FHBBusInfo) == 138);
static_assert(offsetof(struct_GspSystemInfo, chipsetIDInfo) == 148);
static_assert(offsetof(struct_GspSystemInfo, acpiMethodData) == 160);
static_assert(offsetof(struct_GspSystemInfo, hypervisorType) == 836);
static_assert(offsetof(struct_GspSystemInfo, bIsPassthru) == 840);
static_assert(offsetof(struct_GspSystemInfo, sysTimerOffsetNs) == 848);
static_assert(offsetof(struct_GspSystemInfo, gspVFInfo) == 856);
static_assert(offsetof(struct_GspSystemInfo, bIsPrimary) == 896);
static_assert(offsetof(struct_GspSystemInfo, isGridBuild) == 897);
static_assert(offsetof(struct_GspSystemInfo, pcieConfigReg) == 900);
static_assert(offsetof(struct_GspSystemInfo, gridBuildCsp) == 904);
static_assert(offsetof(struct_GspSystemInfo, bPreserveVideoMemoryAllocations) == 908);
static_assert(offsetof(struct_GspSystemInfo, bTdrEventSupported) == 909);
static_assert(offsetof(struct_GspSystemInfo, bFeatureStretchVblankCapable) == 910);
static_assert(offsetof(struct_GspSystemInfo, bEnableDynamicGranularityPageArrays) == 911);
static_assert(offsetof(struct_GspSystemInfo, bClockBoostSupported) == 912);
static_assert(offsetof(struct_GspSystemInfo, bRouteDispIntrsToCPU) == 913);
static_assert(offsetof(struct_GspSystemInfo, hostPageSize) == 920);
using GspSystemInfo = struct_GspSystemInfo;

struct struct_PACKED_REGISTRY_ENTRY {  // nv.py:4182
    uint32_t nameOffset;
    uint8_t type;
    uint8_t _pad0[3];
    uint32_t data;
    uint32_t length;
};
static_assert(sizeof(struct_PACKED_REGISTRY_ENTRY) == 16);
static_assert(offsetof(struct_PACKED_REGISTRY_ENTRY, nameOffset) == 0);
static_assert(offsetof(struct_PACKED_REGISTRY_ENTRY, type) == 4);
static_assert(offsetof(struct_PACKED_REGISTRY_ENTRY, data) == 8);
static_assert(offsetof(struct_PACKED_REGISTRY_ENTRY, length) == 12);
using PACKED_REGISTRY_ENTRY = struct_PACKED_REGISTRY_ENTRY;

struct struct_PACKED_REGISTRY_TABLE {  // nv.py:4191
    uint32_t size;
    uint32_t numEntries;
};
static_assert(sizeof(struct_PACKED_REGISTRY_TABLE) == 8);
static_assert(offsetof(struct_PACKED_REGISTRY_TABLE, size) == 0);
static_assert(offsetof(struct_PACKED_REGISTRY_TABLE, numEntries) == 4);
using PACKED_REGISTRY_TABLE = struct_PACKED_REGISTRY_TABLE;

struct struct_pte_desc_pte_pde {  // nv.py:369
    union {
        uint64_t pte;
        uint64_t pde;
    };
};
static_assert(sizeof(struct_pte_desc_pte_pde) == 8);
static_assert(offsetof(struct_pte_desc_pte_pde, pte) == 0);
static_assert(offsetof(struct_pte_desc_pte_pde, pde) == 0);

struct struct_pte_desc {  // nv.py:362
    uint8_t _bf_0[2];  // idr: 2 bits at bit 0 of byte 0, reserved1: 14 bits at bit 2 of byte 0
    uint8_t _bf_2[2];  // length: 16 bits at bit 0 of byte 2
    uint8_t _pad0[4];
    struct_pte_desc_pte_pde pte_pde[0];
    uint32_t idr() const { return (uint32_t)nv_bitfield_get(_bf_0 + 0, 1, 0, 2); }
    void set_idr(uint32_t v) { nv_bitfield_set(_bf_0 + 0, 1, 0, 2, v); }
    uint32_t reserved1() const { return (uint32_t)nv_bitfield_get(_bf_0 + 0, 2, 2, 14); }
    void set_reserved1(uint32_t v) { nv_bitfield_set(_bf_0 + 0, 2, 2, 14, v); }
    uint32_t length() const { return (uint32_t)nv_bitfield_get(_bf_2 + 0, 2, 0, 16); }
    void set_length(uint32_t v) { nv_bitfield_set(_bf_2 + 0, 2, 0, 16, v); }
};
static_assert(sizeof(struct_pte_desc) == 8);
static_assert(offsetof(struct_pte_desc, _bf_0) + 0 == 0);  // idr
static_assert(offsetof(struct_pte_desc, _bf_0) + 0 == 0);  // reserved1
static_assert(offsetof(struct_pte_desc, _bf_2) + 0 == 2);  // length
static_assert(offsetof(struct_pte_desc, pte_pde) == 8);

struct struct_rpc_alloc_memory_v13_01 {  // nv.py:349
    uint32_t hClient;
    uint32_t hDevice;
    uint32_t hMemory;
    uint32_t hClass;
    uint32_t flags;
    uint32_t pteAdjust;
    uint32_t format;
    uint8_t _pad0[4];
    uint64_t length;
    uint32_t pageCount;
    uint8_t _pad1[4];
    struct_pte_desc pteDesc;
};
static_assert(sizeof(struct_rpc_alloc_memory_v13_01) == 56);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, hClient) == 0);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, hDevice) == 4);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, hMemory) == 8);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, hClass) == 12);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, flags) == 16);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, pteAdjust) == 20);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, format) == 24);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, length) == 32);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, pageCount) == 40);
static_assert(offsetof(struct_rpc_alloc_memory_v13_01, pteDesc) == 48);
using rpc_alloc_memory_v13_01 = struct_rpc_alloc_memory_v13_01;
using rpc_alloc_memory_v = struct_rpc_alloc_memory_v13_01;

struct struct_rpc_gsp_rm_alloc_v03_00 {  // nv.py:3569
    uint32_t hClient;
    uint32_t hParent;
    uint32_t hObject;
    uint32_t hClass;
    uint32_t status;
    uint32_t paramsSize;
    uint32_t flags;
    uint8_t reserved[4];
    uint8_t params[0];
};
static_assert(sizeof(struct_rpc_gsp_rm_alloc_v03_00) == 32);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, hClient) == 0);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, hParent) == 4);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, hObject) == 8);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, hClass) == 12);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, status) == 16);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, paramsSize) == 20);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, flags) == 24);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, reserved) == 28);
static_assert(offsetof(struct_rpc_gsp_rm_alloc_v03_00, params) == 32);
using rpc_gsp_rm_alloc_v03_00 = struct_rpc_gsp_rm_alloc_v03_00;
using rpc_gsp_rm_alloc_v = struct_rpc_gsp_rm_alloc_v03_00;

struct struct_rpc_gsp_rm_control_v03_00 {  // nv.py:3584
    uint32_t hClient;
    uint32_t hObject;
    uint32_t cmd;
    uint32_t status;
    uint32_t paramsSize;
    uint32_t flags;
    uint8_t params[0];
};
static_assert(sizeof(struct_rpc_gsp_rm_control_v03_00) == 24);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, hClient) == 0);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, hObject) == 4);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, cmd) == 8);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, status) == 12);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, paramsSize) == 16);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, flags) == 20);
static_assert(offsetof(struct_rpc_gsp_rm_control_v03_00, params) == 24);
using rpc_gsp_rm_control_v03_00 = struct_rpc_gsp_rm_control_v03_00;
using rpc_gsp_rm_control_v = struct_rpc_gsp_rm_control_v03_00;

struct struct_rpc_run_cpu_sequencer_v17_00 {  // nv.py:3610
    uint32_t bufferSizeDWord;
    uint32_t cmdIndex;
    uint32_t regSaveArea[8];
    uint32_t commandBuffer[0];
};
static_assert(sizeof(struct_rpc_run_cpu_sequencer_v17_00) == 40);
static_assert(offsetof(struct_rpc_run_cpu_sequencer_v17_00, bufferSizeDWord) == 0);
static_assert(offsetof(struct_rpc_run_cpu_sequencer_v17_00, cmdIndex) == 4);
static_assert(offsetof(struct_rpc_run_cpu_sequencer_v17_00, regSaveArea) == 8);
static_assert(offsetof(struct_rpc_run_cpu_sequencer_v17_00, commandBuffer) == 40);
using rpc_run_cpu_sequencer_v17_00 = struct_rpc_run_cpu_sequencer_v17_00;
using rpc_run_cpu_sequencer_v = struct_rpc_run_cpu_sequencer_v17_00;

struct struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05 {  // nv.py:1331
    uint64_t physAddress;
    uint32_t numEntries;
    uint32_t flags;
    uint32_t hVASpace;
    uint32_t chId;
    uint32_t subDeviceId;
    uint32_t pasid;
};
static_assert(sizeof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05) == 32);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, physAddress) == 0);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, numEntries) == 8);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, flags) == 12);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, hVASpace) == 16);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, chId) == 20);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, subDeviceId) == 24);
static_assert(offsetof(struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05, pasid) == 28);
using NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05 = struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05;

struct struct_rpc_set_page_directory_v1E_05 {  // nv.py:1324
    uint32_t hClient;
    uint32_t hDevice;
    uint32_t pasid;
    uint8_t _pad0[4];
    struct_NV0080_CTRL_DMA_SET_PAGE_DIRECTORY_PARAMS_v1E_05 params;
};
static_assert(sizeof(struct_rpc_set_page_directory_v1E_05) == 48);
static_assert(offsetof(struct_rpc_set_page_directory_v1E_05, hClient) == 0);
static_assert(offsetof(struct_rpc_set_page_directory_v1E_05, hDevice) == 4);
static_assert(offsetof(struct_rpc_set_page_directory_v1E_05, pasid) == 8);
static_assert(offsetof(struct_rpc_set_page_directory_v1E_05, params) == 16);
using rpc_set_page_directory_v1E_05 = struct_rpc_set_page_directory_v1E_05;
using rpc_set_page_directory_v = struct_rpc_set_page_directory_v1E_05;

struct struct_rpc_unloading_guest_driver_v1F_07 {  // nv.py:1239
    uint8_t bInPMTransition;
    uint8_t bGc6Entering;
    uint8_t _pad0[2];
    uint32_t newLevel;
};
static_assert(sizeof(struct_rpc_unloading_guest_driver_v1F_07) == 8);
static_assert(offsetof(struct_rpc_unloading_guest_driver_v1F_07, bInPMTransition) == 0);
static_assert(offsetof(struct_rpc_unloading_guest_driver_v1F_07, bGc6Entering) == 1);
static_assert(offsetof(struct_rpc_unloading_guest_driver_v1F_07, newLevel) == 4);
using rpc_unloading_guest_driver_v1F_07 = struct_rpc_unloading_guest_driver_v1F_07;
using rpc_unloading_guest_driver_v = struct_rpc_unloading_guest_driver_v1F_07;

#pragma pack(pop)

} // namespace nv

namespace nv_gpu {
constexpr uint32_t ADA_COMPUTE_A = 0xc9c0;
constexpr uint32_t AMPERE_CHANNEL_GPFIFO_A = 0xc56f;
constexpr uint32_t AMPERE_COMPUTE_B = 0xc7c0;
constexpr uint32_t AMPERE_DMA_COPY_B = 0xc7b5;
constexpr uint32_t BLACKWELL_CHANNEL_GPFIFO_A = 0xc96f;
constexpr uint32_t BLACKWELL_COMPUTE_B = 0xcec0;
constexpr uint32_t BLACKWELL_DMA_COPY_B = 0xcab5;
constexpr uint32_t FERMI_CONTEXT_SHARE_A = 0x9067;
constexpr uint32_t FERMI_VASPACE_A = 0x90f1;
constexpr uint32_t GT200_DEBUGGER = 0x83de;
constexpr uint32_t KEPLER_CHANNEL_GROUP_A = 0xa06c;
constexpr uint32_t NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS = 0x0;
constexpr uint32_t NV0080_CTRL_FIFO_GET_ENGINE_CONTEXT_PROPERTIES_ENGINE_ID_GRAPHICS_PATCH = 0x10;
constexpr uint32_t NV01_DEVICE_0 = 0x80;
constexpr uint32_t NV01_MEMORY_LIST_SYSTEM = 0x81;
constexpr uint32_t NV01_MEMORY_VIRTUAL = 0x70;
constexpr uint32_t NV01_ROOT = 0x0;
constexpr uint32_t NV1_ROOT = 0x0;
constexpr uint32_t NV2080_CTRL_CMD_FIFO_GET_DEVICE_INFO_TABLE = 0x20801112;
constexpr uint32_t NV2080_CTRL_CMD_GPU_PROMOTE_CTX = 0x2080012b;
constexpr uint32_t NV2080_CTRL_CMD_INTERNAL_BUS_FLUSH_WITH_SYSMEMBAR = 0x20800a70;
constexpr uint32_t NV2080_CTRL_CMD_INTERNAL_STATIC_KGR_GET_CONTEXT_BUFFERS_INFO = 0x20800a32;
constexpr uint32_t NV2080_CTRL_CMD_INTERNAL_STATIC_KGR_GET_INFO = 0x20800a2a;
constexpr uint32_t NV2080_CTRL_CMD_PERF_BOOST = 0x2080200a;
constexpr uint32_t NV2080_CTRL_GR_INFO_INDEX_LITTER_NUM_GPCS = 0x14;
constexpr uint32_t NV2080_CTRL_GR_INFO_INDEX_LITTER_NUM_SM_PER_TPC = 0x20;
constexpr uint32_t NV2080_CTRL_GR_INFO_INDEX_LITTER_NUM_TPC_PER_GPC = 0x17;
constexpr uint32_t NV2080_CTRL_GR_INFO_INDEX_MAX_WARPS_PER_SM = 0xd;
constexpr uint32_t NV2080_CTRL_GR_INFO_INDEX_SM_VERSION = 0xc;
constexpr uint32_t NV2080_CTRL_PERF_BOOST_FLAGS_CMD_BOOST_TO_MAX = 0x2;
constexpr uint32_t NV2080_CTRL_PERF_BOOST_FLAGS_CUDA_PRIORITY_HIGH = 0x1;
constexpr uint32_t NV2080_CTRL_PERF_BOOST_FLAGS_CUDA_YES = 0x1;
constexpr uint32_t NV2080_ENGINE_TYPE_GRAPHICS = 0x1;
constexpr uint32_t NV2080_ENGINE_TYPE_NVDEC0 = 0x13;
constexpr uint32_t NV20_SUBDEVICE_0 = 0x2080;
constexpr uint32_t NV83DE_CTRL_CMD_DEBUG_READ_ALL_SM_ERROR_STATES = 0x83de030c;
constexpr uint32_t NV83DE_CTRL_CMD_DEBUG_READ_MMU_FAULT_INFO = 0x83de0328;
constexpr uint32_t NV90F1_CTRL_CMD_VASPACE_COPY_SERVER_RESERVED_PDES = 0x90f10106;
constexpr uint32_t NVA06C_CTRL_CMD_GPFIFO_SCHEDULE = 0xa06c0101;
constexpr uint32_t NVB0CC_CTRL_CMD_ALLOC_PMA_STREAM = 0xb0cc0105;
constexpr uint32_t NVB0CC_CTRL_CMD_INTERNAL_PERMISSIONS_INIT = 0xb0cc0203;
constexpr uint32_t NVB0CC_CTRL_CMD_POWER_REQUEST_FEATURES = 0xb0cc0301;
constexpr uint32_t NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN = 0xc36f0108;
constexpr uint32_t NVC9B0_VIDEO_DECODER = 0xc9b0;
constexpr uint32_t NVCFB0_VIDEO_DECODER = 0xcfb0;
constexpr uint32_t NVOS02_FLAGS_ALLOC_USER_READ_ONLY_YES = 0x1;
constexpr uint32_t NVOS02_FLAGS_MAPPING_NO_MAP = 0x1;
constexpr uint32_t NVOS02_FLAGS_PHYSICALITY_NONCONTIGUOUS = 0x1;
constexpr uint32_t NV_CTXSHARE_ALLOCATION_FLAGS_SUBCONTEXT_ASYNC = 0x1;
constexpr uint32_t NV_DEVICE_ALLOCATION_VAMODE_OPTIONAL_MULTIPLE_VASPACES = 0x0;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_ATOMIC = 0x2;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_PHYS_ATOMIC = 0xa;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_PHYS_PREFETCH = 0xb;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_PHYS_READ = 0x8;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_PHYS_WRITE = 0x9;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_PREFETCH = 0x3;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_READ = 0x0;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_ATOMIC = 0x2;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_ATOMIC_STRONG = 0x2;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_ATOMIC_WEAK = 0x4;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_PREFETCH = 0x3;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_READ = 0x0;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_VIRT_WRITE = 0x1;
constexpr uint32_t NV_PFAULT_ACCESS_TYPE_WRITE = 0x1;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_ATOMIC_VIOLATION = 0xf;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_COMPRESSION_FAILURE = 0xb;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_PDE = 0x0;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_PDE_SIZE = 0x1;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_PITCH_MASK_VIOLATION = 0x8;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_POISONED = 0xe;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_PRIV_VIOLATION = 0x5;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_PTE = 0x2;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_REGION_VIOLATION = 0xd;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_RO_VIOLATION = 0x6;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_UNBOUND_INST_BLOCK = 0x4;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_UNSUPPORTED_APERTURE = 0xa;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_UNSUPPORTED_KIND = 0xc;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_VA_LIMIT_VIOLATION = 0x3;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_WORK_CREATION = 0x9;
constexpr uint32_t NV_PFAULT_FAULT_TYPE_WO_VIOLATION = 0x7;
constexpr uint32_t NV_VASPACE_ALLOCATION_FLAGS_ENABLE_PAGE_FAULTING = 0x40;
constexpr uint32_t NV_VASPACE_ALLOCATION_FLAGS_IS_EXTERNALLY_OWNED = 0x8;

#pragma pack(push, 1)

struct volatile_struct_Nvc56fControl_struct {  // nv_570.py:1520
    uint32_t Ignored00[16];
    uint32_t Put;
    uint32_t Get;
    uint32_t Reference;
    uint32_t PutHi;
    uint32_t Ignored01[2];
    uint32_t TopLevelGet;
    uint32_t TopLevelGetHi;
    uint32_t GetHi;
    uint32_t Ignored02[7];
    uint32_t Ignored03;
    uint32_t Ignored04[1];
    uint32_t GPGet;
    uint32_t GPPut;
    uint32_t Ignored05[92];
};
static_assert(sizeof(volatile_struct_Nvc56fControl_struct) == 512);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored00) == 0);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Put) == 64);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Get) == 68);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Reference) == 72);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, PutHi) == 76);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored01) == 80);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, TopLevelGet) == 88);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, TopLevelGetHi) == 92);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, GetHi) == 96);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored02) == 100);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored03) == 128);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored04) == 132);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, GPGet) == 136);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, GPPut) == 140);
static_assert(offsetof(volatile_struct_Nvc56fControl_struct, Ignored05) == 144);
using Nvc56fControl = volatile_struct_Nvc56fControl_struct;
using AmpereAControlGPFifo = volatile_struct_Nvc56fControl_struct;

struct struct_NV0000_ALLOC_PARAMETERS {  // nv_570.py:1281
    uint32_t hClient;
    uint32_t processID;
    char processName[100];
    uint8_t _pad0[4];
    uint64_t pOsPidInfo;
};
static_assert(sizeof(struct_NV0000_ALLOC_PARAMETERS) == 120);
static_assert(offsetof(struct_NV0000_ALLOC_PARAMETERS, hClient) == 0);
static_assert(offsetof(struct_NV0000_ALLOC_PARAMETERS, processID) == 4);
static_assert(offsetof(struct_NV0000_ALLOC_PARAMETERS, processName) == 8);
static_assert(offsetof(struct_NV0000_ALLOC_PARAMETERS, pOsPidInfo) == 112);
using NV0000_ALLOC_PARAMETERS = struct_NV0000_ALLOC_PARAMETERS;

struct struct_NV0080_ALLOC_PARAMETERS {  // nv_570.py:1302
    uint32_t deviceId;
    uint32_t hClientShare;
    uint32_t hTargetClient;
    uint32_t hTargetDevice;
    uint32_t flags;
    uint8_t _pad0[4];
    uint64_t vaSpaceSize;
    uint64_t vaStartInternal;
    uint64_t vaLimitInternal;
    uint32_t vaMode;
    uint8_t _pad1[4];
};
static_assert(sizeof(struct_NV0080_ALLOC_PARAMETERS) == 56);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, deviceId) == 0);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, hClientShare) == 4);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, hTargetClient) == 8);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, hTargetDevice) == 12);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, flags) == 16);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, vaSpaceSize) == 24);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, vaStartInternal) == 32);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, vaLimitInternal) == 40);
static_assert(offsetof(struct_NV0080_ALLOC_PARAMETERS, vaMode) == 48);
using NV0080_ALLOC_PARAMETERS = struct_NV0080_ALLOC_PARAMETERS;

struct struct_NV2080_ALLOC_PARAMETERS {  // nv_570.py:1317
    uint32_t subDeviceId;
};
static_assert(sizeof(struct_NV2080_ALLOC_PARAMETERS) == 4);
static_assert(offsetof(struct_NV2080_ALLOC_PARAMETERS, subDeviceId) == 0);
using NV2080_ALLOC_PARAMETERS = struct_NV2080_ALLOC_PARAMETERS;

struct struct_NV2080_CTRL_FIFO_DEVICE_ENTRY {  // nv_570.py:7001
    uint32_t engineData[16];
    uint32_t pbdmaIds[2];
    uint32_t pbdmaFaultIds[2];
    uint32_t numPbdmas;
    char engineName[16];
};
static_assert(sizeof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY) == 100);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY, engineData) == 0);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY, pbdmaIds) == 64);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY, pbdmaFaultIds) == 72);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY, numPbdmas) == 80);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_DEVICE_ENTRY, engineName) == 84);
using NV2080_CTRL_FIFO_DEVICE_ENTRY = struct_NV2080_CTRL_FIFO_DEVICE_ENTRY;

struct struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS {  // nv_570.py:7011
    uint32_t baseIndex;
    uint32_t numEntries;
    uint8_t bMore;
    uint8_t _pad0[3];
    struct_NV2080_CTRL_FIFO_DEVICE_ENTRY entries[32];
};
static_assert(sizeof(struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS) == 3212);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS, baseIndex) == 0);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS, numEntries) == 4);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS, bMore) == 8);
static_assert(offsetof(struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS, entries) == 12);
using NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS = struct_NV2080_CTRL_FIFO_GET_DEVICE_INFO_TABLE_PARAMS;

struct struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY {  // nv_570.py:7396
    uint64_t gpuPhysAddr;
    uint64_t gpuVirtAddr;
    uint64_t size;
    uint32_t physAttr;
    uint16_t bufferId;
    uint8_t bInitialize;
    uint8_t bNonmapped;
};
static_assert(sizeof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY) == 32);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, gpuPhysAddr) == 0);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, gpuVirtAddr) == 8);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, size) == 16);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, physAttr) == 24);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, bufferId) == 28);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, bInitialize) == 30);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY, bNonmapped) == 31);
using NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY = struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY;

struct struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS {  // nv_570.py:7408
    uint32_t engineType;
    uint32_t hClient;
    uint32_t ChID;
    uint32_t hChanClient;
    uint32_t hObject;
    uint32_t hVirtMemory;
    uint64_t virtAddress;
    uint64_t size;
    uint32_t entryCount;
    uint8_t _pad0[4];
    struct_NV2080_CTRL_GPU_PROMOTE_CTX_BUFFER_ENTRY promoteEntry[16];
};
static_assert(sizeof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS) == 560);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, engineType) == 0);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, hClient) == 4);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, ChID) == 8);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, hChanClient) == 12);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, hObject) == 16);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, hVirtMemory) == 20);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, virtAddress) == 24);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, size) == 32);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, entryCount) == 40);
static_assert(offsetof(struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS, promoteEntry) == 48);
using NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS = struct_NV2080_CTRL_GPU_PROMOTE_CTX_PARAMS;

struct struct_NV2080_CTRL_INTERNAL_GR_INFO {  // nv_570.py:9125
    uint32_t index;
    uint32_t data;
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_GR_INFO) == 8);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_GR_INFO, index) == 0);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_GR_INFO, data) == 4);
using NV2080_CTRL_INTERNAL_GR_INFO = struct_NV2080_CTRL_INTERNAL_GR_INFO;

struct struct_NV2080_CTRL_INTERNAL_STATIC_GR_INFO {  // nv_570.py:9132
    struct_NV2080_CTRL_INTERNAL_GR_INFO infoList[58];
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_INFO) == 464);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_INFO, infoList) == 0);
using NV2080_CTRL_INTERNAL_STATIC_GR_INFO = struct_NV2080_CTRL_INTERNAL_STATIC_GR_INFO;

struct struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS {  // nv_570.py:9138
    struct_NV2080_CTRL_INTERNAL_STATIC_GR_INFO engineInfo[8];
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS) == 3712);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS, engineInfo) == 0);
using NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS = struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS;
using NV2080_CTRL_INTERNAL_STATIC_KGR_GET_INFO_PARAMS = struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_INFO_PARAMS;

struct struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO {  // nv_570.py:9195
    uint32_t size;
    uint32_t alignment;
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO) == 8);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO, size) == 0);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO, alignment) == 4);
using NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO = struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO;

struct struct_NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO {  // nv_570.py:9202
    struct_NV2080_CTRL_INTERNAL_ENGINE_CONTEXT_BUFFER_INFO engine[26];
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO) == 208);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO, engine) == 0);
using NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO = struct_NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO;

struct struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS {  // nv_570.py:9208
    struct_NV2080_CTRL_INTERNAL_STATIC_GR_CONTEXT_BUFFERS_INFO engineContextBuffersInfo[8];
};
static_assert(sizeof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS) == 1664);
static_assert(offsetof(struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS, engineContextBuffersInfo) == 0);
using NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS = struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS;
using NV2080_CTRL_INTERNAL_STATIC_KGR_GET_CONTEXT_BUFFERS_INFO_PARAMS = struct_NV2080_CTRL_INTERNAL_STATIC_GR_GET_CONTEXT_BUFFERS_INFO_PARAMS;

struct struct_NV2080_CTRL_PERF_BOOST_PARAMS {  // nv_570.py:12203
    uint32_t flags;
    uint32_t duration;
};
static_assert(sizeof(struct_NV2080_CTRL_PERF_BOOST_PARAMS) == 8);
static_assert(offsetof(struct_NV2080_CTRL_PERF_BOOST_PARAMS, flags) == 0);
static_assert(offsetof(struct_NV2080_CTRL_PERF_BOOST_PARAMS, duration) == 4);
using NV2080_CTRL_PERF_BOOST_PARAMS = struct_NV2080_CTRL_PERF_BOOST_PARAMS;

struct struct_NV83DE_ALLOC_PARAMETERS {  // nv_570.py:1597
    uint32_t hDebuggerClient_Obsolete;
    uint32_t hAppClient;
    uint32_t hClass3dObject;
};
static_assert(sizeof(struct_NV83DE_ALLOC_PARAMETERS) == 12);
static_assert(offsetof(struct_NV83DE_ALLOC_PARAMETERS, hDebuggerClient_Obsolete) == 0);
static_assert(offsetof(struct_NV83DE_ALLOC_PARAMETERS, hAppClient) == 4);
static_assert(offsetof(struct_NV83DE_ALLOC_PARAMETERS, hClass3dObject) == 8);
using NV83DE_ALLOC_PARAMETERS = struct_NV83DE_ALLOC_PARAMETERS;

struct struct_NV83DE_SM_ERROR_STATE_REGISTERS {  // nv_570.py:12907
    uint32_t hwwGlobalEsr;
    uint32_t hwwWarpEsr;
    uint32_t hwwWarpEsrPc;
    uint32_t hwwGlobalEsrReportMask;
    uint32_t hwwWarpEsrReportMask;
    uint8_t _pad0[4];
    uint64_t hwwEsrAddr;
    uint64_t hwwWarpEsrPc64;
    uint32_t hwwCgaEsr;
    uint32_t hwwCgaEsrReportMask;
};
static_assert(sizeof(struct_NV83DE_SM_ERROR_STATE_REGISTERS) == 48);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwGlobalEsr) == 0);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwWarpEsr) == 4);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwWarpEsrPc) == 8);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwGlobalEsrReportMask) == 12);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwWarpEsrReportMask) == 16);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwEsrAddr) == 24);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwWarpEsrPc64) == 32);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwCgaEsr) == 40);
static_assert(offsetof(struct_NV83DE_SM_ERROR_STATE_REGISTERS, hwwCgaEsrReportMask) == 44);
using NV83DE_SM_ERROR_STATE_REGISTERS = struct_NV83DE_SM_ERROR_STATE_REGISTERS;

struct struct_NV83DE_MMU_FAULT_INFO {  // nv_570.py:12929
    uint8_t valid;
    uint8_t _pad0[3];
    uint32_t faultInfo;
};
static_assert(sizeof(struct_NV83DE_MMU_FAULT_INFO) == 8);
static_assert(offsetof(struct_NV83DE_MMU_FAULT_INFO, valid) == 0);
static_assert(offsetof(struct_NV83DE_MMU_FAULT_INFO, faultInfo) == 4);
using NV83DE_MMU_FAULT_INFO = struct_NV83DE_MMU_FAULT_INFO;

struct struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS {  // nv_570.py:12936
    uint32_t hTargetChannel;
    uint32_t numSMsToRead;
    struct_NV83DE_SM_ERROR_STATE_REGISTERS smErrorStateArray[100];
    uint32_t mmuFaultInfo;
    struct_NV83DE_MMU_FAULT_INFO mmuFault;
    uint32_t startingSM;
};
static_assert(sizeof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS) == 4824);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, hTargetChannel) == 0);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, numSMsToRead) == 4);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, smErrorStateArray) == 8);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, mmuFaultInfo) == 4808);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, mmuFault) == 4812);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS, startingSM) == 4820);
using NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS = struct_NV83DE_CTRL_DEBUG_READ_ALL_SM_ERROR_STATES_PARAMS;

struct struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY {  // nv_570.py:13123
    uint64_t faultAddress;
    uint32_t faultType;
    uint32_t accessType;
};
static_assert(sizeof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY) == 16);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY, faultAddress) == 0);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY, faultType) == 8);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY, accessType) == 12);
using NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY = struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY;

struct struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS {  // nv_570.py:13131
    struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_ENTRY mmuFaultInfoList[4];
    uint32_t count;
    uint8_t _pad0[4];
};
static_assert(sizeof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS) == 72);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS, mmuFaultInfoList) == 0);
static_assert(offsetof(struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS, count) == 64);
using NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS = struct_NV83DE_CTRL_DEBUG_READ_MMU_FAULT_INFO_PARAMS;

struct struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS {  // nv_570.py:3439
    uint8_t bEnable;
    uint8_t bSkipSubmit;
};
static_assert(sizeof(struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS) == 2);
static_assert(offsetof(struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS, bEnable) == 0);
static_assert(offsetof(struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS, bSkipSubmit) == 1);
using NVA06C_CTRL_GPFIFO_SCHEDULE_PARAMS = struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS;
using NVA06C_CTRL_INTERNAL_GPFIFO_SCHEDULE_PARAMS = struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS;
using NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS = struct_NVA06F_CTRL_GPFIFO_SCHEDULE_PARAMS;

struct struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS {  // nv_570.py:13193
    uint8_t bAdminProfilingPermitted;
    uint8_t bDevProfilingPermitted;
    uint8_t bCtxProfilingPermitted;
    uint8_t bVideoMemoryProfilingPermitted;
    uint8_t bSysMemoryProfilingPermitted;
};
static_assert(sizeof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS) == 5);
static_assert(offsetof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS, bAdminProfilingPermitted) == 0);
static_assert(offsetof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS, bDevProfilingPermitted) == 1);
static_assert(offsetof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS, bCtxProfilingPermitted) == 2);
static_assert(offsetof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS, bVideoMemoryProfilingPermitted) == 3);
static_assert(offsetof(struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS, bSysMemoryProfilingPermitted) == 4);
using NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS = struct_NVB0CC_CTRL_INTERNAL_PERMISSIONS_INIT_PARAMS;

struct struct_NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS {  // nv_570.py:3336
    uint32_t workSubmitToken;
};
static_assert(sizeof(struct_NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS) == 4);
static_assert(offsetof(struct_NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS, workSubmitToken) == 0);
using NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS = struct_NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS;
using NVC36F_CTRL_INTERNAL_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS = struct_NVC36F_CTRL_CMD_GPFIFO_GET_WORK_SUBMIT_TOKEN_PARAMS;

struct struct_NV_MEMORY_DESC_PARAMS {  // nv_570.py:2528
    uint64_t base;
    uint64_t size;
    uint32_t addressSpace;
    uint32_t cacheAttrib;
};
static_assert(sizeof(struct_NV_MEMORY_DESC_PARAMS) == 24);
static_assert(offsetof(struct_NV_MEMORY_DESC_PARAMS, base) == 0);
static_assert(offsetof(struct_NV_MEMORY_DESC_PARAMS, size) == 8);
static_assert(offsetof(struct_NV_MEMORY_DESC_PARAMS, addressSpace) == 16);
static_assert(offsetof(struct_NV_MEMORY_DESC_PARAMS, cacheAttrib) == 20);
using NV_MEMORY_DESC_PARAMS = struct_NV_MEMORY_DESC_PARAMS;

struct struct_NV_CHANNEL_ALLOC_PARAMS {  // nv_570.py:2537
    uint32_t hObjectError;
    uint32_t hObjectBuffer;
    uint64_t gpFifoOffset;
    uint32_t gpFifoEntries;
    uint32_t flags;
    uint32_t hContextShare;
    uint32_t hVASpace;
    uint32_t hUserdMemory[8];
    uint64_t userdOffset[8];
    uint32_t engineType;
    uint32_t cid;
    uint32_t subDeviceId;
    uint32_t hObjectEccError;
    struct_NV_MEMORY_DESC_PARAMS instanceMem;
    struct_NV_MEMORY_DESC_PARAMS userdMem;
    struct_NV_MEMORY_DESC_PARAMS ramfcMem;
    struct_NV_MEMORY_DESC_PARAMS mthdbufMem;
    uint32_t hPhysChannelGroup;
    uint32_t internalFlags;
    struct_NV_MEMORY_DESC_PARAMS errorNotifierMem;
    struct_NV_MEMORY_DESC_PARAMS eccErrorNotifierMem;
    uint32_t ProcessID;
    uint32_t SubProcessID;
    uint32_t encryptIv[3];
    uint32_t decryptIv[3];
    uint32_t hmacNonce[8];
    uint32_t tpcConfigID;
    uint8_t _pad0[4];
};
static_assert(sizeof(struct_NV_CHANNEL_ALLOC_PARAMS) == 368);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hObjectError) == 0);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hObjectBuffer) == 4);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, gpFifoOffset) == 8);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, gpFifoEntries) == 16);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, flags) == 20);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hContextShare) == 24);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hVASpace) == 28);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hUserdMemory) == 32);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, userdOffset) == 64);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, engineType) == 128);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, cid) == 132);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, subDeviceId) == 136);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hObjectEccError) == 140);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, instanceMem) == 144);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, userdMem) == 168);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, ramfcMem) == 192);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, mthdbufMem) == 216);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hPhysChannelGroup) == 240);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, internalFlags) == 244);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, errorNotifierMem) == 248);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, eccErrorNotifierMem) == 272);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, ProcessID) == 296);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, SubProcessID) == 300);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, encryptIv) == 304);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, decryptIv) == 316);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, hmacNonce) == 328);
static_assert(offsetof(struct_NV_CHANNEL_ALLOC_PARAMS, tpcConfigID) == 360);
using NV_CHANNEL_ALLOC_PARAMS = struct_NV_CHANNEL_ALLOC_PARAMS;
using NV_CHANNELGPFIFO_ALLOCATION_PARAMETERS = struct_NV_CHANNEL_ALLOC_PARAMS;

struct NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS {  // nv_570.py:3202
    uint32_t hObjectError;
    uint32_t hObjectEccError;
    uint32_t hVASpace;
    uint32_t engineType;
    uint8_t bIsCallingContextVgpuPlugin;
    uint8_t _pad0[3];
};
static_assert(sizeof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS) == 20);
static_assert(offsetof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hObjectError) == 0);
static_assert(offsetof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hObjectEccError) == 4);
static_assert(offsetof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, hVASpace) == 8);
static_assert(offsetof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, engineType) == 12);
static_assert(offsetof(NV_CHANNEL_GROUP_ALLOCATION_PARAMETERS, bIsCallingContextVgpuPlugin) == 16);

struct NV_CTXSHARE_ALLOCATION_PARAMETERS {  // nv_570.py:3306
    uint32_t hVASpace;
    uint32_t flags;
    uint32_t subctxId;
};
static_assert(sizeof(NV_CTXSHARE_ALLOCATION_PARAMETERS) == 12);
static_assert(offsetof(NV_CTXSHARE_ALLOCATION_PARAMETERS, hVASpace) == 0);
static_assert(offsetof(NV_CTXSHARE_ALLOCATION_PARAMETERS, flags) == 4);
static_assert(offsetof(NV_CTXSHARE_ALLOCATION_PARAMETERS, subctxId) == 8);

struct struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS {  // nv_570.py:1293
    uint64_t offset;
    uint64_t limit;
    uint32_t hVASpace;
    uint8_t _pad0[4];
};
static_assert(sizeof(struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS) == 24);
static_assert(offsetof(struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS, offset) == 0);
static_assert(offsetof(struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS, limit) == 8);
static_assert(offsetof(struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS, hVASpace) == 16);
using NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS = struct_NV_MEMORY_VIRTUAL_ALLOCATION_PARAMS;

struct NV_VASPACE_ALLOCATION_PARAMETERS {  // nv_570.py:3295
    uint32_t index;
    uint32_t flags;
    uint64_t vaSize;
    uint64_t vaStartInternal;
    uint64_t vaLimitInternal;
    uint32_t bigPageSize;
    uint8_t _pad0[4];
    uint64_t vaBase;
};
static_assert(sizeof(NV_VASPACE_ALLOCATION_PARAMETERS) == 48);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, index) == 0);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, flags) == 4);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, vaSize) == 8);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, vaStartInternal) == 16);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, vaLimitInternal) == 24);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, bigPageSize) == 32);
static_assert(offsetof(NV_VASPACE_ALLOCATION_PARAMETERS, vaBase) == 40);

struct struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level {  // nv_570.py:3598
    uint64_t physAddress;
    uint64_t size;
    uint32_t aperture;
    uint8_t pageShift;
    uint8_t _pad0[3];
};
static_assert(sizeof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level) == 24);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level, physAddress) == 0);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level, size) == 8);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level, aperture) == 16);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level, pageShift) == 20);

struct struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS {  // nv_570.py:3588
    uint32_t hSubDevice;
    uint32_t subDeviceId;
    uint64_t pageSize;
    uint64_t virtAddrLo;
    uint64_t virtAddrHi;
    uint32_t numLevelsToCopy;
    uint8_t _pad0[4];
    struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS_level levels[6];
};
static_assert(sizeof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS) == 184);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, hSubDevice) == 0);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, subDeviceId) == 4);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, pageSize) == 8);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, virtAddrLo) == 16);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, virtAddrHi) == 24);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, numLevelsToCopy) == 32);
static_assert(offsetof(struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS, levels) == 40);
using NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS = struct_NV90F1_CTRL_VASPACE_COPY_SERVER_RESERVED_PDES_PARAMS;

#pragma pack(pop)

} // namespace nv_gpu
} // namespace tinygpu_device

#endif // LIBHMSBEAGLE_GPU_TINYGPUNVRMTABLES_H
