/*
 * TinyGPUAMDTables.h -- GENERATED by make_tinygpu_amd_tables.py from tinygrad (the pin's autogen: am/pm4_nv.py,
 * am/sdma_6_0_0.py, am/soc_11.py, am/navi_offsets.py with the gc 11.0.0, nbio 4.3.0 and osssys 6.0.0 register tables,
 * hsa.py and amdgpu_kd.py). Do not edit.
 *
 * The constants of ops_amd.py's AMDComputeQueue and AMDCopyQueue on gfx11 (TODO.md plan step A1a). Registers are at
 * navi_offsets' constant bases, as AMDDevice.gc and AMDDevice.nbio are (PM4 offsets); the discovered MMIO addresses
 * come from the daemon's handoff. A Field is a macro of the form (x & mask) << shift, mask 0 when it has none.
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H
#define LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H

#include <cstdint>

namespace tinygpu_device {
namespace amdt {

struct Field { uint64_t mask; uint32_t shift; };
constexpr uint64_t put(Field f, uint64_t x) { return (f.mask ? (x & f.mask) : x) << f.shift; }
struct Bits { uint32_t lo, hi; };   // AMDReg.fields: inclusive bit positions
constexpr uint64_t encode(Bits b, uint64_t x) { return x << b.lo; }   // AMDReg.encode does not mask
constexpr uint64_t getbits(uint64_t v, Bits b) { return (v >> b.lo) & ((1ull << (b.hi - b.lo + 1)) - 1); }
constexpr uint64_t mask(Bits b) { return ((1ull << (b.hi - b.lo + 1)) - 1) << b.lo; }

// ---- PM4 (pm4_nv.py) and soc21 (soc_11.py)
constexpr uint32_t PACKET_TYPE3 = 3;
constexpr uint32_t PACKET3(uint32_t op, uint32_t n) { return (PACKET_TYPE3 << 30) | ((op & 0xFFu) << 8) | ((n & 0x3FFFu) << 16); }
constexpr uint32_t PACKET3_SET_SH_REG = 0x76u;
constexpr uint32_t PACKET3_SET_SH_REG_START = 0x2c00u;
constexpr uint32_t PACKET3_SET_SH_REG_END = 0x3000u;
constexpr uint32_t PACKET3_SET_UCONFIG_REG = 0x79u;
constexpr uint32_t PACKET3_SET_UCONFIG_REG_START = 0xc000u;
constexpr uint32_t PACKET3_WAIT_REG_MEM = 0x3cu;
constexpr uint32_t PACKET3_ACQUIRE_MEM = 0x58u;
constexpr uint32_t PACKET3_RELEASE_MEM = 0x49u;
constexpr uint32_t PACKET3_DISPATCH_DIRECT = 0x15u;
constexpr uint32_t PACKET3_EVENT_WRITE = 0x46u;
constexpr uint32_t CACHE_FLUSH_AND_INV_TS_EVENT = 0x14u;
constexpr uint32_t event_index__mec_release_mem__end_of_pipe = 0x5u;
constexpr uint32_t data_sel__mec_release_mem__send_32_bit_low = 0x1u;
constexpr uint32_t int_sel__mec_release_mem__none = 0x0u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GLV_INV = 0x4000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GL1_INV = 0x8000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GL2_INV = 0x100000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GLM_WB = 0x1000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GLM_INV = 0x2000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_GL2_WB = 0x200000u;
constexpr uint32_t PACKET3_RELEASE_MEM_GCR_SEQ = 0x400000u;
constexpr Field WAIT_REG_MEM_MEM_SPACE = {0x0u, 4};
constexpr Field WAIT_REG_MEM_OPERATION = {0x0u, 6};
constexpr Field WAIT_REG_MEM_FUNCTION = {0x0u, 0};
constexpr Field WAIT_REG_MEM_ENGINE = {0x0u, 8};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLI_INV = {0x0u, 0};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLM_INV = {0x0u, 5};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLM_WB = {0x0u, 4};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLK_INV = {0x0u, 7};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLK_WB = {0x0u, 6};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GLV_INV = {0x0u, 8};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GL1_INV = {0x0u, 9};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GL2_INV = {0x0u, 14};
constexpr Field PACKET3_ACQUIRE_MEM_GCR_CNTL_GL2_WB = {0x0u, 15};
constexpr Field PACKET3_RELEASE_MEM_EVENT_TYPE = {0x0u, 0};
constexpr Field PACKET3_RELEASE_MEM_EVENT_INDEX = {0x0u, 8};
constexpr Field PACKET3_RELEASE_MEM_DATA_SEL = {0x0u, 29};
constexpr Field PACKET3_RELEASE_MEM_INT_SEL = {0x0u, 24};
constexpr Field PACKET3_RELEASE_MEM_DST_SEL = {0x0u, 16};
constexpr Field EVENT_TYPE = {0x0u, 0};
constexpr Field EVENT_INDEX = {0x0u, 8};
constexpr uint32_t CS_PARTIAL_FLUSH = 0x7u;   // soc_11
constexpr uint32_t EVENT_INDEX_PARTIAL_FLUSH = 4;   // ops_amd.py
constexpr uint32_t WAIT_REG_MEM_FUNCTION_EQ = 3, WAIT_REG_MEM_FUNCTION_GEQ = 5;

// ---- SDMA (sdma_6_0_0.py)
constexpr uint32_t SDMA_OP_COPY = 0x1u;
constexpr uint32_t SDMA_SUBOP_COPY_LINEAR = 0x0u;
constexpr uint32_t SDMA_OP_FENCE = 0x5u;
constexpr uint32_t SDMA_OP_POLL_REGMEM = 0x8u;
constexpr Field SDMA_PKT_COPY_LINEAR_HEADER_SUB_OP = {0xffu, 8};
constexpr Field SDMA_PKT_COPY_LINEAR_COUNT_COUNT = {0x3fffffffu, 0};
constexpr Field SDMA_PKT_FENCE_HEADER_MTYPE = {0x7u, 16};
constexpr Field SDMA_PKT_POLL_REGMEM_HEADER_FUNC = {0x7u, 28};
constexpr Field SDMA_PKT_POLL_REGMEM_HEADER_MEM_POLL = {0x1u, 31};
constexpr Field SDMA_PKT_POLL_REGMEM_DW5_INTERVAL = {0xffffu, 0};
constexpr Field SDMA_PKT_POLL_REGMEM_DW5_RETRY_COUNT = {0xfffu, 16};

// ---- gc 11.0.0 at navi_offsets' GC bases (AMDDevice.gc): PM4 register offsets, and the fields encode() names
constexpr uint32_t regCOMPUTE_PGM_LO = 0x2e0cu;
constexpr uint32_t regCOMPUTE_PGM_RSRC1 = 0x2e12u;
constexpr uint32_t regCOMPUTE_PGM_RSRC3 = 0x2e28u;
constexpr uint32_t regCOMPUTE_TMPRING_SIZE = 0x2e18u;
constexpr uint32_t regCOMPUTE_DISPATCH_SCRATCH_BASE_LO = 0x2e10u;
constexpr uint32_t regCOMPUTE_RESTART_X = 0x2e1bu;
constexpr uint32_t regCOMPUTE_USER_DATA_0 = 0x2e40u;
constexpr uint32_t regCOMPUTE_RESOURCE_LIMITS = 0x2e15u;
constexpr uint32_t regCOMPUTE_START_X = 0x2e04u;
constexpr uint32_t regCOMPUTE_DISPATCH_INITIATOR = 0x2e00u;
constexpr Bits COMPUTE_DISPATCH_INITIATOR__compute_shader_en = {0, 0};
constexpr Bits COMPUTE_DISPATCH_INITIATOR__force_start_at_000 = {2, 2};
constexpr Bits COMPUTE_DISPATCH_INITIATOR__cs_w32_en = {15, 15};
constexpr Bits COMPUTE_RESOURCE_LIMITS__waves_per_sh = {0, 9};
constexpr Bits GCVM_L2_PROTECTION_FAULT_CNTL__clear_protection_fault_status_addr = {0, 0};
// nbio 4.3.0 at navi_offsets' NBIO bases (AMDDevice.nbio): memory_barrier's HDP flush request and done
constexpr uint32_t regBIF_BX_PF0_GPU_HDP_FLUSH_REQ = 0xe26u;
constexpr uint32_t regBIF_BX_PF0_GPU_HDP_FLUSH_DONE = 0xe27u;
// osssys 6.0.0: the IH ring fields AM_IH.drain reads and updates (the registers' MMIO addresses are the handoff's)
constexpr Bits IH_RB_WPTR__offset = {2, 17};
constexpr Bits IH_RB_WPTR__rb_overflow = {0, 0};
constexpr Bits IH_RB_CNTL__wptr_overflow_clear = {31, 31};

// ---- am.py: the IH ring entry (SOC15_*_FROM_IH_ENTRY), soc21's clients and gfx11's sources (AM_SOC.ih_srcs_names, AM_IH)
struct IHField { uint32_t dword, shift, mask; };
constexpr IHField IH_CLIENT_ID = {0, 0, 0xffu};
constexpr IHField IH_SOURCE_ID = {0, 8, 0xffu};
constexpr IHField IH_RING_ID = {0, 16, 0xffu};
constexpr IHField IH_VMID = {0, 24, 0xfu};
constexpr IHField IH_VMID_TYPE = {0, 31, 0x1u};
constexpr IHField IH_PASID = {3, 0, 0xffffu};
constexpr IHField IH_NODEID = {3, 16, 0xffu};
constexpr IHField IH_CONTEXT_ID0 = {4, 0, 0xffffffffu};
constexpr IHField IH_CONTEXT_ID1 = {5, 0, 0xffffffffu};
constexpr IHField IH_CONTEXT_ID2 = {6, 0, 0xffffffffu};
constexpr IHField IH_CONTEXT_ID3 = {7, 0, 0xffffffffu};
constexpr uint32_t ih_get(const uint32_t e[8], IHField f) { return (e[f.dword] >> f.shift) & f.mask; }
constexpr uint32_t SOC21_IH_CLIENTID_GRBM_CP = 20, SOC21_IH_CLIENTID_GFX = 10;   // gfx_ih_clients
struct IHName { uint32_t id; const char* name; };
constexpr IHName IH_GFX11_SRCS[] = {{0, "UTCL2_FAULT"}, {1, "UTCL2_DATA_POISONING"}, {10, "MEM_ACCES_MON"}, {48, "SDMA_ATOMIC_RTN_DONE"}, {49, "SDMA_TRAP"}, {50, "SDMA_SRBMWRITE"}, {51, "SDMA_CTXEMPTY"}, {52, "SDMA_PREEMPT"}, {53, "SDMA_IB_PREEMPT"}, {54, "SDMA_DOORBELL_INVALID"}, {55, "SDMA_QUEUE_HANG"}, {56, "SDMA_ATOMIC_TIMEOUT"}, {57, "SDMA_POLL_TIMEOUT"}, {58, "SDMA_PAGE_TIMEOUT"}, {59, "SDMA_PAGE_NULL"}, {60, "SDMA_PAGE_FAULT"}, {61, "SDMA_VM_HOLE"}, {62, "SDMA_ECC"}, {63, "SDMA_FROZEN"}, {64, "SDMA_SRAM_ECC"}, {65, "SDMA_SEM_INCOMPLETE_TIMEOUT"}, {66, "SDMA_SEM_WAIT_FAIL_TIMEOUT"}, {67, "SDMA_FENCE"}, {128, "RLC_GC_FED_INTERRUPT"}, {177, "CP_GENERIC_INT"}, {180, "CP_PM4_PKT_RSVD_BIT_ERROR"}, {181, "CP_EOP_INTERRUPT"}, {183, "CP_BAD_OPCODE_ERROR"}, {184, "CP_PRIV_REG_FAULT"}, {185, "CP_PRIV_INSTR_FAULT"}, {186, "CP_WAIT_MEM_SEM_FAULT"}, {187, "CP_CTX_EMPTY_INTERRUPT"}, {188, "CP_CTX_BUSY_INTERRUPT"}, {192, "CP_ME_WAIT_REG_MEM_POLL_TIMEOUT"}, {193, "CP_SIG_INCOMPLETE"}, {194, "CP_PREEMPT_ACK"}, {195, "CP_GPF"}, {196, "CP_GDS_ALLOC_ERROR"}, {197, "CP_ECC_ERROR"}, {199, "CP_COMPUTE_QUERY_STATUS"}, {200, "CP_VM_DOORBELL"}, {201, "CP_FUE_ERROR"}, {202, "RLC_STRM_PERF_MONITOR_INTERRUPT"}, {232, "GRBM_RD_TIMEOUT_ERROR"}, {233, "GRBM_REG_GUI_IDLE"}, {239, "SQ_INTERRUPT_ID"}};
constexpr IHName IH_SOC21_CLIENTS[] = {{0, "SOC21_IH_CLIENTID_IH"}, {2, "SOC21_IH_CLIENTID_ATHUB"}, {3, "SOC21_IH_CLIENTID_BIF"}, {4, "SOC21_IH_CLIENTID_DCN"}, {5, "SOC21_IH_CLIENTID_ISP"}, {6, "SOC21_IH_CLIENTID_MP3"}, {7, "SOC21_IH_CLIENTID_RLC"}, {10, "SOC21_IH_CLIENTID_GFX"}, {11, "SOC21_IH_CLIENTID_IMU"}, {14, "SOC21_IH_CLIENTID_VCN1"}, {15, "SOC21_IH_CLIENTID_THM"}, {16, "SOC21_IH_CLIENTID_VCN"}, {17, "SOC21_IH_CLIENTID_VPE1"}, {18, "SOC21_IH_CLIENTID_VMC"}, {20, "SOC21_IH_CLIENTID_GRBM_CP"}, {22, "SOC21_IH_CLIENTID_ROM_SMUIO"}, {23, "SOC21_IH_CLIENTID_DF"}, {24, "SOC21_IH_CLIENTID_VPE"}, {25, "SOC21_IH_CLIENTID_PWR"}, {26, "SOC21_IH_CLIENTID_LSDMA"}, {30, "SOC21_IH_CLIENTID_MP0"}, {31, "SOC21_IH_CLIENTID_MP1"}, {32, "SOC21_IH_CLIENTID_MAX"}};

// ---- hsa.py: kernel code properties and COMPUTE_TMPRING_SIZE_GFX11
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_DISPATCH_ID = 0x10u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_DISPATCH_PTR = 0x2u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_FLAT_SCRATCH_INIT = 0x20u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_GRID_WORKGROUP_COUNT_X = 0x80u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_GRID_WORKGROUP_COUNT_Y = 0x100u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_GRID_WORKGROUP_COUNT_Z = 0x200u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_KERNARG_SEGMENT_PTR = 0x8u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_PRIVATE_SEGMENT_BUFFER = 0x1u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_PRIVATE_SEGMENT_SIZE = 0x40u;
constexpr uint32_t AMD_KERNEL_CODE_PROPERTIES_ENABLE_SGPR_QUEUE_PTR = 0x4u;
constexpr uint32_t KERNEL_CODE_PROPERTIES_WAVE32 = 0x400u;   // AMDProgram.__init__ tests this bit
constexpr Bits TMPRING_GFX11_WAVES = {0, 11};
constexpr Bits TMPRING_GFX11_WAVESIZE = {12, 26};

// ---- amdgpu_kd.py: llvm_amdhsa_kernel_descriptor_t (byte offsets)
constexpr uint32_t KD_SIZE = 64;
constexpr uint32_t KD_GROUP_SEGMENT_FIXED_SIZE = 0;   // 4 bytes
constexpr uint32_t KD_PRIVATE_SEGMENT_FIXED_SIZE = 4;   // 4 bytes
constexpr uint32_t KD_KERNARG_SIZE = 8;   // 4 bytes
constexpr uint32_t KD_KERNEL_CODE_ENTRY_BYTE_OFFSET = 16;   // 8 bytes
constexpr uint32_t KD_COMPUTE_PGM_RSRC3 = 44;   // 4 bytes
constexpr uint32_t KD_COMPUTE_PGM_RSRC1 = 48;   // 4 bytes
constexpr uint32_t KD_COMPUTE_PGM_RSRC2 = 52;   // 4 bytes
constexpr uint32_t KD_KERNEL_CODE_PROPERTIES = 56;   // 2 bytes
constexpr uint32_t KD_KERNARG_PRELOAD = 58;   // 2 bytes

// ---- gfx12 (GC 12.0.x: Navi 44 and 48, TODO.md plan step N2): what differs from gfx11's; every other constant is the same
constexpr IHName IH_GFX12_SRCS[] = {{0, "UTCL2_FAULT"}, {1, "UTCL2_DATA_POISONING"}, {10, "MEM_ACCES_MON"}, {48, "SDMA_ATOMIC_RTN_DONE"}, {49, "SDMA_TRAP"}, {50, "SDMA_SRBMWRITE"}, {51, "SDMA_CTXEMPTY"}, {52, "SDMA_PREEMPT"}, {53, "SDMA_IB_PREEMPT"}, {54, "SDMA_DOORBELL_INVALID"}, {55, "SDMA_QUEUE_HANG"}, {56, "SDMA_ATOMIC_TIMEOUT"}, {57, "SDMA_POLL_TIMEOUT"}, {58, "SDMA_PAGE_TIMEOUT"}, {59, "SDMA_PAGE_NULL"}, {60, "SDMA_PAGE_FAULT"}, {61, "SDMA_VM_HOLE"}, {62, "SDMA_ECC"}, {63, "SDMA_FROZEN"}, {64, "SDMA_SRAM_ECC"}, {65, "SDMA_SEM_INCOMPLETE_TIMEOUT"}, {66, "SDMA_SEM_WAIT_FAIL_TIMEOUT"}, {70, "SDMA_FENCE"}, {128, "RLC_GC_FED_INTERRUPT"}, {177, "CP_GENERIC_INT"}, {180, "CP_PM4_PKT_RSVD_BIT_ERROR"}, {181, "CP_EOP_INTERRUPT"}, {183, "CP_BAD_OPCODE_ERROR"}, {184, "CP_PRIV_REG_FAULT"}, {185, "CP_PRIV_INSTR_FAULT"}, {186, "CP_WAIT_MEM_SEM_FAULT"}, {187, "CP_CTX_EMPTY_INTERRUPT"}, {188, "CP_CTX_BUSY_INTERRUPT"}, {192, "CP_ME_WAIT_REG_MEM_POLL_TIMEOUT"}, {193, "CP_SIG_INCOMPLETE"}, {194, "CP_PREEMPT_ACK"}, {195, "CP_GPF"}, {196, "CP_GDS_ALLOC_ERROR"}, {197, "CP_ECC_ERROR"}, {199, "CP_COMPUTE_QUERY_STATUS"}, {200, "CP_VM_DOORBELL"}, {201, "CP_FUE_ERROR"}, {202, "RLC_STRM_PERF_MONITOR_INTERRUPT"}, {232, "GRBM_RD_TIMEOUT_ERROR"}, {233, "GRBM_REG_GUI_IDLE"}, {239, "SQ_INTERRUPT_ID"}};
constexpr Bits TMPRING_GFX12_WAVES = {0, 11};
constexpr Bits TMPRING_GFX12_WAVESIZE = {12, 29};

}  // namespace amdt
}  // namespace tinygpu_device

#endif  // LIBHMSBEAGLE_GPU_TINYGPUAMDTABLES_H
