/*
 * TinyGPUFirmwareManifest.h -- GENERATED by make_tinygpu_fw_manifest.py from tinygrad a9830e2b4 and
 * libhmsbeagle/GPU/nv_init_helper.py. Do not edit. TODO.md plan step C4.
 *
 * Every NVIDIA firmware file tinygrad's NV boot fetches (helpers.fetch_fw), per chip family, and the Booter Unload
 * image of BEAGLE's teardown: the arguments of each fetch_fw call, the URL it builds, and md5(URL), the file's name
 * in tinygrad's download cache (<cache>/tinygrad/downloads/fw/<md5>). TinyGPUFirmware.h finds and checks them.
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H
#define LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H

namespace tinygpu_device {
namespace nvfw {

constexpr const char* kLinuxFirmware = "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/0a6871b19abf5d6e024b5d208b101ae53e7fa0de";   // helpers.fetch_fw's pin

struct TGFirmware {
    const char* chip;     // NVDev.fw_name
    const char* role;     // booter_load, fmc, gsp, bootloader or booter_unload
    const char* subdir;   // fetch_fw's path
    const char* name;
    const char* sha256;
    const char* url_md5;  // its name in tinygrad's download cache
};

constexpr TGFirmware kFirmware[] = {
    {"ga102", "booter_load", "nvidia/ga102/gsp", "booter_load-570.144.bin", "4497e3eff7e95c774b8a569d17b27c08c9650158d10b229d2be81cdcad9a085b", "fea1362dc23c38a882c531fdcb696eb6"},  // NV_FLCN.prep_booter, ip.py:170-174
    {"ga102", "gsp", "nvidia/ga102/gsp", "gsp-570.144.bin", "a8c3ebeed280323aedb51c061f321e73379cce7a9ae643a33dd03915df027f7f", "fb02697830bcd6e5f04f85dce7b52579"},  // NV_GSP.init_gsp_image, ip.py:401-402
    {"ga102", "bootloader", "nvidia/ga102/gsp", "bootloader-570.144.bin", "82428f532240727e95bb3083fbaaba9b2cc7b937314323f2d546ce7245f27fad", "ec7d71cfb9dbc7d91c47f370c3aba879"},  // NV_GSP.init_boot_binary_image, ip.py:425-429
    {"ga102", "booter_unload", "nvidia/ga102/gsp", "booter_unload-570.144.bin", "8e63db5b78d7d3e349f20a2d11099c3d7109081393cb09ffc0a28133324ae009", "0b50da0d38e67979f63d03be0164ab5b"},  // nv_init_helper._booter_ucode (plan step P2)
    {"ad102", "booter_load", "nvidia/ad102/gsp", "booter_load-570.144.bin", "8b293e19b637c5e22c87a2428d1c71bb13e0904e8a88ac6b3c6c1f2679c6e37a", "d430a4a66bb0b0282e0421d923dfc4d0"},  // NV_FLCN.prep_booter, ip.py:170-174
    {"ad102", "gsp", "nvidia/ga102/gsp", "gsp-570.144.bin", "a8c3ebeed280323aedb51c061f321e73379cce7a9ae643a33dd03915df027f7f", "fb02697830bcd6e5f04f85dce7b52579"},  // NV_GSP.init_gsp_image, ip.py:401-402
    {"ad102", "bootloader", "nvidia/ad102/gsp", "bootloader-570.144.bin", "65ab2e6b6e0fca95365c4deac79a34582abcfeb15b6ae234138f22e7183118a8", "a5eb117d5124952eb03a12425b682ee2"},  // NV_GSP.init_boot_binary_image, ip.py:425-429
    {"ad102", "booter_unload", "nvidia/ad102/gsp", "booter_unload-570.144.bin", "975b85a14ded8e430d30f000c3c1afdd55c15dee04f35ff9dfd876acd7e67186", "d7589e039420c1ffa54ecec8126cc251"},  // nv_init_helper._booter_ucode (plan step P2)
    {"gb202", "fmc", "nvidia/gb202/gsp", "fmc-570.144.bin", "cb59a35c1d4bd1274d7267fd10243c29f843ff41c851b9cbd59f5af2ddd7fece", "a7196496b60154a0c2d222ade9529b82"},  // NV_FLCN_COT.init_fmc_image, ip.py:302-304
    {"gb202", "gsp", "nvidia/ga102/gsp", "gsp-570.144.bin", "a8c3ebeed280323aedb51c061f321e73379cce7a9ae643a33dd03915df027f7f", "fb02697830bcd6e5f04f85dce7b52579"},  // NV_GSP.init_gsp_image, ip.py:401-402
    {"gb202", "bootloader", "nvidia/gb202/gsp", "bootloader-570.144.bin", "d40b48e431d1707dc77af3605db358ed7a32ebfc2830eb74de2eddb4d3025071", "80b529973767420fd098c0f6aeeba32b"},  // NV_GSP.init_boot_binary_image, ip.py:425-429
};

} // namespace nvfw
} // namespace tinygpu_device

#endif // LIBHMSBEAGLE_GPU_TINYGPUFIRMWAREMANIFEST_H
