/*
 * TinyGPUNVBootTables.h -- GENERATED by make_tinygpu_nv_boot_tables.py from tinygrad a9830e2b4
 * (tinygrad/runtime/autogen/nv_regs, tinygrad/runtime/autogen/nv.py and tinygrad/runtime/autogen/pci.py, as
 * tinygrad/runtime/support/nv/ip.py, nvdev.py and libhmsbeagle/GPU/nv_init_helper.py use them). Do not edit. TODO.md
 * plan step C2.
 *
 * nv_regs: the boot's 45 registers and 6 MMU field groups as tinygrad's NVDev binds them after each chip's include()
 * sequence (kAdaRegs, kGB20xRegs, indexed by NVRegId; NVReg in TinyGPUNVReg.h reads and writes them), and the 4
 * register values the boot uses. pci: the config offsets it uses. nv570: NVIDIA 570.144 constants tinygrad's autogen
 * lacks, as nv_init_helper.py uses them. nv: the boot's constants and 34 structs (233 fields: VBIOS and falcon ucode,
 * FWSECLIC, firmware headers, WPR meta, libos, the message-queue framing, FSP/COT/FMC), packed at tinygrad's offsets
 * with explicit padding, anonymous unions where its offsets overlap, bitfield accessors, and its names and aliases.
 * TinyGPUNVRMTables.h has the RPC payloads and RM objects.
 *
 * include() sequences:
 *   Ada:   nv_ref, dev_fb tu102, dev_gc6_island ga102, dev_vm tu102, dev_mmu tu102, dev_gsp ga102,
 *          dev_falcon_v4 ga102, dev_riscv_pri ga102, dev_fbif_v4 ga102, dev_falcon_second_pri ga102,
 *          dev_sec_pri ga102, dev_bus tu102
 *   GB20x: nv_ref, dev_fb tu102, dev_gc6_island ga102, dev_therm gb202, dev_vm tu102, dev_mmu gh100,
 *          dev_riscv_pri ga102, dev_gsp ga102, dev_falcon_v4 gh100, dev_vm gh100, dev_fsp_pri gh100, dev_bus tu102
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUNVBOOTTABLES_H
#define LIBHMSBEAGLE_GPU_TINYGPUNVBOOTTABLES_H

#include <cstddef>
#include <cstdint>

#include "libhmsbeagle/GPU/TinyGPUNVReg.h"

namespace tinygpu_device {
namespace nv_regs {

enum NVRegId {
    NV_PMC_BOOT_0,
    NV_PMC_BOOT_42,
    NV_PFB_PRI_MMU_WPR2_ADDR_LO,
    NV_PFB_PRI_MMU_WPR2_ADDR_HI,
    NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK,
    NV_PGC6_AON_SECURE_SCRATCH_GROUP_05,
    NV_PGC6_AON_SECURE_SCRATCH_GROUP_42,
    NV_PGC6_BSI_SECURE_SCRATCH_14,
    NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE,
    NV_MMU_VER2_PDE,
    NV_MMU_VER2_DUAL_PDE,
    NV_MMU_VER2_PTE,
    NV_PGSP_FALCON_MAILBOX0,
    NV_PGSP_FALCON_MAILBOX1,
    NV_PGSP_FALCON_ENGINE,
    NV_PGSP_QUEUE_HEAD,
    NV_PFALCON_FALCON_MAILBOX0,
    NV_PFALCON_FALCON_MAILBOX1,
    NV_PFALCON_FALCON_DMACTL,
    NV_PFALCON_FALCON_DMATRFBASE,
    NV_PFALCON_FALCON_DMATRFMOFFS,
    NV_PFALCON_FALCON_DMATRFCMD,
    NV_PFALCON_FALCON_DMATRFFBOFFS,
    NV_PFALCON_FALCON_DMATRFBASE1,
    NV_PFALCON_FALCON_HWCFG2,
    NV_PFALCON_FALCON_OS,
    NV_PFALCON_FALCON_RM,
    NV_PFALCON_FALCON_CPUCTL,
    NV_PFALCON_FALCON_BOOTVEC,
    NV_PRISCV_RISCV_CPUCTL,
    NV_PRISCV_RISCV_BCR_CTRL,
    NV_PFALCON_FBIF_TRANSCFG,
    NV_PFALCON_FBIF_CTL,
    NV_PFALCON2_FALCON_MOD_SEL,
    NV_PFALCON2_FALCON_BROM_CURR_UCODE_ID,
    NV_PFALCON2_FALCON_BROM_ENGIDMASK,
    NV_PFALCON2_FALCON_BROM_PARAADDR,
    NV_PSEC_FALCON_ENGINE,
    NV_PBUS_VBIOS_SCRATCH,
    NV_PBUS_BAR1_BLOCK,
    NV_THERM_I2CS_SCRATCH,
    NV_MMU_VER3_PDE,
    NV_MMU_VER3_DUAL_PDE,
    NV_MMU_VER3_PTE,
    NV_VIRTUAL_FUNCTION_PRIV_FUNC_BAR1_BLOCK_LOW_ADDR,
    NV_PFSP_EMEMC,
    NV_PFSP_EMEMD,
    NV_PFSP_MSGQ_HEAD,
    NV_PFSP_MSGQ_TAIL,
    NV_PFSP_QUEUE_HEAD,
    NV_PFSP_QUEUE_TAIL,
    NV_REG_COUNT
};

constexpr NVField kF_nv_ref_NV_PMC_BOOT_0[] = {
    {"minor_revision", 0, 3}, {"major_revision", 4, 7}, {"architecture_1", 8, 8}, {"implementation", 20, 23},
    {"architecture_0", 24, 28}
};
constexpr NVField kF_nv_ref_NV_PMC_BOOT_42[] = {
    {"minor_extended_revision", 8, 11}, {"minor_revision", 12, 15}, {"major_revision", 16, 19},
    {"implementation", 20, 23}, {"architecture", 24, 29}, {"chip_id", 20, 29}
};
constexpr NVField kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_LO[] = {{"val", 4, 31}};
constexpr NVField kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_HI[] = {{"val", 4, 31}};
constexpr NVField kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK[] = {
    {"read_protection", 0, 3}, {"read_protection_level0", 0, 0}
};
constexpr NVField kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05[] = {
    {"priv_level_mask_read_protection", 0, 3}, {"priv_level_mask_read_protection_level0", 0, 0},
    {"0_gfw_boot_progress", 0, 7}
};
constexpr uint32_t kI_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05(uint32_t i) { return 0x00118234+(i)*4; }
constexpr NVField kF_dev_gc6_island_ga102_NV_PGC6_BSI_SECURE_SCRATCH_14[] = {{"boot_stage_3_handoff", 26, 26}};
constexpr NVField kF_dev_vm_tu102_NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE[] = {
    {"pdb_aperture", 1, 1}, {"pdb_addr", 4, 31}, {"upper_pdb_addr", 0, 19}, {"all_va", 0, 0}, {"all_pdb", 1, 1},
    {"hubtlb_only", 2, 2}, {"replay", 3, 5}, {"sys_membar", 6, 6}, {"ack", 7, 8}, {"cancel_client_id", 9, 14},
    {"cancel_gpc_id", 15, 19}, {"cancel_client_type", 20, 20}, {"use_pasid", 21, 21}, {"use_size", 22, 22},
    {"prop_flush", 23, 23}, {"cache_level", 24, 26}, {"trigger", 31, 31}
};
constexpr NVField kF_dev_mmu_tu102_NV_MMU_VER2_PDE[] = {
    {"is_pte", 0, 0}, {"is_pde", 0, 0}, {"valid", 0, 0}, {"aperture", 1, 2}, {"vol", 3, 3}, {"no_ats", 5, 5},
    {"address_sys", 8, 53}, {"address_vid", 8, 32}, {"address_vid_peer", 33, 35}
};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER2_PDE[] = {
    {"is_pte", 0, 0}, {"is_pde", 0, 0}, {"valid", 0, 0}, {"aperture", 1, 2}, {"vol", 3, 3}, {"no_ats", 5, 5},
    {"address_sys", 8, 53}, {"address_vid", 8, 32}, {"address_vid_peer", 33, 35}
};
constexpr NVField kF_dev_mmu_tu102_NV_MMU_VER2_DUAL_PDE[] = {
    {"is_pte", 0, 0}, {"is_pde", 0, 0}, {"valid", 0, 0}, {"aperture_big", 1, 2}, {"vol_big", 3, 3}, {"no_ats", 5, 5},
    {"address_big_sys", 4, 53}, {"address_big_vid", 4, 32}, {"address_big_vid_peer", 33, 35},
    {"aperture_small", 65, 66}, {"vol_small", 67, 67}, {"address_small_sys", 72, 117}, {"address_small_vid", 72, 96},
    {"address_small_vid_peer", 97, 99}
};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER2_DUAL_PDE[] = {
    {"is_pte", 0, 0}, {"is_pde", 0, 0}, {"valid", 0, 0}, {"aperture_big", 1, 2}, {"vol_big", 3, 3}, {"no_ats", 5, 5},
    {"address_big_sys", 4, 53}, {"address_big_vid", 4, 32}, {"address_big_vid_peer", 33, 35},
    {"aperture_small", 65, 66}, {"vol_small", 67, 67}, {"address_small_sys", 72, 117}, {"address_small_vid", 72, 96},
    {"address_small_vid_peer", 97, 99}
};
constexpr NVField kF_dev_mmu_tu102_NV_MMU_VER2_PTE[] = {
    {"valid", 0, 0}, {"aperture", 1, 2}, {"vol", 3, 3}, {"encrypted", 4, 4}, {"privilege", 5, 5}, {"read_only", 6, 6},
    {"atomic_disable", 7, 7}, {"address_sys", 8, 53}, {"address_vid", 8, 32}, {"address_vid_peer", 33, 35},
    {"comptagline", 36, 55}, {"kind", 56, 63}
};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER2_PTE[] = {
    {"valid", 0, 0}, {"aperture", 1, 2}, {"vol", 3, 3}, {"encrypted", 4, 4}, {"privilege", 5, 5}, {"read_only", 6, 6},
    {"atomic_disable", 7, 7}, {"address_sys", 8, 53}, {"address_vid", 8, 32}, {"address_vid_peer", 33, 35},
    {"comptagline", 36, 55}, {"kind", 56, 63}
};
constexpr NVField kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX0[] = {{"data", 0, 31}};
constexpr NVField kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX1[] = {{"data", 0, 31}};
constexpr NVField kF_dev_gsp_ga102_NV_PGSP_FALCON_ENGINE[] = {{"reset", 0, 0}};
constexpr NVField kF_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD[] = {{"address", 0, 31}};
constexpr uint32_t kI_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD(uint32_t i) { return 0x110c00+(i)*8; }
constexpr NVField kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_MAILBOX0[] = {{"data", 0, 31}};
constexpr NVField kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_MAILBOX1[] = {{"data", 0, 31}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMACTL[] = {
    {"require_ctx", 0, 0}, {"dmem_scrubbing", 1, 1}, {"imem_scrubbing", 2, 2}
};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFBASE[] = {{"base", 0, 31}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFMOFFS[] = {{"offs", 0, 23}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFCMD[] = {
    {"full", 0, 0}, {"idle", 1, 1}, {"sec", 2, 3}, {"imem", 4, 4}, {"write", 5, 5}, {"size", 8, 10}, {"ctxdma", 12, 14},
    {"set_dmtag", 16, 16}
};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFFBOFFS[] = {{"offs", 0, 31}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFBASE1[] = {{"base", 0, 8}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_HWCFG2[] = {
    {"riscv", 10, 10}, {"mem_scrubbing", 12, 12}, {"reset_ready", 31, 31}
};
constexpr NVField kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_HWCFG2[] = {
    {"sha", 0, 0}, {"bmem", 1, 1}, {"pkcboot", 2, 2}, {"dbgmode", 3, 3}, {"kmem", 4, 4}, {"hscode_revocation", 5, 5},
    {"strap_fun", 6, 6}, {"vhr", 7, 7}, {"hs", 8, 8}, {"securebus", 9, 9}, {"riscv", 10, 10},
    {"riscv_pl3_disable", 11, 11}, {"mem_scrubbing", 12, 12}, {"riscv_br_priv_lockdown", 13, 13},
    {"boot_from_hs", 14, 14}, {"riscv_br_adpair", 15, 15}, {"scp", 16, 16}, {"gdma", 17, 17}, {"se_lite", 18, 18},
    {"prgn_rsvd_fuse", 24, 31}
};
constexpr NVField kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_OS[] = {{"version", 0, 31}};
constexpr NVField kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_CPUCTL[] = {
    {"startcpu", 1, 1}, {"halted", 4, 4}, {"alias_en", 6, 6}, {"alias_startcpu", 1, 1}
};
constexpr NVField kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_CPUCTL[] = {{"active_stat", 7, 7}, {"halted", 4, 4}};
constexpr NVField kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_BCR_CTRL[] = {
    {"valid", 0, 0}, {"core_select", 4, 4}, {"brfetch", 8, 8}
};
constexpr NVField kF_dev_fbif_v4_ga102_NV_PFALCON_FBIF_TRANSCFG[] = {{"target", 0, 1}, {"mem_type", 2, 2}};
constexpr uint32_t kI_dev_fbif_v4_ga102_NV_PFALCON_FBIF_TRANSCFG(uint32_t i) { return 0x00000000+(i)*4; }
constexpr NVField kF_dev_fbif_v4_ga102_NV_PFALCON_FBIF_CTL[] = {{"allow_phys_no_ctx", 7, 7}};
constexpr NVField kF_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_MOD_SEL[] = {{"algo", 0, 7}};
constexpr NVField kF_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_BROM_CURR_UCODE_ID[] = {{"val", 0, 7}};
constexpr uint32_t kI_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_BROM_PARAADDR(uint32_t i) { return 0x00000210+(i)*4; }
constexpr NVField kF_dev_sec_pri_ga102_NV_PSEC_FALCON_ENGINE[] = {{"reset", 0, 0}};
constexpr uint32_t kI_dev_bus_tu102_NV_PBUS_VBIOS_SCRATCH(uint32_t i) { return 0x00001400+(i)*4; }
constexpr NVField kF_dev_bus_tu102_NV_PBUS_BAR1_BLOCK[] = {
    {"map", 0, 29}, {"ptr", 0, 27}, {"target", 28, 29}, {"mode", 31, 31}
};
constexpr NVField kF_dev_therm_gb202_NV_THERM_I2CS_SCRATCH[] = {{"data", 0, 31}};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER3_PDE[] = {
    {"is_pte", 0, 0}, {"valid", 0, 0}, {"aperture", 1, 2}, {"pcf", 3, 5}, {"address", 12, 51}
};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER3_DUAL_PDE[] = {
    {"is_pte", 0, 0}, {"valid", 0, 0}, {"aperture_big", 1, 2}, {"pcf_big", 3, 5}, {"address_big", 8, 51},
    {"aperture_small", 65, 66}, {"pcf_small", 67, 69}, {"address_small", 76, 115}
};
constexpr NVField kF_dev_mmu_gh100_NV_MMU_VER3_PTE[] = {
    {"valid", 0, 0}, {"aperture", 1, 2}, {"pcf", 3, 7}, {"kind", 8, 11}, {"address", 12, 51}, {"address_sys", 12, 51},
    {"address_peer", 12, 51}, {"address_vid", 12, 39}, {"peer_id", 61, 63}
};
constexpr NVField kF_dev_vm_gh100_NV_VIRTUAL_FUNCTION_PRIV_FUNC_BAR1_BLOCK_LOW_ADDR[] = {
    {"map", 10, 31}, {"bar1_pending", 0, 0}, {"bar1_outstanding", 1, 1}, {"mode", 9, 9}, {"target", 10, 11},
    {"ptr", 12, 31}
};
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_EMEMC[] = {
    {"offs", 2, 7}, {"blk", 8, 15}, {"aincw", 24, 24}, {"aincr", 25, 25}
};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_EMEMC(uint32_t i) { return 0x008F2ac0+(i)*8; }
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_EMEMD[] = {{"data", 0, 31}};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_EMEMD(uint32_t i) { return 0x008F2ac4+(i)*8; }
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_MSGQ_HEAD[] = {{"val", 0, 31}};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_MSGQ_HEAD(uint32_t i) { return 0x008F2c80+(i)*8; }
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_MSGQ_TAIL[] = {{"val", 0, 31}};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_MSGQ_TAIL(uint32_t i) { return 0x008F2c84+(i)*8; }
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_QUEUE_HEAD[] = {{"address", 0, 31}};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_QUEUE_HEAD(uint32_t i) { return 0x008F2c00+(i)*8; }
constexpr NVField kF_dev_fsp_pri_gh100_NV_PFSP_QUEUE_TAIL[] = {{"address", 0, 31}};
constexpr uint32_t kI_dev_fsp_pri_gh100_NV_PFSP_QUEUE_TAIL(uint32_t i) { return 0x008F2c04+(i)*8; }

constexpr NVRegDef kAdaRegs[NV_REG_COUNT] = {
    {"NV_PMC_BOOT_0", kReg, 0x0, 0x0, nullptr, kF_nv_ref_NV_PMC_BOOT_0, 5},  // nv_ref
    {"NV_PMC_BOOT_42", kReg, 0x0, 0xa00, nullptr, kF_nv_ref_NV_PMC_BOOT_42, 6},  // nv_ref
    {"NV_PFB_PRI_MMU_WPR2_ADDR_LO", kReg, 0x0, 0x1fa824, nullptr, kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_LO, 1},  // dev_fb tu102
    {"NV_PFB_PRI_MMU_WPR2_ADDR_HI", kReg, 0x0, 0x1fa828, nullptr, kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_HI, 1},  // dev_fb tu102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK", kReg, 0x0, 0x118128, nullptr, kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK, 2},  // dev_gc6_island ga102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_05", kReg, 0x0, 0x0, kI_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05, kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05, 3},  // dev_gc6_island ga102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_42", kReg, 0x0, 0x1183a4, nullptr, nullptr, 0},  // dev_gc6_island ga102
    {"NV_PGC6_BSI_SECURE_SCRATCH_14", kReg, 0x0, 0x1180f8, nullptr, kF_dev_gc6_island_ga102_NV_PGC6_BSI_SECURE_SCRATCH_14, 1},  // dev_gc6_island ga102
    {"NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE", kReg, 0xb80000, 0x30b0, nullptr, kF_dev_vm_tu102_NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE, 17},  // dev_vm tu102
    {"NV_MMU_VER2_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_tu102_NV_MMU_VER2_PDE, 9},  // dev_mmu tu102
    {"NV_MMU_VER2_DUAL_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_tu102_NV_MMU_VER2_DUAL_PDE, 14},  // dev_mmu tu102
    {"NV_MMU_VER2_PTE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_tu102_NV_MMU_VER2_PTE, 12},  // dev_mmu tu102
    {"NV_PGSP_FALCON_MAILBOX0", kReg, 0x0, 0x110040, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX0, 1},  // dev_gsp ga102
    {"NV_PGSP_FALCON_MAILBOX1", kReg, 0x0, 0x110044, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX1, 1},  // dev_gsp ga102
    {"NV_PGSP_FALCON_ENGINE", kReg, 0x0, 0x1103c0, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_ENGINE, 1},  // dev_gsp ga102
    {"NV_PGSP_QUEUE_HEAD", kReg, 0x0, 0x0, kI_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD, kF_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD, 1},  // dev_gsp ga102
    {"NV_PFALCON_FALCON_MAILBOX0", kReg, 0x0, 0x40, nullptr, nullptr, 0},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_MAILBOX1", kReg, 0x0, 0x44, nullptr, nullptr, 0},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMACTL", kReg, 0x0, 0x10c, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMACTL, 3},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMATRFBASE", kReg, 0x0, 0x110, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFBASE, 1},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMATRFMOFFS", kReg, 0x0, 0x114, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFMOFFS, 1},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMATRFCMD", kReg, 0x0, 0x118, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFCMD, 8},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMATRFFBOFFS", kReg, 0x0, 0x11c, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFFBOFFS, 1},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_DMATRFBASE1", kReg, 0x0, 0x128, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_DMATRFBASE1, 1},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_HWCFG2", kReg, 0x0, 0xf4, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_HWCFG2, 3},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_OS", kReg, 0x0, 0x80, nullptr, nullptr, 0},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_RM", kReg, 0x0, 0x84, nullptr, nullptr, 0},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_CPUCTL", kReg, 0x0, 0x100, nullptr, kF_dev_falcon_v4_ga102_NV_PFALCON_FALCON_CPUCTL, 4},  // dev_falcon_v4 ga102
    {"NV_PFALCON_FALCON_BOOTVEC", kReg, 0x0, 0x104, nullptr, nullptr, 0},  // dev_falcon_v4 ga102
    {"NV_PRISCV_RISCV_CPUCTL", kReg, 0x1000, 0x388, nullptr, kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_CPUCTL, 2},  // dev_riscv_pri ga102
    {"NV_PRISCV_RISCV_BCR_CTRL", kReg, 0x1000, 0x668, nullptr, kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_BCR_CTRL, 3},  // dev_riscv_pri ga102
    {"NV_PFALCON_FBIF_TRANSCFG", kReg, 0x600, 0x0, kI_dev_fbif_v4_ga102_NV_PFALCON_FBIF_TRANSCFG, kF_dev_fbif_v4_ga102_NV_PFALCON_FBIF_TRANSCFG, 2},  // dev_fbif_v4 ga102
    {"NV_PFALCON_FBIF_CTL", kReg, 0x600, 0x24, nullptr, kF_dev_fbif_v4_ga102_NV_PFALCON_FBIF_CTL, 1},  // dev_fbif_v4 ga102
    {"NV_PFALCON2_FALCON_MOD_SEL", kReg, 0x1000, 0x180, nullptr, kF_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_MOD_SEL, 1},  // dev_falcon_second_pri ga102
    {"NV_PFALCON2_FALCON_BROM_CURR_UCODE_ID", kReg, 0x1000, 0x198, nullptr, kF_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_BROM_CURR_UCODE_ID, 1},  // dev_falcon_second_pri ga102
    {"NV_PFALCON2_FALCON_BROM_ENGIDMASK", kReg, 0x1000, 0x19c, nullptr, nullptr, 0},  // dev_falcon_second_pri ga102
    {"NV_PFALCON2_FALCON_BROM_PARAADDR", kReg, 0x1000, 0x0, kI_dev_falcon_second_pri_ga102_NV_PFALCON2_FALCON_BROM_PARAADDR, nullptr, 0},  // dev_falcon_second_pri ga102
    {"NV_PSEC_FALCON_ENGINE", kReg, 0x0, 0x8403c0, nullptr, kF_dev_sec_pri_ga102_NV_PSEC_FALCON_ENGINE, 1},  // dev_sec_pri ga102
    {"NV_PBUS_VBIOS_SCRATCH", kReg, 0x0, 0x0, kI_dev_bus_tu102_NV_PBUS_VBIOS_SCRATCH, nullptr, 0},  // dev_bus tu102
    {"NV_PBUS_BAR1_BLOCK", kReg, 0x0, 0x1704, nullptr, kF_dev_bus_tu102_NV_PBUS_BAR1_BLOCK, 4},  // dev_bus tu102
    {"NV_THERM_I2CS_SCRATCH", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_MMU_VER3_PDE", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_MMU_VER3_DUAL_PDE", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_MMU_VER3_PTE", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_VIRTUAL_FUNCTION_PRIV_FUNC_BAR1_BLOCK_LOW_ADDR", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_EMEMC", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_EMEMD", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_MSGQ_HEAD", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_MSGQ_TAIL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_QUEUE_HEAD", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFSP_QUEUE_TAIL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
};

constexpr NVRegDef kGB20xRegs[NV_REG_COUNT] = {
    {"NV_PMC_BOOT_0", kReg, 0x0, 0x0, nullptr, kF_nv_ref_NV_PMC_BOOT_0, 5},  // nv_ref
    {"NV_PMC_BOOT_42", kReg, 0x0, 0xa00, nullptr, kF_nv_ref_NV_PMC_BOOT_42, 6},  // nv_ref
    {"NV_PFB_PRI_MMU_WPR2_ADDR_LO", kReg, 0x0, 0x1fa824, nullptr, kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_LO, 1},  // dev_fb tu102
    {"NV_PFB_PRI_MMU_WPR2_ADDR_HI", kReg, 0x0, 0x1fa828, nullptr, kF_dev_fb_tu102_NV_PFB_PRI_MMU_WPR2_ADDR_HI, 1},  // dev_fb tu102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK", kReg, 0x0, 0x118128, nullptr, kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05_PRIV_LEVEL_MASK, 2},  // dev_gc6_island ga102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_05", kReg, 0x0, 0x0, kI_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05, kF_dev_gc6_island_ga102_NV_PGC6_AON_SECURE_SCRATCH_GROUP_05, 3},  // dev_gc6_island ga102
    {"NV_PGC6_AON_SECURE_SCRATCH_GROUP_42", kReg, 0x0, 0x1183a4, nullptr, nullptr, 0},  // dev_gc6_island ga102
    {"NV_PGC6_BSI_SECURE_SCRATCH_14", kReg, 0x0, 0x1180f8, nullptr, kF_dev_gc6_island_ga102_NV_PGC6_BSI_SECURE_SCRATCH_14, 1},  // dev_gc6_island ga102
    {"NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE", kReg, 0xb80000, 0x30b0, nullptr, kF_dev_vm_tu102_NV_VIRTUAL_FUNCTION_PRIV_MMU_INVALIDATE, 17},  // dev_vm tu102
    {"NV_MMU_VER2_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER2_PDE, 9},  // dev_mmu gh100
    {"NV_MMU_VER2_DUAL_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER2_DUAL_PDE, 14},  // dev_mmu gh100
    {"NV_MMU_VER2_PTE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER2_PTE, 12},  // dev_mmu gh100
    {"NV_PGSP_FALCON_MAILBOX0", kReg, 0x0, 0x110040, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX0, 1},  // dev_gsp ga102
    {"NV_PGSP_FALCON_MAILBOX1", kReg, 0x0, 0x110044, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_MAILBOX1, 1},  // dev_gsp ga102
    {"NV_PGSP_FALCON_ENGINE", kReg, 0x0, 0x1103c0, nullptr, kF_dev_gsp_ga102_NV_PGSP_FALCON_ENGINE, 1},  // dev_gsp ga102
    {"NV_PGSP_QUEUE_HEAD", kReg, 0x0, 0x0, kI_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD, kF_dev_gsp_ga102_NV_PGSP_QUEUE_HEAD, 1},  // dev_gsp ga102
    {"NV_PFALCON_FALCON_MAILBOX0", kReg, 0x0, 0x40, nullptr, kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_MAILBOX0, 1},  // dev_falcon_v4 gh100
    {"NV_PFALCON_FALCON_MAILBOX1", kReg, 0x0, 0x44, nullptr, kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_MAILBOX1, 1},  // dev_falcon_v4 gh100
    {"NV_PFALCON_FALCON_DMACTL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_DMATRFBASE", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_DMATRFMOFFS", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_DMATRFCMD", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_DMATRFFBOFFS", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_DMATRFBASE1", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_HWCFG2", kReg, 0x0, 0xf4, nullptr, kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_HWCFG2, 20},  // dev_falcon_v4 gh100
    {"NV_PFALCON_FALCON_OS", kReg, 0x0, 0x80, nullptr, kF_dev_falcon_v4_gh100_NV_PFALCON_FALCON_OS, 1},  // dev_falcon_v4 gh100
    {"NV_PFALCON_FALCON_RM", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_CPUCTL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FALCON_BOOTVEC", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PRISCV_RISCV_CPUCTL", kReg, 0x1000, 0x388, nullptr, kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_CPUCTL, 2},  // dev_riscv_pri ga102
    {"NV_PRISCV_RISCV_BCR_CTRL", kReg, 0x1000, 0x668, nullptr, kF_dev_riscv_pri_ga102_NV_PRISCV_RISCV_BCR_CTRL, 3},  // dev_riscv_pri ga102
    {"NV_PFALCON_FBIF_TRANSCFG", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON_FBIF_CTL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON2_FALCON_MOD_SEL", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON2_FALCON_BROM_CURR_UCODE_ID", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON2_FALCON_BROM_ENGIDMASK", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PFALCON2_FALCON_BROM_PARAADDR", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PSEC_FALCON_ENGINE", kAbsent, 0x0, 0x0, nullptr, nullptr, 0},
    {"NV_PBUS_VBIOS_SCRATCH", kReg, 0x0, 0x0, kI_dev_bus_tu102_NV_PBUS_VBIOS_SCRATCH, nullptr, 0},  // dev_bus tu102
    {"NV_PBUS_BAR1_BLOCK", kReg, 0x0, 0x1704, nullptr, kF_dev_bus_tu102_NV_PBUS_BAR1_BLOCK, 4},  // dev_bus tu102
    {"NV_THERM_I2CS_SCRATCH", kReg, 0x0, 0xad00bc, nullptr, kF_dev_therm_gb202_NV_THERM_I2CS_SCRATCH, 1},  // dev_therm gb202
    {"NV_MMU_VER3_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER3_PDE, 5},  // dev_mmu gh100
    {"NV_MMU_VER3_DUAL_PDE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER3_DUAL_PDE, 8},  // dev_mmu gh100
    {"NV_MMU_VER3_PTE", kGroup, 0x0, 0x0, nullptr, kF_dev_mmu_gh100_NV_MMU_VER3_PTE, 9},  // dev_mmu gh100
    {"NV_VIRTUAL_FUNCTION_PRIV_FUNC_BAR1_BLOCK_LOW_ADDR", kReg, 0xb80000, 0xf60, nullptr, kF_dev_vm_gh100_NV_VIRTUAL_FUNCTION_PRIV_FUNC_BAR1_BLOCK_LOW_ADDR, 6},  // dev_vm gh100
    {"NV_PFSP_EMEMC", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_EMEMC, kF_dev_fsp_pri_gh100_NV_PFSP_EMEMC, 4},  // dev_fsp_pri gh100
    {"NV_PFSP_EMEMD", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_EMEMD, kF_dev_fsp_pri_gh100_NV_PFSP_EMEMD, 1},  // dev_fsp_pri gh100
    {"NV_PFSP_MSGQ_HEAD", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_MSGQ_HEAD, kF_dev_fsp_pri_gh100_NV_PFSP_MSGQ_HEAD, 1},  // dev_fsp_pri gh100
    {"NV_PFSP_MSGQ_TAIL", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_MSGQ_TAIL, kF_dev_fsp_pri_gh100_NV_PFSP_MSGQ_TAIL, 1},  // dev_fsp_pri gh100
    {"NV_PFSP_QUEUE_HEAD", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_QUEUE_HEAD, kF_dev_fsp_pri_gh100_NV_PFSP_QUEUE_HEAD, 1},  // dev_fsp_pri gh100
    {"NV_PFSP_QUEUE_TAIL", kReg, 0x0, 0x0, kI_dev_fsp_pri_gh100_NV_PFSP_QUEUE_TAIL, kF_dev_fsp_pri_gh100_NV_PFSP_QUEUE_TAIL, 1},  // dev_fsp_pri gh100
};

// register values the boot uses
constexpr uint32_t NV_PFALCON_FALCON_DMATRFCMD_SIZE_256B = 0x6;  // dev_falcon_v4 ga102, on Ada
constexpr uint32_t NV_PFALCON_FALCON_CPUCTL_ALIAS = 0x130;  // dev_falcon_v4 ga102, on Ada
constexpr uint32_t NV_PFALCON_FBIF_TRANSCFG_MEM_TYPE_PHYSICAL = 0x1;  // dev_fbif_v4 ga102, on Ada
constexpr uint32_t NV_PFALCON2_FALCON_MOD_SEL_ALGO_RSA3K = 0x1;  // dev_falcon_second_pri ga102, on Ada

} // namespace nv_regs

namespace pci {
constexpr uint32_t PCI_COMMAND = 0x4;
constexpr uint32_t PCI_COMMAND_MASTER = 0x4;
constexpr uint32_t PCI_REVISION_ID = 0x8;
constexpr uint32_t PCI_SUBSYSTEM_VENDOR_ID = 0x2c;
constexpr uint32_t PCI_VENDOR_ID = 0x0;
} // namespace pci

namespace nv570 {
// open-gpu-kernel-modules 570.144, src/nvidia/src/kernel/gpu/gsp/arch/turing/kernel_gsp_frts_tu102.c; nv_init_helper.py's names in parentheses
constexpr uint32_t FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3_CMD_FRTS = 0x15;  // kernel_gsp_frts_tu102.c:101 (_FWSEC_CMD_FRTS; ip.py:169 passes 0x15)
constexpr uint32_t FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3_CMD_SB = 0x19;  // kernel_gsp_frts_tu102.c:102 (_FWSEC_CMD_SB)
constexpr uint32_t NV_VBIOS_FWSECLIC_SCRATCH_INDEX_0E = 0xe;  // kernel_gsp_frts_tu102.c:133, an NV_PBUS_VBIOS_SCRATCH index (_SCRATCH_FRTS_ERR)
constexpr nv_regs::NVField NV_VBIOS_FWSECLIC_FRTS_ERR_CODE = {"NV_VBIOS_FWSECLIC_FRTS_ERR_CODE", 16, 31};  // 31:16, kernel_gsp_frts_tu102.c:134 (scratch >> 16)
constexpr uint32_t NV_VBIOS_FWSECLIC_SCRATCH_INDEX_15 = 0x15;  // kernel_gsp_frts_tu102.c:137 (_SCRATCH_SB_ERR)
constexpr nv_regs::NVField NV_VBIOS_FWSECLIC_SB_ERR_CODE = {"NV_VBIOS_FWSECLIC_SB_ERR_CODE", 0, 15};  // 15:0, kernel_gsp_frts_tu102.c:138 (scratch & 0xffff)
} // namespace nv570

namespace nv {
constexpr uint32_t BIT_DATA_FALCON_DATA_V2_SIZE_4 = 0x4;
constexpr uint32_t BIT_TOKEN_FALCON_DATA = 0x70;
constexpr uint32_t FALCON_APPLICATION_INTERFACE_ENTRY_ID_DMEMMAPPER = 0x4;
constexpr uint32_t FALCON_UCODE_DESC_V3_SIZE_44 = 0x2c;
constexpr uint32_t FALCON_UCODE_ENTRY_APPID_FWSEC_PROD = 0x85;
constexpr uint32_t GSP_DMA_TARGET_COHERENT_SYSTEM = 0x1;
constexpr uint64_t GSP_FW_WPR_META_MAGIC = 0xdc3aae21371a60b3;
constexpr uint32_t GSP_FW_WPR_META_REVISION = 0x1;
constexpr uint32_t LIBOS_MEMORY_REGION_CONTIGUOUS = 0x1;
constexpr uint32_t LIBOS_MEMORY_REGION_LOC_SYSMEM = 0x1;
constexpr uint32_t LIBOS_MEMORY_REGION_RADIX_PAGE_LOG2 = 0xc;
constexpr uint32_t NVDM_TYPE_COT = 0x14;
constexpr uint32_t NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_BASE = 0x0;
constexpr uint32_t NV_BCRT_HASH_INFO_BASE_CODE_TYPE_VBIOS_EXT = 0xe0;
constexpr uint32_t OFFSETOF_PCI_DATA_STRUCT_CODE_TYPE = 0x14;
constexpr uint32_t OFFSETOF_PCI_DATA_STRUCT_IMAGE_LEN = 0x10;
constexpr uint32_t OFFSETOF_PCI_EXP_ROM_PCI_DATA_STRUCT_PTR = 0x18;
constexpr uint32_t PCI_ROM_IMAGE_BLOCK_SIZE = 0x200;

#pragma pack(push, 1)

struct BIT_DATA_FALCON_DATA_V2 {  // nv.py:4558
    uint32_t FalconUcodeTablePtr;
};
static_assert(sizeof(BIT_DATA_FALCON_DATA_V2) == 4);
static_assert(offsetof(BIT_DATA_FALCON_DATA_V2, FalconUcodeTablePtr) == 0);

struct struct_BIT_HEADER_V1_00 {  // nv.py:4531
    uint16_t Id;
    uint32_t Signature;
    uint16_t BCD_Version;
    uint8_t HeaderSize;
    uint8_t TokenSize;
    uint8_t TokenEntries;
    uint8_t HeaderChksum;
};
static_assert(sizeof(struct_BIT_HEADER_V1_00) == 12);
static_assert(offsetof(struct_BIT_HEADER_V1_00, Id) == 0);
static_assert(offsetof(struct_BIT_HEADER_V1_00, Signature) == 2);
static_assert(offsetof(struct_BIT_HEADER_V1_00, BCD_Version) == 6);
static_assert(offsetof(struct_BIT_HEADER_V1_00, HeaderSize) == 8);
static_assert(offsetof(struct_BIT_HEADER_V1_00, TokenSize) == 9);
static_assert(offsetof(struct_BIT_HEADER_V1_00, TokenEntries) == 10);
static_assert(offsetof(struct_BIT_HEADER_V1_00, HeaderChksum) == 11);
using BIT_HEADER_V1_00 = struct_BIT_HEADER_V1_00;

struct struct_BIT_TOKEN_V1_00 {  // nv.py:4543
    uint8_t TokenId;
    uint8_t DataVersion;
    uint16_t DataSize;
    uint32_t DataPtr;
};
static_assert(sizeof(struct_BIT_TOKEN_V1_00) == 8);
static_assert(offsetof(struct_BIT_TOKEN_V1_00, TokenId) == 0);
static_assert(offsetof(struct_BIT_TOKEN_V1_00, DataVersion) == 1);
static_assert(offsetof(struct_BIT_TOKEN_V1_00, DataSize) == 2);
static_assert(offsetof(struct_BIT_TOKEN_V1_00, DataPtr) == 4);
using BIT_TOKEN_V1_00 = struct_BIT_TOKEN_V1_00;

struct FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3 {  // nv.py:4510
    uint32_t signature;
    uint16_t version;
    uint16_t size;
    uint32_t cmd_in_buffer_offset;
    uint32_t cmd_in_buffer_size;
    uint32_t cmd_out_buffer_offset;
    uint32_t cmd_out_buffer_size;
    uint32_t nvf_img_data_buffer_offset;
    uint32_t nvf_img_data_buffer_size;
    uint32_t printfBufferHdr;
    uint32_t ucode_build_time_stamp;
    uint32_t ucode_signature;
    uint32_t init_cmd;
    uint32_t ucode_feature;
    uint32_t ucode_cmd_mask0;
    uint32_t ucode_cmd_mask1;
    uint32_t multiTgtTbl;
};
static_assert(sizeof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3) == 64);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, signature) == 0);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, version) == 4);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, size) == 6);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, cmd_in_buffer_offset) == 8);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, cmd_in_buffer_size) == 12);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, cmd_out_buffer_offset) == 16);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, cmd_out_buffer_size) == 20);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, nvf_img_data_buffer_offset) == 24);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, nvf_img_data_buffer_size) == 28);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, printfBufferHdr) == 32);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, ucode_build_time_stamp) == 36);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, ucode_signature) == 40);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, init_cmd) == 44);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, ucode_feature) == 48);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, ucode_cmd_mask0) == 52);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, ucode_cmd_mask1) == 56);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_DMEM_MAPPER_V3, multiTgtTbl) == 60);

struct FALCON_APPLICATION_INTERFACE_ENTRY_V1 {  // nv.py:4504
    uint32_t id;
    uint32_t dmemOffset;
};
static_assert(sizeof(FALCON_APPLICATION_INTERFACE_ENTRY_V1) == 8);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_ENTRY_V1, id) == 0);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_ENTRY_V1, dmemOffset) == 4);

struct FALCON_APPLICATION_INTERFACE_HEADER_V1 {  // nv.py:4496
    uint8_t version;
    uint8_t headerSize;
    uint8_t entrySize;
    uint8_t entryCount;
};
static_assert(sizeof(FALCON_APPLICATION_INTERFACE_HEADER_V1) == 4);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_HEADER_V1, version) == 0);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_HEADER_V1, headerSize) == 1);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_HEADER_V1, entrySize) == 2);
static_assert(offsetof(FALCON_APPLICATION_INTERFACE_HEADER_V1, entryCount) == 3);

struct FALCON_UCODE_DESC_HEADER {  // nv.py:4580
    uint32_t vDesc;
};
static_assert(sizeof(FALCON_UCODE_DESC_HEADER) == 4);
static_assert(offsetof(FALCON_UCODE_DESC_HEADER, vDesc) == 0);

struct FALCON_UCODE_DESC_V3 {  // nv.py:4585
    FALCON_UCODE_DESC_HEADER Hdr;
    uint32_t StoredSize;
    uint32_t PKCDataOffset;
    uint32_t InterfaceOffset;
    uint32_t IMEMPhysBase;
    uint32_t IMEMLoadSize;
    uint32_t IMEMVirtBase;
    uint32_t DMEMPhysBase;
    uint32_t DMEMLoadSize;
    uint16_t EngineIdMask;
    uint8_t UcodeId;
    uint8_t SignatureCount;
    uint16_t SignatureVersions;
    uint16_t Reserved;
};
static_assert(sizeof(FALCON_UCODE_DESC_V3) == 44);
static_assert(offsetof(FALCON_UCODE_DESC_V3, Hdr) == 0);
static_assert(offsetof(FALCON_UCODE_DESC_V3, StoredSize) == 4);
static_assert(offsetof(FALCON_UCODE_DESC_V3, PKCDataOffset) == 8);
static_assert(offsetof(FALCON_UCODE_DESC_V3, InterfaceOffset) == 12);
static_assert(offsetof(FALCON_UCODE_DESC_V3, IMEMPhysBase) == 16);
static_assert(offsetof(FALCON_UCODE_DESC_V3, IMEMLoadSize) == 20);
static_assert(offsetof(FALCON_UCODE_DESC_V3, IMEMVirtBase) == 24);
static_assert(offsetof(FALCON_UCODE_DESC_V3, DMEMPhysBase) == 28);
static_assert(offsetof(FALCON_UCODE_DESC_V3, DMEMLoadSize) == 32);
static_assert(offsetof(FALCON_UCODE_DESC_V3, EngineIdMask) == 36);
static_assert(offsetof(FALCON_UCODE_DESC_V3, UcodeId) == 38);
static_assert(offsetof(FALCON_UCODE_DESC_V3, SignatureCount) == 39);
static_assert(offsetof(FALCON_UCODE_DESC_V3, SignatureVersions) == 40);
static_assert(offsetof(FALCON_UCODE_DESC_V3, Reserved) == 42);

struct FALCON_UCODE_TABLE_ENTRY_V1 {  // nv.py:4573
    uint8_t ApplicationID;
    uint8_t TargetID;
    uint32_t DescPtr;
};
static_assert(sizeof(FALCON_UCODE_TABLE_ENTRY_V1) == 6);
static_assert(offsetof(FALCON_UCODE_TABLE_ENTRY_V1, ApplicationID) == 0);
static_assert(offsetof(FALCON_UCODE_TABLE_ENTRY_V1, TargetID) == 1);
static_assert(offsetof(FALCON_UCODE_TABLE_ENTRY_V1, DescPtr) == 2);

struct FALCON_UCODE_TABLE_HDR_V1 {  // nv.py:4563
    uint8_t Version;
    uint8_t HeaderSize;
    uint8_t EntrySize;
    uint8_t EntryCount;
    uint8_t DescVersion;
    uint8_t DescSize;
};
static_assert(sizeof(FALCON_UCODE_TABLE_HDR_V1) == 6);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, Version) == 0);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, HeaderSize) == 1);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, EntrySize) == 2);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, EntryCount) == 3);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, DescVersion) == 4);
static_assert(offsetof(FALCON_UCODE_TABLE_HDR_V1, DescSize) == 5);

struct FWSECLIC_READ_VBIOS_DESC {  // nv.py:4603
    uint32_t version;
    uint32_t size;
    uint64_t gfwImageOffset;
    uint32_t gfwImageSize;
    uint32_t flags;
};
static_assert(sizeof(FWSECLIC_READ_VBIOS_DESC) == 24);
static_assert(offsetof(FWSECLIC_READ_VBIOS_DESC, version) == 0);
static_assert(offsetof(FWSECLIC_READ_VBIOS_DESC, size) == 4);
static_assert(offsetof(FWSECLIC_READ_VBIOS_DESC, gfwImageOffset) == 8);
static_assert(offsetof(FWSECLIC_READ_VBIOS_DESC, gfwImageSize) == 16);
static_assert(offsetof(FWSECLIC_READ_VBIOS_DESC, flags) == 20);

struct FWSECLIC_FRTS_REGION_DESC {  // nv.py:4612
    uint32_t version;
    uint32_t size;
    uint32_t frtsRegionOffset4K;
    uint32_t frtsRegionSize;
    uint32_t frtsRegionMediaType;
};
static_assert(sizeof(FWSECLIC_FRTS_REGION_DESC) == 20);
static_assert(offsetof(FWSECLIC_FRTS_REGION_DESC, version) == 0);
static_assert(offsetof(FWSECLIC_FRTS_REGION_DESC, size) == 4);
static_assert(offsetof(FWSECLIC_FRTS_REGION_DESC, frtsRegionOffset4K) == 8);
static_assert(offsetof(FWSECLIC_FRTS_REGION_DESC, frtsRegionSize) == 12);
static_assert(offsetof(FWSECLIC_FRTS_REGION_DESC, frtsRegionMediaType) == 16);

struct FWSECLIC_FRTS_CMD {  // nv.py:4621
    FWSECLIC_READ_VBIOS_DESC readVbiosDesc;
    FWSECLIC_FRTS_REGION_DESC frtsRegionDesc;
};
static_assert(sizeof(FWSECLIC_FRTS_CMD) == 44);
static_assert(offsetof(FWSECLIC_FRTS_CMD, readVbiosDesc) == 0);
static_assert(offsetof(FWSECLIC_FRTS_CMD, frtsRegionDesc) == 24);

struct struct_GSP_ACR_BOOT_GSP_RM_PARAMS {  // nv.py:72
    uint32_t target;
    uint32_t gspRmDescSize;
    uint64_t gspRmDescOffset;
    uint64_t wprCarveoutOffset;
    uint32_t wprCarveoutSize;
    uint8_t bIsGspRmBoot;
    uint8_t _pad0[3];
};
static_assert(sizeof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS) == 32);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, target) == 0);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, gspRmDescSize) == 4);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, gspRmDescOffset) == 8);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, wprCarveoutOffset) == 16);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, wprCarveoutSize) == 24);
static_assert(offsetof(struct_GSP_ACR_BOOT_GSP_RM_PARAMS, bIsGspRmBoot) == 28);
using GSP_ACR_BOOT_GSP_RM_PARAMS = struct_GSP_ACR_BOOT_GSP_RM_PARAMS;

struct MESSAGE_QUEUE_INIT_ARGUMENTS {  // nv.py:33
    uint64_t sharedMemPhysAddr;
    uint32_t pageTableEntryCount;
    uint8_t _pad0[4];
    uint64_t cmdQueueOffset;
    uint64_t statQueueOffset;
};
static_assert(sizeof(MESSAGE_QUEUE_INIT_ARGUMENTS) == 32);
static_assert(offsetof(MESSAGE_QUEUE_INIT_ARGUMENTS, sharedMemPhysAddr) == 0);
static_assert(offsetof(MESSAGE_QUEUE_INIT_ARGUMENTS, pageTableEntryCount) == 8);
static_assert(offsetof(MESSAGE_QUEUE_INIT_ARGUMENTS, cmdQueueOffset) == 16);
static_assert(offsetof(MESSAGE_QUEUE_INIT_ARGUMENTS, statQueueOffset) == 24);

struct GSP_SR_INIT_ARGUMENTS {  // nv.py:42
    uint32_t oldLevel;
    uint32_t flags;
    uint8_t bInPMTransition;
    uint8_t _pad0[3];
};
static_assert(sizeof(GSP_SR_INIT_ARGUMENTS) == 12);
static_assert(offsetof(GSP_SR_INIT_ARGUMENTS, oldLevel) == 0);
static_assert(offsetof(GSP_SR_INIT_ARGUMENTS, flags) == 4);
static_assert(offsetof(GSP_SR_INIT_ARGUMENTS, bInPMTransition) == 8);

struct GSP_ARGUMENTS_CACHED_profilerArgs {  // nv.py:58
    uint64_t pa;
    uint64_t size;
};
static_assert(sizeof(GSP_ARGUMENTS_CACHED_profilerArgs) == 16);
static_assert(offsetof(GSP_ARGUMENTS_CACHED_profilerArgs, pa) == 0);
static_assert(offsetof(GSP_ARGUMENTS_CACHED_profilerArgs, size) == 8);

struct GSP_ARGUMENTS_CACHED {  // nv.py:50
    MESSAGE_QUEUE_INIT_ARGUMENTS messageQueueInitArguments;
    GSP_SR_INIT_ARGUMENTS srInitArguments;
    uint32_t gpuInstance;
    uint8_t bDmemStack;
    uint8_t _pad0[7];
    GSP_ARGUMENTS_CACHED_profilerArgs profilerArgs;
};
static_assert(sizeof(GSP_ARGUMENTS_CACHED) == 72);
static_assert(offsetof(GSP_ARGUMENTS_CACHED, messageQueueInitArguments) == 0);
static_assert(offsetof(GSP_ARGUMENTS_CACHED, srInitArguments) == 32);
static_assert(offsetof(GSP_ARGUMENTS_CACHED, gpuInstance) == 44);
static_assert(offsetof(GSP_ARGUMENTS_CACHED, bDmemStack) == 48);
static_assert(offsetof(GSP_ARGUMENTS_CACHED, profilerArgs) == 56);

struct struct_GSP_FMC_INIT_PARAMS {  // nv.py:66
    uint32_t regkeys;
};
static_assert(sizeof(struct_GSP_FMC_INIT_PARAMS) == 4);
static_assert(offsetof(struct_GSP_FMC_INIT_PARAMS, regkeys) == 0);
using GSP_FMC_INIT_PARAMS = struct_GSP_FMC_INIT_PARAMS;

struct struct_GSP_RM_PARAMS {  // nv.py:83
    uint32_t target;
    uint8_t _pad0[4];
    uint64_t bootArgsOffset;
};
static_assert(sizeof(struct_GSP_RM_PARAMS) == 16);
static_assert(offsetof(struct_GSP_RM_PARAMS, target) == 0);
static_assert(offsetof(struct_GSP_RM_PARAMS, bootArgsOffset) == 8);
using GSP_RM_PARAMS = struct_GSP_RM_PARAMS;

struct struct_GSP_SPDM_PARAMS {  // nv.py:90
    uint32_t target;
    uint8_t _pad0[4];
    uint64_t payloadBufferOffset;
    uint32_t payloadBufferSize;
    uint8_t _pad1[4];
};
static_assert(sizeof(struct_GSP_SPDM_PARAMS) == 24);
static_assert(offsetof(struct_GSP_SPDM_PARAMS, target) == 0);
static_assert(offsetof(struct_GSP_SPDM_PARAMS, payloadBufferOffset) == 8);
static_assert(offsetof(struct_GSP_SPDM_PARAMS, payloadBufferSize) == 16);
using GSP_SPDM_PARAMS = struct_GSP_SPDM_PARAMS;

struct struct_GSP_FMC_BOOT_PARAMS {  // nv.py:98
    struct_GSP_FMC_INIT_PARAMS initParams;
    uint8_t _pad0[4];
    struct_GSP_ACR_BOOT_GSP_RM_PARAMS bootGspRmParams;
    struct_GSP_RM_PARAMS gspRmParams;
    struct_GSP_SPDM_PARAMS gspSpdmParams;
};
static_assert(sizeof(struct_GSP_FMC_BOOT_PARAMS) == 80);
static_assert(offsetof(struct_GSP_FMC_BOOT_PARAMS, initParams) == 0);
static_assert(offsetof(struct_GSP_FMC_BOOT_PARAMS, bootGspRmParams) == 8);
static_assert(offsetof(struct_GSP_FMC_BOOT_PARAMS, gspRmParams) == 40);
static_assert(offsetof(struct_GSP_FMC_BOOT_PARAMS, gspSpdmParams) == 56);
using GSP_FMC_BOOT_PARAMS = struct_GSP_FMC_BOOT_PARAMS;

struct struct_GSP_MSG_QUEUE_ELEMENT {  // nv.py:4149
    uint8_t authTagBuffer[16];
    uint8_t aadBuffer[16];
    uint32_t checkSum;
    uint32_t seqNum;
    uint32_t elemCount;
    uint32_t padding;
};
static_assert(sizeof(struct_GSP_MSG_QUEUE_ELEMENT) == 48);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, authTagBuffer) == 0);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, aadBuffer) == 16);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, checkSum) == 32);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, seqNum) == 36);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, elemCount) == 40);
static_assert(offsetof(struct_GSP_MSG_QUEUE_ELEMENT, padding) == 44);
using GSP_MSG_QUEUE_ELEMENT = struct_GSP_MSG_QUEUE_ELEMENT;

struct GspFwWprMeta {  // nv.py:107
    uint64_t magic;
    uint64_t revision;
    uint64_t sysmemAddrOfRadix3Elf;
    uint64_t sizeOfRadix3Elf;
    uint64_t sysmemAddrOfBootloader;
    uint64_t sizeOfBootloader;
    uint64_t bootloaderCodeOffset;
    uint64_t bootloaderDataOffset;
    uint64_t bootloaderManifestOffset;
    union {
        struct {
            uint64_t sysmemAddrOfSignature;
            uint64_t sizeOfSignature;
        };
        struct {
            uint32_t gspFwHeapFreeListWprOffset;
            uint32_t unused0;
            uint64_t unused1;
        };
    };
    uint64_t gspFwRsvdStart;
    uint64_t nonWprHeapOffset;
    uint64_t nonWprHeapSize;
    uint64_t gspFwWprStart;
    uint64_t gspFwHeapOffset;
    uint64_t gspFwHeapSize;
    uint64_t gspFwOffset;
    uint64_t bootBinOffset;
    uint64_t frtsOffset;
    uint64_t frtsSize;
    uint64_t gspFwWprEnd;
    uint64_t fbSize;
    uint64_t vgaWorkspaceOffset;
    uint64_t vgaWorkspaceSize;
    uint64_t bootCount;
    union {
        struct {
            uint64_t partitionRpcAddr;
            uint16_t partitionRpcRequestOffset;
            uint16_t partitionRpcReplyOffset;
            uint32_t elfCodeOffset;
            uint32_t elfDataOffset;
            uint32_t elfCodeSize;
            uint32_t elfDataSize;
            uint32_t lsUcodeVersion;
        };
        struct {
            uint32_t partitionRpcPadding[4];
            uint64_t sysmemAddrOfCrashReportQueue;
            uint32_t sizeOfCrashReportQueue;
            uint32_t lsUcodeVersionPadding[1];
        };
    };
    uint8_t gspFwHeapVfPartitionCount;
    uint8_t flags;
    uint8_t padding[2];
    uint32_t pmuReservedSize;
    uint64_t verified;
};
static_assert(sizeof(GspFwWprMeta) == 256);
static_assert(offsetof(GspFwWprMeta, magic) == 0);
static_assert(offsetof(GspFwWprMeta, revision) == 8);
static_assert(offsetof(GspFwWprMeta, sysmemAddrOfRadix3Elf) == 16);
static_assert(offsetof(GspFwWprMeta, sizeOfRadix3Elf) == 24);
static_assert(offsetof(GspFwWprMeta, sysmemAddrOfBootloader) == 32);
static_assert(offsetof(GspFwWprMeta, sizeOfBootloader) == 40);
static_assert(offsetof(GspFwWprMeta, bootloaderCodeOffset) == 48);
static_assert(offsetof(GspFwWprMeta, bootloaderDataOffset) == 56);
static_assert(offsetof(GspFwWprMeta, bootloaderManifestOffset) == 64);
static_assert(offsetof(GspFwWprMeta, sysmemAddrOfSignature) == 72);
static_assert(offsetof(GspFwWprMeta, sizeOfSignature) == 80);
static_assert(offsetof(GspFwWprMeta, gspFwHeapFreeListWprOffset) == 72);
static_assert(offsetof(GspFwWprMeta, unused0) == 76);
static_assert(offsetof(GspFwWprMeta, unused1) == 80);
static_assert(offsetof(GspFwWprMeta, gspFwRsvdStart) == 88);
static_assert(offsetof(GspFwWprMeta, nonWprHeapOffset) == 96);
static_assert(offsetof(GspFwWprMeta, nonWprHeapSize) == 104);
static_assert(offsetof(GspFwWprMeta, gspFwWprStart) == 112);
static_assert(offsetof(GspFwWprMeta, gspFwHeapOffset) == 120);
static_assert(offsetof(GspFwWprMeta, gspFwHeapSize) == 128);
static_assert(offsetof(GspFwWprMeta, gspFwOffset) == 136);
static_assert(offsetof(GspFwWprMeta, bootBinOffset) == 144);
static_assert(offsetof(GspFwWprMeta, frtsOffset) == 152);
static_assert(offsetof(GspFwWprMeta, frtsSize) == 160);
static_assert(offsetof(GspFwWprMeta, gspFwWprEnd) == 168);
static_assert(offsetof(GspFwWprMeta, fbSize) == 176);
static_assert(offsetof(GspFwWprMeta, vgaWorkspaceOffset) == 184);
static_assert(offsetof(GspFwWprMeta, vgaWorkspaceSize) == 192);
static_assert(offsetof(GspFwWprMeta, bootCount) == 200);
static_assert(offsetof(GspFwWprMeta, partitionRpcAddr) == 208);
static_assert(offsetof(GspFwWprMeta, partitionRpcRequestOffset) == 216);
static_assert(offsetof(GspFwWprMeta, partitionRpcReplyOffset) == 218);
static_assert(offsetof(GspFwWprMeta, elfCodeOffset) == 220);
static_assert(offsetof(GspFwWprMeta, elfDataOffset) == 224);
static_assert(offsetof(GspFwWprMeta, elfCodeSize) == 228);
static_assert(offsetof(GspFwWprMeta, elfDataSize) == 232);
static_assert(offsetof(GspFwWprMeta, lsUcodeVersion) == 236);
static_assert(offsetof(GspFwWprMeta, partitionRpcPadding) == 208);
static_assert(offsetof(GspFwWprMeta, sysmemAddrOfCrashReportQueue) == 224);
static_assert(offsetof(GspFwWprMeta, sizeOfCrashReportQueue) == 232);
static_assert(offsetof(GspFwWprMeta, lsUcodeVersionPadding) == 236);
static_assert(offsetof(GspFwWprMeta, gspFwHeapVfPartitionCount) == 240);
static_assert(offsetof(GspFwWprMeta, flags) == 241);
static_assert(offsetof(GspFwWprMeta, padding) == 242);
static_assert(offsetof(GspFwWprMeta, pmuReservedSize) == 244);
static_assert(offsetof(GspFwWprMeta, verified) == 248);

struct LibosMemoryRegionInitArgument {  // nv.py:231
    uint64_t id8;
    uint64_t pa;
    uint64_t size;
    uint8_t kind;
    uint8_t loc;
    uint8_t _pad0[6];
};
static_assert(sizeof(LibosMemoryRegionInitArgument) == 32);
static_assert(offsetof(LibosMemoryRegionInitArgument, id8) == 0);
static_assert(offsetof(LibosMemoryRegionInitArgument, pa) == 8);
static_assert(offsetof(LibosMemoryRegionInitArgument, size) == 16);
static_assert(offsetof(LibosMemoryRegionInitArgument, kind) == 24);
static_assert(offsetof(LibosMemoryRegionInitArgument, loc) == 25);

struct NVDM_PAYLOAD_COT {  // nv.py:17
    uint16_t version;
    uint16_t size;
    uint64_t gspFmcSysmemOffset;
    uint64_t frtsSysmemOffset;
    uint32_t frtsSysmemSize;
    uint64_t frtsVidmemOffset;
    uint32_t frtsVidmemSize;
    uint32_t hash384[12];
    uint32_t publicKey[96];
    uint32_t signature[96];
    uint64_t gspBootArgsSysmemOffset;
};
static_assert(sizeof(NVDM_PAYLOAD_COT) == 860);
static_assert(offsetof(NVDM_PAYLOAD_COT, version) == 0);
static_assert(offsetof(NVDM_PAYLOAD_COT, size) == 2);
static_assert(offsetof(NVDM_PAYLOAD_COT, gspFmcSysmemOffset) == 4);
static_assert(offsetof(NVDM_PAYLOAD_COT, frtsSysmemOffset) == 12);
static_assert(offsetof(NVDM_PAYLOAD_COT, frtsSysmemSize) == 20);
static_assert(offsetof(NVDM_PAYLOAD_COT, frtsVidmemOffset) == 24);
static_assert(offsetof(NVDM_PAYLOAD_COT, frtsVidmemSize) == 32);
static_assert(offsetof(NVDM_PAYLOAD_COT, hash384) == 36);
static_assert(offsetof(NVDM_PAYLOAD_COT, publicKey) == 84);
static_assert(offsetof(NVDM_PAYLOAD_COT, signature) == 468);
static_assert(offsetof(NVDM_PAYLOAD_COT, gspBootArgsSysmemOffset) == 852);

struct RM_RISCV_UCODE_DESC {  // nv.py:182
    uint32_t version;
    uint32_t bootloaderOffset;
    uint32_t bootloaderSize;
    uint32_t bootloaderParamOffset;
    uint32_t bootloaderParamSize;
    uint32_t riscvElfOffset;
    uint32_t riscvElfSize;
    uint32_t appVersion;
    uint32_t manifestOffset;
    uint32_t manifestSize;
    uint32_t monitorDataOffset;
    uint32_t monitorDataSize;
    uint32_t monitorCodeOffset;
    uint32_t monitorCodeSize;
    uint32_t bIsMonitorEnabled;
    uint32_t swbromCodeOffset;
    uint32_t swbromCodeSize;
    uint32_t swbromDataOffset;
    uint32_t swbromDataSize;
    uint32_t fbReservedSize;
    uint32_t bSignedAsCode;
};
static_assert(sizeof(RM_RISCV_UCODE_DESC) == 84);
static_assert(offsetof(RM_RISCV_UCODE_DESC, version) == 0);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bootloaderOffset) == 4);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bootloaderSize) == 8);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bootloaderParamOffset) == 12);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bootloaderParamSize) == 16);
static_assert(offsetof(RM_RISCV_UCODE_DESC, riscvElfOffset) == 20);
static_assert(offsetof(RM_RISCV_UCODE_DESC, riscvElfSize) == 24);
static_assert(offsetof(RM_RISCV_UCODE_DESC, appVersion) == 28);
static_assert(offsetof(RM_RISCV_UCODE_DESC, manifestOffset) == 32);
static_assert(offsetof(RM_RISCV_UCODE_DESC, manifestSize) == 36);
static_assert(offsetof(RM_RISCV_UCODE_DESC, monitorDataOffset) == 40);
static_assert(offsetof(RM_RISCV_UCODE_DESC, monitorDataSize) == 44);
static_assert(offsetof(RM_RISCV_UCODE_DESC, monitorCodeOffset) == 48);
static_assert(offsetof(RM_RISCV_UCODE_DESC, monitorCodeSize) == 52);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bIsMonitorEnabled) == 56);
static_assert(offsetof(RM_RISCV_UCODE_DESC, swbromCodeOffset) == 60);
static_assert(offsetof(RM_RISCV_UCODE_DESC, swbromCodeSize) == 64);
static_assert(offsetof(RM_RISCV_UCODE_DESC, swbromDataOffset) == 68);
static_assert(offsetof(RM_RISCV_UCODE_DESC, swbromDataSize) == 72);
static_assert(offsetof(RM_RISCV_UCODE_DESC, fbReservedSize) == 76);
static_assert(offsetof(RM_RISCV_UCODE_DESC, bSignedAsCode) == 80);

struct msgqTxHeader {  // nv.py:240
    uint32_t version;
    uint32_t size;
    uint32_t msgSize;
    uint32_t msgCount;
    uint32_t writePtr;
    uint32_t flags;
    uint32_t rxHdrOff;
    uint32_t entryOff;
};
static_assert(sizeof(msgqTxHeader) == 32);
static_assert(offsetof(msgqTxHeader, version) == 0);
static_assert(offsetof(msgqTxHeader, size) == 4);
static_assert(offsetof(msgqTxHeader, msgSize) == 8);
static_assert(offsetof(msgqTxHeader, msgCount) == 12);
static_assert(offsetof(msgqTxHeader, writePtr) == 16);
static_assert(offsetof(msgqTxHeader, flags) == 20);
static_assert(offsetof(msgqTxHeader, rxHdrOff) == 24);
static_assert(offsetof(msgqTxHeader, entryOff) == 28);

struct union_rpc_message_rpc_union_field_v03_00 {  // nv.py:4160
    union {
        uint32_t spare;
        uint32_t cpuRmGfid;
    };
};
static_assert(sizeof(union_rpc_message_rpc_union_field_v03_00) == 4);
static_assert(offsetof(union_rpc_message_rpc_union_field_v03_00, spare) == 0);
static_assert(offsetof(union_rpc_message_rpc_union_field_v03_00, cpuRmGfid) == 0);
using rpc_message_rpc_union_field_v03_00 = union_rpc_message_rpc_union_field_v03_00;
using rpc_message_rpc_union_field_v = union_rpc_message_rpc_union_field_v03_00;

struct struct_rpc_message_header_v03_00 {  // nv.py:4168
    uint32_t header_version;
    uint32_t signature;
    uint32_t length;
    uint32_t function;
    uint32_t rpc_result;
    uint32_t rpc_result_private;
    uint32_t sequence;
    union_rpc_message_rpc_union_field_v03_00 u;
};
static_assert(sizeof(struct_rpc_message_header_v03_00) == 32);
static_assert(offsetof(struct_rpc_message_header_v03_00, header_version) == 0);
static_assert(offsetof(struct_rpc_message_header_v03_00, signature) == 4);
static_assert(offsetof(struct_rpc_message_header_v03_00, length) == 8);
static_assert(offsetof(struct_rpc_message_header_v03_00, function) == 12);
static_assert(offsetof(struct_rpc_message_header_v03_00, rpc_result) == 16);
static_assert(offsetof(struct_rpc_message_header_v03_00, rpc_result_private) == 20);
static_assert(offsetof(struct_rpc_message_header_v03_00, sequence) == 24);
static_assert(offsetof(struct_rpc_message_header_v03_00, u) == 28);
using rpc_message_header_v03_00 = struct_rpc_message_header_v03_00;
using rpc_message_header_v = struct_rpc_message_header_v03_00;

struct struct_nvfw_bin_hdr {  // nv.py:4687
    uint32_t bin_magic;
    uint32_t bin_ver;
    uint32_t bin_size;
    uint32_t header_offset;
    uint32_t data_offset;
    uint32_t data_size;
};
static_assert(sizeof(struct_nvfw_bin_hdr) == 24);
static_assert(offsetof(struct_nvfw_bin_hdr, bin_magic) == 0);
static_assert(offsetof(struct_nvfw_bin_hdr, bin_ver) == 4);
static_assert(offsetof(struct_nvfw_bin_hdr, bin_size) == 8);
static_assert(offsetof(struct_nvfw_bin_hdr, header_offset) == 12);
static_assert(offsetof(struct_nvfw_bin_hdr, data_offset) == 16);
static_assert(offsetof(struct_nvfw_bin_hdr, data_size) == 20);

struct struct_nvfw_hs_header_v2 {  // nv.py:4719
    uint32_t sig_prod_offset;
    uint32_t sig_prod_size;
    uint32_t patch_loc;
    uint32_t patch_sig;
    uint32_t meta_data_offset;
    uint32_t meta_data_size;
    uint32_t num_sig;
    uint32_t header_offset;
    uint32_t header_size;
};
static_assert(sizeof(struct_nvfw_hs_header_v2) == 36);
static_assert(offsetof(struct_nvfw_hs_header_v2, sig_prod_offset) == 0);
static_assert(offsetof(struct_nvfw_hs_header_v2, sig_prod_size) == 4);
static_assert(offsetof(struct_nvfw_hs_header_v2, patch_loc) == 8);
static_assert(offsetof(struct_nvfw_hs_header_v2, patch_sig) == 12);
static_assert(offsetof(struct_nvfw_hs_header_v2, meta_data_offset) == 16);
static_assert(offsetof(struct_nvfw_hs_header_v2, meta_data_size) == 20);
static_assert(offsetof(struct_nvfw_hs_header_v2, num_sig) == 24);
static_assert(offsetof(struct_nvfw_hs_header_v2, header_offset) == 28);
static_assert(offsetof(struct_nvfw_hs_header_v2, header_size) == 32);

struct struct_nvfw_hs_load_header_v2_app {  // nv.py:4751
    uint32_t offset;
    uint32_t size;
    uint32_t data_offset;
    uint32_t data_size;
};
static_assert(sizeof(struct_nvfw_hs_load_header_v2_app) == 16);
static_assert(offsetof(struct_nvfw_hs_load_header_v2_app, offset) == 0);
static_assert(offsetof(struct_nvfw_hs_load_header_v2_app, size) == 4);
static_assert(offsetof(struct_nvfw_hs_load_header_v2_app, data_offset) == 8);
static_assert(offsetof(struct_nvfw_hs_load_header_v2_app, data_size) == 12);

struct struct_nvfw_hs_load_header_v2 {  // nv.py:4742
    uint32_t os_code_offset;
    uint32_t os_code_size;
    uint32_t os_data_offset;
    uint32_t os_data_size;
    uint32_t num_apps;
    struct_nvfw_hs_load_header_v2_app app[0];
};
static_assert(sizeof(struct_nvfw_hs_load_header_v2) == 20);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, os_code_offset) == 0);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, os_code_size) == 4);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, os_data_offset) == 8);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, os_data_size) == 12);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, num_apps) == 16);
static_assert(offsetof(struct_nvfw_hs_load_header_v2, app) == 20);

#pragma pack(pop)

} // namespace nv
} // namespace tinygpu_device

#endif // LIBHMSBEAGLE_GPU_TINYGPUNVBOOTTABLES_H
