/*
 * TinyGPUNVTables.h -- GENERATED by make_tinygpu_nv_tables.py from tinygrad
 * (tinygrad/runtime/ops_nv.py, nv_gpu = nv_570). Do not edit.
 *
 * QMD field positions ({hi, lo} bit ranges, as tinygrad's QMD.fields) for
 * QMD v3 (NVC6C0_QMDV03_00, Ampere/Ada) and v5 (NVCEC0_QMDV05_00, Blackwell),
 * and the method and flag words ops_nv.py writes.
 */

#ifndef LIBHMSBEAGLE_GPU_TINYGPUNVTABLES_H
#define LIBHMSBEAGLE_GPU_TINYGPUNVTABLES_H

#include <cstdint>

namespace tinygpu_device {
namespace nvt {

struct Bits { uint16_t hi, lo; };
constexpr Bits kAbsent = {0xffff, 0xffff};
constexpr bool present(Bits b) { return b.hi != 0xffff; }

enum QmdField {
    QMD_MAJOR_VERSION,
    QMD_TYPE,
    QMD_GROUP_ID,
    SM_GLOBAL_CACHING_ENABLE,
    INVALIDATE_TEXTURE_HEADER_CACHE,
    INVALIDATE_TEXTURE_SAMPLER_CACHE,
    INVALIDATE_TEXTURE_DATA_CACHE,
    INVALIDATE_SHADER_DATA_CACHE,
    API_VISIBLE_CALL_LIMIT,
    SAMPLER_INDEX,
    BARRIER_COUNT,
    CWD_MEMBAR_TYPE,
    CONSTANT_BUFFER_INVALIDATE_0,
    MIN_SM_CONFIG_SHARED_MEM_SIZE,
    TARGET_SM_CONFIG_SHARED_MEM_SIZE,
    MAX_SM_CONFIG_SHARED_MEM_SIZE,
    PROGRAM_PREFETCH_SIZE,
    SASS_VERSION,
    PROGRAM_PREFETCH_ADDR_UPPER_SHIFTED,
    PROGRAM_PREFETCH_ADDR_LOWER_SHIFTED,
    PROGRAM_ADDRESS_UPPER,
    PROGRAM_ADDRESS_LOWER,
    PROGRAM_ADDRESS_UPPER_SHIFTED4,
    PROGRAM_ADDRESS_LOWER_SHIFTED4,
    REGISTER_COUNT_V,
    REGISTER_COUNT,
    SHARED_MEMORY_SIZE,
    SHARED_MEMORY_SIZE_SHIFTED7,
    SHADER_LOCAL_MEMORY_HIGH_SIZE,
    SHADER_LOCAL_MEMORY_HIGH_SIZE_SHIFTED4,
    CTA_RASTER_WIDTH,
    CTA_RASTER_HEIGHT,
    CTA_RASTER_DEPTH,
    GRID_WIDTH,
    GRID_HEIGHT,
    GRID_DEPTH,
    CTA_THREAD_DIMENSION0,
    CTA_THREAD_DIMENSION1,
    CTA_THREAD_DIMENSION2,
    RELEASE0_ENABLE,
    RELEASE0_ADDRESS_LOWER,
    RELEASE0_ADDRESS_UPPER,
    RELEASE0_PAYLOAD_LOWER,
    RELEASE0_PAYLOAD_UPPER,
    RELEASE_SEMAPHORE0_ADDR_LOWER,
    RELEASE_SEMAPHORE0_ADDR_UPPER,
    RELEASE_SEMAPHORE0_PAYLOAD_LOWER,
    RELEASE_SEMAPHORE0_PAYLOAD_UPPER,
    DEPENDENT_QMD0_POINTER,
    DEPENDENT_QMD0_ACTION,
    DEPENDENT_QMD0_PREFETCH,
    DEPENDENT_QMD0_ENABLE,
    NUM_QMD_FIELDS
};

enum QmdIndexedField {
    CONSTANT_BUFFER_ADDR_UPPER,
    CONSTANT_BUFFER_ADDR_LOWER,
    CONSTANT_BUFFER_ADDR_UPPER_SHIFTED6,
    CONSTANT_BUFFER_ADDR_LOWER_SHIFTED6,
    CONSTANT_BUFFER_SIZE_SHIFTED4,
    CONSTANT_BUFFER_VALID,
    NUM_QMD_INDEXED
};

constexpr uint32_t kQmdV3Bytes = 256;
constexpr Bits kQmdV3[NUM_QMD_FIELDS] = {
    {583, 580},  // qmd_major_version
    {65535, 65535},  // qmd_type
    {133, 128},  // qmd_group_id
    {134, 134},  // sm_global_caching_enable
    {186, 186},  // invalidate_texture_header_cache
    {187, 187},  // invalidate_texture_sampler_cache
    {188, 188},  // invalidate_texture_data_cache
    {189, 189},  // invalidate_shader_data_cache
    {378, 378},  // api_visible_call_limit
    {382, 382},  // sampler_index
    {767, 763},  // barrier_count
    {369, 368},  // cwd_membar_type
    {1074, 1074},  // constant_buffer_invalidate_0
    {567, 562},  // min_sm_config_shared_mem_size
    {662, 657},  // target_sm_config_shared_mem_size
    {574, 569},  // max_sm_config_shared_mem_size
    {1649, 1641},  // program_prefetch_size
    {1663, 1656},  // sass_version
    {1640, 1632},  // program_prefetch_addr_upper_shifted
    {287, 256},  // program_prefetch_addr_lower_shifted
    {1584, 1568},  // program_address_upper
    {1567, 1536},  // program_address_lower
    {65535, 65535},  // program_address_upper_shifted4
    {65535, 65535},  // program_address_lower_shifted4
    {656, 648},  // register_count_v
    {65535, 65535},  // register_count
    {561, 544},  // shared_memory_size
    {65535, 65535},  // shared_memory_size_shifted7
    {1623, 1600},  // shader_local_memory_high_size
    {65535, 65535},  // shader_local_memory_high_size_shifted4
    {415, 384},  // cta_raster_width
    {431, 416},  // cta_raster_height
    {463, 448},  // cta_raster_depth
    {65535, 65535},  // grid_width
    {65535, 65535},  // grid_height
    {65535, 65535},  // grid_depth
    {607, 592},  // cta_thread_dimension0
    {623, 608},  // cta_thread_dimension1
    {639, 624},  // cta_thread_dimension2
    {823, 823},  // release0_enable
    {799, 768},  // release0_address_lower
    {807, 800},  // release0_address_upper
    {863, 832},  // release0_payload_lower
    {895, 864},  // release0_payload_upper
    {65535, 65535},  // release_semaphore0_addr_lower
    {65535, 65535},  // release_semaphore0_addr_upper
    {65535, 65535},  // release_semaphore0_payload_lower
    {65535, 65535},  // release_semaphore0_payload_upper
    {511, 480},  // dependent_qmd0_pointer
    {515, 513},  // dependent_qmd0_action
    {516, 516},  // dependent_qmd0_prefetch
    {512, 512},  // dependent_qmd0_enable
};
constexpr Bits kQmdV3Indexed[NUM_QMD_INDEXED][8] = {
    {{1072, 1056}, {1136, 1120}, {1200, 1184}, {1264, 1248}, {1328, 1312}, {1392, 1376}, {1456, 1440}, {1520, 1504}},  // constant_buffer_addr_upper_i
    {{1055, 1024}, {1119, 1088}, {1183, 1152}, {1247, 1216}, {1311, 1280}, {1375, 1344}, {1439, 1408}, {1503, 1472}},  // constant_buffer_addr_lower_i
    {{65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}},  // constant_buffer_addr_upper_shifted6_i
    {{65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}},  // constant_buffer_addr_lower_shifted6_i
    {{1087, 1075}, {1151, 1139}, {1215, 1203}, {1279, 1267}, {1343, 1331}, {1407, 1395}, {1471, 1459}, {1535, 1523}},  // constant_buffer_size_shifted4_i
    {{640, 640}, {641, 641}, {642, 642}, {643, 643}, {644, 644}, {645, 645}, {646, 646}, {647, 647}},  // constant_buffer_valid_i
};

constexpr uint32_t kQmdV5Bytes = 384;
constexpr Bits kQmdV5[NUM_QMD_FIELDS] = {
    {471, 468},  // qmd_major_version
    {153, 151},  // qmd_type
    {149, 144},  // qmd_group_id
    {65535, 65535},  // sm_global_caching_enable
    {472, 472},  // invalidate_texture_header_cache
    {473, 473},  // invalidate_texture_sampler_cache
    {474, 474},  // invalidate_texture_data_cache
    {475, 475},  // invalidate_shader_data_cache
    {456, 456},  // api_visible_call_limit
    {457, 457},  // sampler_index
    {1141, 1137},  // barrier_count
    {625, 624},  // cwd_membar_type
    {1859, 1859},  // constant_buffer_invalidate_0
    {1168, 1163},  // min_sm_config_shared_mem_size
    {1180, 1175},  // target_sm_config_shared_mem_size
    {1174, 1169},  // max_sm_config_shared_mem_size
    {1085, 1077},  // program_prefetch_size
    {455, 448},  // sass_version
    {1936, 1920},  // program_prefetch_addr_upper_shifted
    {1919, 1888},  // program_prefetch_addr_lower_shifted
    {65535, 65535},  // program_address_upper
    {65535, 65535},  // program_address_lower
    {1076, 1056},  // program_address_upper_shifted4
    {1055, 1024},  // program_address_lower_shifted4
    {65535, 65535},  // register_count_v
    {1136, 1128},  // register_count
    {65535, 65535},  // shared_memory_size
    {1162, 1152},  // shared_memory_size_shifted7
    {65535, 65535},  // shader_local_memory_high_size
    {1215, 1200},  // shader_local_memory_high_size_shifted4
    {65535, 65535},  // cta_raster_width
    {65535, 65535},  // cta_raster_height
    {65535, 65535},  // cta_raster_depth
    {1279, 1248},  // grid_width
    {1295, 1280},  // grid_height
    {1327, 1312},  // grid_depth
    {1103, 1088},  // cta_thread_dimension0
    {1119, 1104},  // cta_thread_dimension1
    {1127, 1120},  // cta_thread_dimension2
    {288, 288},  // release0_enable
    {65535, 65535},  // release0_address_lower
    {65535, 65535},  // release0_address_upper
    {65535, 65535},  // release0_payload_lower
    {65535, 65535},  // release0_payload_upper
    {511, 480},  // release_semaphore0_addr_lower
    {536, 512},  // release_semaphore0_addr_upper
    {575, 544},  // release_semaphore0_payload_lower
    {607, 576},  // release_semaphore0_payload_upper
    {415, 384},  // dependent_qmd0_pointer
    {339, 337},  // dependent_qmd0_action
    {340, 340},  // dependent_qmd0_prefetch
    {336, 336},  // dependent_qmd0_enable
};
constexpr Bits kQmdV5Indexed[NUM_QMD_INDEXED][8] = {
    {{65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}},  // constant_buffer_addr_upper_i
    {{65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}, {65535, 65535}},  // constant_buffer_addr_lower_i
    {{1394, 1376}, {1458, 1440}, {1522, 1504}, {1586, 1568}, {1650, 1632}, {1714, 1696}, {1778, 1760}, {1842, 1824}},  // constant_buffer_addr_upper_shifted6_i
    {{1375, 1344}, {1439, 1408}, {1503, 1472}, {1567, 1536}, {1631, 1600}, {1695, 1664}, {1759, 1728}, {1823, 1792}},  // constant_buffer_addr_lower_shifted6_i
    {{1407, 1395}, {1471, 1459}, {1535, 1523}, {1599, 1587}, {1663, 1651}, {1727, 1715}, {1791, 1779}, {1855, 1843}},  // constant_buffer_size_shifted4_i
    {{1856, 1856}, {1860, 1860}, {1864, 1864}, {1868, 1868}, {1872, 1872}, {1876, 1876}, {1880, 1880}, {1884, 1884}},  // constant_buffer_valid_i
};

constexpr uint32_t M_SEM_ADDR_LO = 0x5c;
constexpr uint32_t M_NON_STALL_INTERRUPT = 0x20;
constexpr uint32_t M_SET_OBJECT = 0x0;
constexpr uint32_t M_SET_SHADER_LOCAL_MEMORY_WINDOW_A = 0x7b0;
constexpr uint32_t M_SET_SHADER_SHARED_MEMORY_WINDOW_A = 0x2a0;
constexpr uint32_t M_SET_SHADER_LOCAL_MEMORY_A = 0x790;
constexpr uint32_t M_SET_SHADER_LOCAL_MEMORY_NON_THROTTLED_A = 0x2e4;
constexpr uint32_t M_INVALIDATE_SHADER_CACHES_NO_WFI = 0x1698;
constexpr uint32_t M_SEND_PCAS_A = 0x2b4;
constexpr uint32_t M_SEND_SIGNALING_PCAS2_B = 0x2c0;
constexpr uint32_t M_DMA_OFFSET_IN_UPPER = 0x400;
constexpr uint32_t M_DMA_LINE_LENGTH_IN = 0x418;
constexpr uint32_t M_DMA_LAUNCH_DMA = 0x300;
constexpr uint32_t M_DMA_SET_SEMAPHORE_A = 0x240;

constexpr uint32_t F_SEM_ACQUIRE_GEQ_64 = 0x1000003;
constexpr uint32_t F_SEM_RELEASE_64_TIMESTAMP = 0x3100001;
constexpr uint32_t F_INVALIDATE_ALL = 0x1011;
constexpr uint32_t F_DMA_COPY = 0x182;
constexpr uint32_t F_DMA_SEMAPHORE_RELEASE = 0x14;

constexpr uint32_t BLACKWELL_COMPUTE_A = 0xcdc0;
constexpr uint32_t QMD_TYPE_GRID_CTA = 0x2;
constexpr uint32_t CWD_MEMBAR_TYPE_L1_SYSMEMBAR = 0x1;

} // namespace nvt
} // namespace tinygpu_device

#endif // LIBHMSBEAGLE_GPU_TINYGPUNVTABLES_H
