/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore__
#define __dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobject JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_getGPUInfo (JNIEnv *env, jclass);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_initialize (JNIEnv *env, jobject, jint, jint, jint, jint, jint, jint, jint);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_freeNativeMemory (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_setTipPartials (JNIEnv *env, jobject, jint, jint, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_setTipStates (JNIEnv *env, jobject, jint, jint, jintArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updateRootFrequencies (JNIEnv *env, jobject, jint, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updateEigenDecomposition (JNIEnv *env, jobject, jint, jobjectArray, jobjectArray, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updateCategoryRates (JNIEnv *env, jobject, jint, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updateCategoryProportions (JNIEnv *env, jobject, jint, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updateMatrices (JNIEnv *env, jobject, jint, jintArray, jdoubleArray, jint);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_updatePartials (JNIEnv *env, jobject, jint, jintArray, jintArray, jint, jboolean rescale);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_calculateLogLikelihoods (JNIEnv *env, jobject, jint, jint, jdoubleArray);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_storeState (JNIEnv *env, jobject, jint);
JNIEXPORT void JNICALL Java_dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore_restoreState (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __dr_evomodel_newtreelikelihood_ThreadedGPULikelihoodCore__ */
