name: CI BIT

on:
  push:
    branches:    
    - basta
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build on Linux x86_64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake file

    - uses: Jimver/cuda-toolkit@v0.2.24
      id: cuda-toolkit
      with:
        cuda: '12.5.0'  

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_BIT=ON -DBUILD_CUDA=ON
        make -j
        file libhmsbeagle/libhmsbeagle.so.* | grep x86-64
        
    - name: Upload CPack files
      uses: actions/upload-artifact@v4
      with:
        name: Debug files
        path: .        
