name: Build mac package

# on: 
#   workflow_dispatch:
  
on:
  push:
    branches:
    - master
    - basta  
  
jobs:
  build:
    name: Build on Mac
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install the Apple certificate
      env:
        APPLICATION_CERTIFICATES_BASE64: ${{ secrets.APPLE_APPLICATION_CERTIFICATES_BASE64 }}
        CERTIFICATES_PASSWORD: ${{ secrets.APPLE_CERTIFICATES_PASSWORD }}     
        KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        SIGNER: ${{ secrets.APPLE_SIGNER }}     
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_API_PASSWORD }}
        TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}        
      run: |
        # create variables
        APPLICATION_CERTIFICATE_PATH=$RUNNER_TEMP/application_certificates.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$APPLICATION_CERTIFICATES_BASE64" | base64 --decode -o $APPLICATION_CERTIFICATE_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $APPLICATION_CERTIFICATE_PATH -P "$CERTIFICATES_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
#         security list-keychain -d user -s $KEYCHAIN_PATH
        
        # add notary password
        xcrun notarytool store-credentials --apple-id "$APPLE_ID" --password "$APP_SPECIFIC_PASSWORD" --team-id "$TEAM_ID" "my-notary-profile"
        
    - name: Build BIT package
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_BIT=ON -DBUILD_OPENCL=ON
        make
        cpack .    
    
    - name: Sign BIT package
      env:
        SIGNER: ${{ secrets.APPLE_SIGNER }}    
      run: |   
        # sign
        codesign -s "$SIGNER" -v --deep build/BEAGLE-BIT-4.1.0-Darwin.pkg
#         xcrun notarytool submit build/BEAGLE-BIT-4.1.0-Darwin.pkg --keychain-profile "my-notary-profile" --wait 
        
#     - name: Notarize BIT package
#       run: |      
#         xcrun notarytool submit build/BEAGLE-BIT-4.1.0-Darwin.pkg --keychain-profile "my-notary-profile" --wait 
              
#         REQUEST_UUID=$(
#         xcrun notarytool submit build/BEAGLE-BIT-4.1.0-Darwin.pkg --keychain-profile "my-notary-profile" --wait | grep "id:" | awk '{print $2}'
#         )
              
#    - name: Notarize BIT package
#       run: |
#         # Submit for notarization
#         REQUEST_UUID=$(xcrun notarytool submit "build/BEAGLE-BIT-4.1.0-Darwin.pkg" --keychain-profile "my-notary-profile" --wait | grep "id:" | awk '{print $2}')
# 
#         # Check notarization status and staple
#         if [[ -n "$REQUEST_UUID" ]]; then
#           echo "Notarization submitted with UUID: $REQUEST_UUID"
#           xcrun notarytool log "$REQUEST_UUID" --keychain-profile "my-notary-profile"
#           xcrun stapler staple "build/BEAGLE-BIT-4.1.0-Darwin.pkg"
#           echo "Notarization successful and stapled."
#         else
#           echo "Notarization submission failed."
#           exit 1
#         fi              
                 
    - name: Upload BIT package
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Mac_BIT_installer
        path: build/BEAGLE-BIT-4.1.0-Darwin.pkg        
