name: win-build

# on: workflow_dispatch

on:
  push:
    branches:
    - basta

jobs:
  build:
    name: Build release on windoz
    runs-on: windows-2022

    steps:    
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1 # This action sets up the environment
      - name: Build
        run: |        
          mkdir build
          cd build
          cmake ..
          devenv BEAGLE.sln /build "Release"
          cpack .
